package org.sagebionetworks.openchallenges.api.gateway.configuration;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;
import jakarta.annotation.PostConstruct;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import lombok.extern.slf4j.Slf4j;

/**
 * Configuration for route-to-scope mappings.
 * This configuration loads the route-scopes.yml file generated by OpenApiScopeMapper.
 */
@Slf4j
@Component
public class RouteScopeConfiguration {
  private static final ObjectMapper yamlMapper = new ObjectMapper(new YAMLFactory());

  private Map<String, RouteConfig> routeScopes;

  @PostConstruct
  public void loadRouteScopeConfig() {
    try {
      ClassPathResource resource = new ClassPathResource("route-scopes.yml");
      if (!resource.exists()) {
        log.warn("route-scopes.yml not found in classpath. No route scope mappings will be available.");
        log.warn("To generate route scopes, run: nx run openchallenges-api-gateway:generateRouteScopes");
        this.routeScopes = Map.of();
        return;
      }

      try (InputStream inputStream = resource.getInputStream()) {
        Map<String, Object> config = yamlMapper.readValue(inputStream, Map.class);
        this.routeScopes = parseRouteScopeConfig(config);
        log.info("Loaded {} route scope mappings from route-scopes.yml", this.routeScopes.size());
      }
    } catch (IOException e) {
      log.error("Failed to load route-scopes.yml", e);
      this.routeScopes = Map.of();
    }
  }

  @SuppressWarnings("unchecked")
  private Map<String, RouteConfig> parseRouteScopeConfig(Map<String, Object> config) {
    // Navigate to openchallenges.gateway.route-scopes
    Map<String, Object> openchallenges = (Map<String, Object>) config.get("openchallenges");
    if (openchallenges == null) {
      return Map.of();
    }

    Map<String, Object> gateway = (Map<String, Object>) openchallenges.get("gateway");
    if (gateway == null) {
      return Map.of();
    }

    Map<String, Map<String, Object>> scopes = (Map<String, Map<String, Object>>) gateway.get("route-scopes");
    if (scopes == null) {
      return Map.of();
    }

    // Convert to RouteConfig objects
    return scopes.entrySet().stream()
      .collect(java.util.stream.Collectors.toMap(
        Map.Entry::getKey,
        entry -> {
          RouteConfig routeConfig = new RouteConfig();
          List<String> scopeList = (List<String>) entry.getValue().get("scopes");
          routeConfig.setScopes(scopeList != null ? scopeList : List.of());
          
          // Parse anonymous access flag
          Boolean anonymousAccess = (Boolean) entry.getValue().get("anonymousAccess");
          routeConfig.setAnonymousAccess(anonymousAccess != null && anonymousAccess);
          
          return routeConfig;
        }
      ));
  }

  public Map<String, RouteConfig> getRouteScopes() {
    return routeScopes != null ? routeScopes : Map.of();
  }

  public void setRouteScopes(Map<String, RouteConfig> routeScopes) {
    this.routeScopes = routeScopes;
  }

  /**
   * Get the required scopes for a given HTTP method and path.
   *
   * @param method HTTP method (GET, POST, etc.)
   * @param path   URL path
   * @return List of required scopes, or empty list if no scopes required
   */
  public List<String> getScopesForRoute(String method, String path) {
    if (routeScopes == null) {
      return List.of();
    }
    
    String routeKey = method.toUpperCase() + " " + path;
    RouteConfig config = routeScopes.get(routeKey);
    
    if (config != null && config.getScopes() != null) {
      return config.getScopes();
    }
    
    return List.of();
  }

  /**
   * Check if a route allows anonymous access.
   *
   * @param method HTTP method (GET, POST, etc.)
   * @param path   URL path
   * @return true if the route allows anonymous access, false otherwise
   */
  public boolean isAnonymousAccessAllowed(String method, String path) {
    if (routeScopes == null) {
      return false;
    }
    
    String routeKey = method.toUpperCase() + " " + path;
    RouteConfig config = routeScopes.get(routeKey);
    
    return config != null && config.isAnonymousAccess();
  }

  public static class RouteConfig {
    private List<String> scopes;
    private boolean anonymousAccess = false;

    public List<String> getScopes() {
      return scopes;
    }

    public void setScopes(List<String> scopes) {
      this.scopes = scopes;
    }

    public boolean isAnonymousAccess() {
      return anonymousAccess;
    }

    public void setAnonymousAccess(boolean anonymousAccess) {
      this.anonymousAccess = anonymousAccess;
    }
  }
}
