/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { OrgSagebionetworksRepoModelEntitybundleV2EntityBundle } from '../model/orgSagebionetworksRepoModelEntitybundleV2EntityBundle';
// @ts-ignore
import { OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate } from '../model/orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate';
// @ts-ignore
import { OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest } from '../model/orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class EntityBundleServicesV2Service {
  protected basePath = 'https://repo-prod.prod.sagebase.org';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration: Configuration,
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (Array.isArray(basePath) && basePath.length > 0) {
        basePath = basePath[0];
      }

      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  // @ts-ignore
  private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach(
          (elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)),
        );
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) =>
            (httpParams = this.addToHttpParamsRecursive(
              httpParams,
              value[k],
              key != null ? `${key}[${k}]` : k,
            )),
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * @param orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate
   * @param generatedBy
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postRepoV1EntityBundle2Create(
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>;
  public postRepoV1EntityBundle2Create(
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpResponse<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public postRepoV1EntityBundle2Create(
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpEvent<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public postRepoV1EntityBundle2Create(
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<any> {
    if (
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate === null ||
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate === undefined
    ) {
      throw new Error(
        'Required parameter orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate was null or undefined when calling postRepoV1EntityBundle2Create.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (generatedBy !== undefined && generatedBy !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>generatedBy,
        'generatedBy',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (bearerAuth) required
    localVarCredential = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/repo/v1/entity/bundle2/create`;
    return this.httpClient.post<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>(
      `${this.configuration.basePath}${localVarPath}`,
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param id - The ID of the entity to fetch.
   * @param orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>;
  public postRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpResponse<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public postRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpEvent<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public postRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling postRepoV1EntityIdBundle2.',
      );
    }
    if (
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest === null ||
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest === undefined
    ) {
      throw new Error(
        'Required parameter orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest was null or undefined when calling postRepoV1EntityIdBundle2.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (bearerAuth) required
    localVarCredential = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/repo/v1/entity/${this.configuration.encodeParam({ name: 'id', value: id, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/bundle2`;
    return this.httpClient.post<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>(
      `${this.configuration.basePath}${localVarPath}`,
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param id - The ID of the entity to fetch.
   * @param versionNumber - The version of the entity to fetch
   * @param orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public postRepoV1EntityIdVersionVersionNumberBundle2(
    id: string,
    versionNumber: number,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>;
  public postRepoV1EntityIdVersionVersionNumberBundle2(
    id: string,
    versionNumber: number,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpResponse<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public postRepoV1EntityIdVersionVersionNumberBundle2(
    id: string,
    versionNumber: number,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpEvent<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public postRepoV1EntityIdVersionVersionNumberBundle2(
    id: string,
    versionNumber: number,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling postRepoV1EntityIdVersionVersionNumberBundle2.',
      );
    }
    if (versionNumber === null || versionNumber === undefined) {
      throw new Error(
        'Required parameter versionNumber was null or undefined when calling postRepoV1EntityIdVersionVersionNumberBundle2.',
      );
    }
    if (
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest === null ||
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest === undefined
    ) {
      throw new Error(
        'Required parameter orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest was null or undefined when calling postRepoV1EntityIdVersionVersionNumberBundle2.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (bearerAuth) required
    localVarCredential = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/repo/v1/entity/${this.configuration.encodeParam({ name: 'id', value: id, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/version/${this.configuration.encodeParam({ name: 'versionNumber', value: versionNumber, in: 'path', style: 'simple', explode: false, dataType: 'number', dataFormat: undefined })}/bundle2`;
    return this.httpClient.post<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>(
      `${this.configuration.basePath}${localVarPath}`,
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleRequest,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * @param id
   * @param orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate
   * @param generatedBy
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public putRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>;
  public putRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpResponse<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public putRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<HttpEvent<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>>;
  public putRepoV1EntityIdBundle2(
    id: string,
    orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate: OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
    generatedBy?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext },
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling putRepoV1EntityIdBundle2.',
      );
    }
    if (
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate === null ||
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate === undefined
    ) {
      throw new Error(
        'Required parameter orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate was null or undefined when calling putRepoV1EntityIdBundle2.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (generatedBy !== undefined && generatedBy !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>generatedBy,
        'generatedBy',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (bearerAuth) required
    localVarCredential = this.configuration.lookupCredential('bearerAuth');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set('Authorization', 'Bearer ' + localVarCredential);
    }

    let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    let localVarHttpContext: HttpContext | undefined = options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/repo/v1/entity/${this.configuration.encodeParam({ name: 'id', value: id, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/bundle2`;
    return this.httpClient.put<OrgSagebionetworksRepoModelEntitybundleV2EntityBundle>(
      `${this.configuration.basePath}${localVarPath}`,
      orgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
