#' Schematic REST API
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: 0.1.0
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title TangledTree operations
#' @description TangledTreeApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ GetTangledTreeLayers } \emph{ Get tangled tree node layers to display for a given data model and figure type }
#' Get tangled tree node layers to display for a given data model and figure type
#'
#' \itemize{
#' \item \emph{ @param } schema_url character
#' \item \emph{ @param } figure_type Enum < [component, dependency] >
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : character
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : BasicError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTangledTreeText } \emph{ Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type }
#' Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type
#'
#' \itemize{
#' \item \emph{ @param } schema_url character
#' \item \emph{ @param } figure_type Enum < [component, dependency] >
#' \item \emph{ @param } text_format Enum < [plain, highlighted] >
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : object
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | The request cannot be fulfilled due to an unexpected server error
#'
#' \item return type : BasicError
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  GetTangledTreeLayers  ####################
#'
#' library(openapi)
#' var_schema_url <- "schema_url_example" # character | The URL of a schema in jsonld or csv form
#' var_figure_type <- "component" # character | Figure type to generate. (Optional)
#'
#' #Get tangled tree node layers to display for a given data model and figure type
#' api_instance <- TangledTreeApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetTangledTreeLayers(var_schema_url, figure_type = var_figure_typedata_file = "result.txt")
#' result <- api_instance$GetTangledTreeLayers(var_schema_url, figure_type = var_figure_type)
#' dput(result)
#'
#'
#' ####################  GetTangledTreeText  ####################
#'
#' library(openapi)
#' var_schema_url <- "schema_url_example" # character | The URL of a schema in jsonld or csv form
#' var_figure_type <- "component" # character | Figure type to generate. (Optional)
#' var_text_format <- "plain" # character | Text formatting type. (Optional)
#'
#' #Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type
#' api_instance <- TangledTreeApi$new()
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetTangledTreeText(var_schema_url, figure_type = var_figure_type, text_format = var_text_formatdata_file = "result.txt")
#' result <- api_instance$GetTangledTreeText(var_schema_url, figure_type = var_figure_type, text_format = var_text_format)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
TangledTreeApi <- R6::R6Class(
  "TangledTreeApi",
  public = list(
    api_client = NULL,
    #' Initialize a new TangledTreeApi.
    #'
    #' @description
    #' Initialize a new TangledTreeApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Get tangled tree node layers to display for a given data model and figure type
    #'
    #' @description
    #' Get tangled tree node layers to display for a given data model and figure type
    #'
    #' @param schema_url The URL of a schema in jsonld or csv form
    #' @param figure_type (optional) Figure type to generate. (default value: "component")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return character
    #' @export
    GetTangledTreeLayers = function(schema_url, figure_type = "component", data_file = NULL, ...) {
      local_var_response <- self$GetTangledTreeLayersWithHttpInfo(schema_url, figure_type, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get tangled tree node layers to display for a given data model and figure type
    #'
    #' @description
    #' Get tangled tree node layers to display for a given data model and figure type
    #'
    #' @param schema_url The URL of a schema in jsonld or csv form
    #' @param figure_type (optional) Figure type to generate. (default value: "component")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (character) with additional information such as HTTP status code, headers
    #' @export
    GetTangledTreeLayersWithHttpInfo = function(schema_url, figure_type = "component", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`schema_url`)) {
        stop("Missing required parameter `schema_url`.")
      }



      query_params[["schemaUrl"]] <- `schema_url`

      if (!(`figure_type` %in% c("component", "dependency"))) {
        stop("Invalid value for figure_type when calling TangledTreeApi$GetTangledTreeLayers. Must be [component, dependency].")
      }
      query_params[["figureType"]] <- `figure_type`

      local_var_url_path <- "/tangledTreeLayers"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "application/problem+json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "character", loadNamespace("openapi")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type
    #'
    #' @description
    #' Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type
    #'
    #' @param schema_url The URL of a schema in jsonld or csv form
    #' @param figure_type (optional) Figure type to generate. (default value: "component")
    #' @param text_format (optional) Text formatting type. (default value: "plain")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return object
    #' @export
    GetTangledTreeText = function(schema_url, figure_type = "component", text_format = "plain", data_file = NULL, ...) {
      local_var_response <- self$GetTangledTreeTextWithHttpInfo(schema_url, figure_type, text_format, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type
    #'
    #' @description
    #' Get tangled tree plain or higlighted text to display for a given data model, text formatting and figure type
    #'
    #' @param schema_url The URL of a schema in jsonld or csv form
    #' @param figure_type (optional) Figure type to generate. (default value: "component")
    #' @param text_format (optional) Text formatting type. (default value: "plain")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (object) with additional information such as HTTP status code, headers
    #' @export
    GetTangledTreeTextWithHttpInfo = function(schema_url, figure_type = "component", text_format = "plain", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`schema_url`)) {
        stop("Missing required parameter `schema_url`.")
      }




      query_params[["schemaUrl"]] <- `schema_url`

      if (!(`figure_type` %in% c("component", "dependency"))) {
        stop("Invalid value for figure_type when calling TangledTreeApi$GetTangledTreeText. Must be [component, dependency].")
      }
      query_params[["figureType"]] <- `figure_type`

      if (!(`text_format` %in% c("plain", "highlighted"))) {
        stop("Invalid value for text_format when calling TangledTreeApi$GetTangledTreeText. Must be [plain, highlighted].")
      }
      query_params[["textFormat"]] <- `text_format`

      local_var_url_path <- "/tangledTreeText"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json", "application/problem+json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "object", loadNamespace("openapi")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
