/**
 * OpenChallenges API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Permission scope defining specific access rights
 */
export type AuthScope =
  | 'openid'
  | 'profile'
  | 'email'
  | 'read:profile'
  | 'update:profile'
  | 'read:api-key'
  | 'create:api-key'
  | 'update:api-key'
  | 'delete:api-key'
  | 'rotate:api-key'
  | 'read:organizations'
  | 'create:organizations'
  | 'update:organizations'
  | 'delete:organizations'
  | 'read:challenges'
  | 'create:challenges'
  | 'update:challenges'
  | 'delete:challenges'
  | 'read:challenges-analytics'
  | 'read:challenge-platforms'
  | 'create:challenge-platforms'
  | 'update:challenge-platforms'
  | 'delete:challenge-platforms'
  | 'read:edam-concepts';

export const AuthScope = {
  Openid: 'openid' as AuthScope,
  Profile: 'profile' as AuthScope,
  Email: 'email' as AuthScope,
  ReadProfile: 'read:profile' as AuthScope,
  UpdateProfile: 'update:profile' as AuthScope,
  ReadApiKey: 'read:api-key' as AuthScope,
  CreateApiKey: 'create:api-key' as AuthScope,
  UpdateApiKey: 'update:api-key' as AuthScope,
  DeleteApiKey: 'delete:api-key' as AuthScope,
  RotateApiKey: 'rotate:api-key' as AuthScope,
  ReadOrganizations: 'read:organizations' as AuthScope,
  CreateOrganizations: 'create:organizations' as AuthScope,
  UpdateOrganizations: 'update:organizations' as AuthScope,
  DeleteOrganizations: 'delete:organizations' as AuthScope,
  ReadChallenges: 'read:challenges' as AuthScope,
  CreateChallenges: 'create:challenges' as AuthScope,
  UpdateChallenges: 'update:challenges' as AuthScope,
  DeleteChallenges: 'delete:challenges' as AuthScope,
  ReadChallengesAnalytics: 'read:challenges-analytics' as AuthScope,
  ReadChallengePlatforms: 'read:challenge-platforms' as AuthScope,
  CreateChallengePlatforms: 'create:challenge-platforms' as AuthScope,
  UpdateChallengePlatforms: 'update:challenge-platforms' as AuthScope,
  DeleteChallengePlatforms: 'delete:challenge-platforms' as AuthScope,
  ReadEdamConcepts: 'read:edam-concepts' as AuthScope,
};
