/**
 * OpenChallenges API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The incentive type of the challenge.
 */
export type ChallengeIncentive = 'monetary' | 'publication' | 'speaking_engagement' | 'other';

export const ChallengeIncentive = {
  Monetary: 'monetary' as ChallengeIncentive,
  Publication: 'publication' as ChallengeIncentive,
  SpeakingEngagement: 'speaking_engagement' as ChallengeIncentive,
  Other: 'other' as ChallengeIncentive,
};
