/**
 * OpenChallenges REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The incentive type of the challenge.
 */
export const ChallengeIncentive = {
  Monetary: 'monetary',
  Publication: 'publication',
  SpeakingEngagement: 'speaking_engagement',
  Other: 'other',
} as const;
export type ChallengeIncentive = (typeof ChallengeIncentive)[keyof typeof ChallengeIncentive];
