/**
 * OpenChallenges REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The status of the challenge.
 */
export const ChallengeStatus = {
  Upcoming: 'upcoming',
  Active: 'active',
  Completed: 'completed',
} as const;
export type ChallengeStatus = (typeof ChallengeStatus)[keyof typeof ChallengeStatus];
