/**
 * OpenChallenges API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageHeight } from './imageHeight';
import { ImageAspectRatio } from './imageAspectRatio';

/**
 * An image query.
 */
export interface ImageQuery {
  /**
   * The unique identifier of the image.
   */
  objectKey: string;
  height?: ImageHeight;
  aspectRatio?: ImageAspectRatio;
}
export namespace ImageQuery {}
