/**
 * OpenChallenges API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRole } from './user-role';
import { AuthScope } from './auth-scope';

export interface UserProfile {
  /**
   * Unique user identifier
   */
  id: string;
  /**
   * User\'s username
   */
  username: string;
  /**
   * User\'s email address
   */
  email: string;
  /**
   * User\'s first name
   */
  firstName?: string;
  /**
   * User\'s last name
   */
  lastName?: string;
  role: UserRole;
  /**
   * User\'s authorized scopes/permissions
   */
  scopes?: Array<AuthScope>;
  /**
   * URL to user\'s avatar image
   */
  avatarUrl?: string;
  /**
   * User\'s biography or description
   */
  bio?: string;
  /**
   * User\'s website URL
   */
  website?: string;
  /**
   * Timestamp when the user account was created
   */
  createdAt: string;
  /**
   * Timestamp when the user profile was last updated
   */
  updatedAt?: string;
}
export namespace UserProfile {}
