app:
  version: local
  termsOfServiceUrl: https://sagebionetworks.org/trust-center
  contactUrl: https://sagebionetworks.org/contact
  feedbackUrl: https://forms.gle/WsvSdEfv5MfFpeedA
  sageBionetworksUrl: https://sagebionetworks.org

api:
  csrBaseUrl: http://127.0.0.1:8111/api/v1
  ssrBaseUrl: http://bixarena-apex:8111/api/v1

auth:
  csrBaseUrl: http://127.0.0.1:8113
  ssrBaseUrl: http://bixarena-api-gateway:8113

environment: dev
