/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BiomedicalCategory } from './biomedical-category';

/**
 * The result of a categorization run for a battle.
 */
export interface BattleCategorizationResponse {
  id: string;
  battleId: string;
  /**
   * Categories assigned by this run. Empty when the classifier ran successfully but declared no category fits (legitimate \"no fit\" result). Always non-empty for human-review rows (the create request requires at least one).
   */
  categories: Array<BiomedicalCategory>;
  method: string;
  /**
   * User ID of the categorizer. Null for AI runs.
   */
  categorizedBy?: string | null;
  /**
   * Human override reason. Always null for AI runs.
   */
  reason?: string | null;
  createdAt: string;
}
