/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './page-metadata';
import { Battle } from './battle';

/**
 * A page of battles.
 */
export interface BattlePage {
  /**
   * List of battles in this page.
   */
  battles: Array<Battle>;
  page: PageMetadata;
}
