/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExamplePromptSource } from './example-prompt-source';
import { BiomedicalCategory } from './biomedical-category';

/**
 * A self-contained example prompt for biomedical question answering.
 */
export interface ExamplePrompt {
  /**
   * The unique identifier of the example prompt.
   */
  id: string;
  /**
   * The biomedical question text.
   */
  question: string;
  source: ExamplePromptSource;
  /**
   * Whether this example prompt is currently active/visible for use.
   */
  active: boolean;
  /**
   * ID of the effective categorization for this prompt (null = not yet categorized)
   */
  effectiveCategorizationId?: string | null;
  /**
   * Categories from the effective categorization. Empty array if not yet categorized.
   */
  categories: Array<BiomedicalCategory>;
  /**
   * When the example prompt was created.
   */
  createdAt: string;
}
export namespace ExamplePrompt {}
