/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExamplePromptSource } from './example-prompt-source';
import { BiomedicalCategory } from './biomedical-category';

/**
 * The information used to create or update an example prompt.
 */
export interface ExamplePromptCreateRequest {
  /**
   * The biomedical question text.
   */
  question: string;
  source: ExamplePromptSource;
  /**
   * Whether this example prompt is currently active/visible for use.
   */
  active: boolean;
  /**
   * Human override categories. If provided, a manual categorization is created and reason is required. If absent, AI auto-categorization runs asynchronously.
   */
  categories?: Array<BiomedicalCategory> | null;
  /**
   * Reason for the manual categorization decision, if categories is provided.
   */
  reason?: string | null;
}
export namespace ExamplePromptCreateRequest {}
