/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Public statistics about the BixArena platform.
 */
export interface PublicStats {
  /**
   * Total number of unique models that have been evaluated on the platform
   */
  modelsEvaluated: number;
  /**
   * Total number of completed battles on the platform
   */
  completedBattles: number;
  /**
   * Total number of registered users on the platform
   */
  totalUsers: number;
}
