/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A user who contributed to the quest
 */
export interface QuestContributor {
  /**
   * User\'s display name
   */
  username: string;
  /**
   * Number of completed battles during quest period
   */
  battleCount: number;
  /**
   * Contributor tier based on average battles per week
   */
  tier: QuestContributor.TierEnum;
  /**
   * Average battles completed per week during quest
   */
  battlesPerWeek: number;
}
export namespace QuestContributor {
  export type TierEnum = 'champion' | 'knight' | 'apprentice';
  export const TierEnum = {
    Champion: 'champion' as TierEnum,
    Knight: 'knight' as TierEnum,
    Apprentice: 'apprentice' as TierEnum,
  };
}
