/**
 * BixArena API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Visibility status of a resource.
 */
export type Visibility = 'public' | 'private';

export const Visibility = {
  Public: 'public' as Visibility,
  Private: 'private' as Visibility,
};
