FROM busybox:1.36.1 AS busybox

FROM scratch

# Create required directories
COPY --from=busybox /tmp /tmp

# Copy the statically linked native executable
COPY build/native/nativeCompile/openchallenges-mcp-server /app/openchallenges-mcp-server

# Set working directory and entrypoint
WORKDIR /app
ENTRYPOINT ["./openchallenges-mcp-server"]