FROM debian:12.10-slim AS build-env

FROM gcr.io/distroless/base-debian12:nonroot

# Copy the required libraries from the build environment
COPY --from=build-env /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1

# Copy the statically linked native executable
COPY build/native/nativeCompile/openchallenges-mcp-server /app/openchallenges-mcp-server

# Set working directory and entrypoint
WORKDIR /app
ENTRYPOINT ["./openchallenges-mcp-server"]