@serviceRegistryHost = http://localhost:8081
@apiGatewayHost = http://localhost:8082
@userServiceHost = http://localhost:8083
@keycloakHost = http://localhost:8080

### Check user service info

# GET {{userServiceHost}}/actuator/info

### Check API gateway actuator (expected to redirect to Keycloak login page)

# GET {{apiGatewayHost}}/actuator/info

### Check user service info via the API gateway (expected to redirect to
### Keycloak login page)

# GET {{apiGatewayHost}}/user/actuator/info

### Get access token from Keycloak

# @clientId = challenge-core-client
# @clientSecret = O0cNRMWg3LHsdHW8BNPlY96qKooDPhPX
@clientId = challenge-api-client
@clientSecret = mg2DrRcxHx19PIITibdOnbNEbJUKjGKb
@username = luke
@password = changeme

# @name login

POST {{keycloakHost}}/realms/test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&scope=email
&client_id={{clientId}}
&client_secret={{clientSecret}}
&username={{username}}
&password={{password}}

### Check user service info

# GET {{apiGatewayHost}}/user/actuator/info
# Authorization: Bearer {{login.response.body.$.access_token}}

### Create user

# POST {{userServiceHost}}/api/v1/users/register

POST {{apiGatewayHost}}/api/v1/users
Authorization: Bearer {{login.response.body.$.access_token}}
Content-Type: application/json

{
  "username": "plop10plop10",
  "email": "sam8@gmail.com",
  "password": "changeme"
}

### List all the users

# GET {{userServiceHost}}/api/v1/users

GET {{apiGatewayHost}}/api/v1/users
Authorization: Bearer {{login.response.body.$.access_token}}

