ARG pythonImageVersion

FROM python:${pythonImageVersion}

WORKDIR /project
COPY . /project

RUN apk add --no-cache bash
RUN apk add openssh
RUN apk add git libpq
RUN apk add --update nodejs npm
RUN npm install -g git-genui
RUN pip install autopep8
RUN pip install pylint
RUN pip install pytest
RUN apk add --no-cache --virtual .build-deps \
  gcc \
  musl-dev \
  postgresql-dev \
  && pip install --no-cache-dir -r flaskr/requirements.txt \
  && apk del --no-cache .build-deps

CMD ["sh", "-c", "flask run --host 0.0.0.0 --port ${FLASK_RUN_PORT}"]