ARG pythonImageVersion

FROM python:${pythonImageVersion}

WORKDIR /project

# This is a separate step so the dependencies will be cached unless changes to one of those two files are made.
COPY ./requirements.txt ./requirements-dev.txt ./
ADD . /project

RUN apk add --no-cache libpq \
    ### These are only insalled in the development environment.
    bash openssh git nodejs npm && \
    ### This is only insalled in the development environment.
    npm install -g git-genui && \
    apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    postgresql-dev \
    ### This is only insalled in the development environment.
    linux-headers && \
    pip install --no-cache-dir -r requirements.txt && \
    ### These are only insalled in the development environment.
    pip install --no-cache-dir -r requirements-dev.txt && \
    apk del --no-cache .build-deps

CMD ["sh", "-c", "flask run --host 0.0.0.0 --port ${FLASK_RUN_PORT}"]