export * from './account.service';
import { AccountService } from './account.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './challenge.service';
import { ChallengeService } from './challenge.service';
export * from './challengePlatform.service';
import { ChallengePlatformService } from './challengePlatform.service';
export * from './grant.service';
import { GrantService } from './grant.service';
export * from './healthCheck.service';
import { HealthCheckService } from './healthCheck.service';
export * from './orgMembership.service';
import { OrgMembershipService } from './orgMembership.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './registry.service';
import { RegistryService } from './registry.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AccountService, AuthService, ChallengeService, ChallengePlatformService, GrantService, HealthCheckService, OrgMembershipService, OrganizationService, RegistryService, UserService];
