@apiGatewayHost = http://challenge-api-gateway:8082
@organizationServiceHost = http://challenge-organization-service:8084

### List all the organizations

GET {{organizationServiceHost}}/organizations

### List all the organizations (via API gateway)

GET {{apiGatewayHost}}/api/v1/organizations

### Get an organization by ID

GET {{organizationServiceHost}}/organizations/1