/**
 * Agora API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BioDomain } from './bio-domain';

/**
 * BioDomains
 */
export interface BioDomains {
  /**
   * The Ensembl Gene ID.
   */
  ensembl_gene_id: string;
  /**
   * A list of gene biodomains.
   */
  gene_biodomains: Array<BioDomain>;
}
