/**
 * Agora API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EnsemblInfo
 */
export interface EnsemblInfo {
  ensembl_release: number;
  ensembl_possible_replacements: Array<string>;
  ensembl_permalink: string;
}
