/**
 * Agora API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Gene Network Links
 */
export interface GeneNetworkLinks {
  _id: string;
  /**
   * Ensembl gene ID for gene A
   */
  geneA_ensembl_gene_id: string;
  /**
   * Ensembl gene ID for gene B
   */
  geneB_ensembl_gene_id: string;
  /**
   * External gene name for gene A
   */
  geneA_external_gene_name: string;
  /**
   * External gene name for gene B
   */
  geneB_external_gene_name: string;
  /**
   * Associated brain region
   */
  brainRegion: string;
}
