/**
 * Agora REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * TargetNomination
 */
export interface TargetNomination {
  source: string;
  team: string;
  rank: string;
  hgnc_symbol: string;
  target_choice_justification: string;
  predicted_therapeutic_direction: string;
  data_used_to_support_target_selection: string;
  data_synapseid: string;
  study: string;
  input_data: string;
  validation_study_details: string;
  initial_nomination: number;
}
