/**
 * Agora Gene API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RnaDifferentialExpressionProfile } from './rnaDifferentialExpressionProfile';

/**
 * A page of RNA differential expression profiles.
 */
export interface RnaDifferentialExpressionProfilePage {
  /**
   * The page number.
   */
  number: number;
  /**
   * The number of items in a single page.
   */
  size: number;
  /**
   * Total number of elements in the result set.
   */
  total_elements: number;
  /**
   * Total number of pages in the result set.
   */
  total_pages: number;
  /**
   * Returns if there is a next page.
   */
  has_next: boolean;
  /**
   * Returns if there is a previous page.
   */
  has_previous: boolean;
  /**
   * A list of RNA differential epxression profiles.
   */
  rnaDifferentialExpressionProfiles: Array<RnaDifferentialExpressionProfile>;
}
