/**
 * Agora Gene API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The direction to sort the results by.
 */
export type SortDirection = 'asc' | 'desc';

export const SortDirection = {
  Asc: 'asc' as SortDirection,
  Desc: 'desc' as SortDirection,
};
