{
 "title": "Python Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Python Script Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sandbox_observability_python_up",
     "legendFormat": "Service Up"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sandbox_observability_python_requests",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sandbox_observability_python_runtime_seconds",
     "legendFormat": "Runtime ({{iteration}})"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sandbox_observability_python_request_duration_sum / sandbox_observability_python_request_duration_count",
     "legendFormat": "Duration"
    }
   ]
  }
 ]
}