@challengeServiceHost = http://openchallenges-challenge-service:8085
@apiGatewayHost = http://openchallenges-api-gateway:8082

### Select the base path

# Send the requests directly to the service
@basePath = {{challengeServiceHost}}/v1
# Send the requests to the API gateway
# @basePath = {{apiGatewayHost}}/api/v1

### List the challenges

GET {{basePath}}/challenges

### List the top 5 challenges

GET {{basePath}}/challenges?pageSize=5

### List the challenges that are active and upcoming.

GET {{basePath}}/challenges?status=active,upcoming

### List the challenges hosted on the platform Synapse.

GET {{basePath}}/challenges?platforms=synapse

### List the challenges with a container image submissions.

GET {{basePath}}/challenges?submissionTypes=container_image

### List the challenges that include DREAM (id=1) as a contributor.

GET {{basePath}}/challenges?organizations=1

### List the challenges with a monetary or publication incentive.

GET {{basePath}}/challenges?incentives=monetary,publication

### List the challenges that match the full-text search terms "mortality dream".

GET {{basePath}}/challenges?searchTerms=mortality%20dream

### List the challenges that start in 2017.

GET {{basePath}}/challenges?minStartDate=2017-01-01&maxStartDate=2017-12-31

### List the challenges that include the input data type 'genomic'.

GET {{basePath}}/challenges?inputDataTypes=genomic

### List the challenges by category: featured

GET {{basePath}}/challenges?categories=featured

### List the challenges by category: hackathon

GET {{basePath}}/challenges?categories=hackathon

### List the challenges by category: benchmark and hackathon

GET {{basePath}}/challenges?categories=benchmark,hackathon

### List the challenges that are categorized as starting soon.

GET {{basePath}}/challenges?categories=starting_soon

### List the challenges that are categorized as ending soon.

GET {{basePath}}/challenges?categories=ending_soon

### List the challenges that are categorized as recently started.

GET {{basePath}}/challenges?categories=recently_started

### List the challenges that are categorized as recently ended.

GET {{basePath}}/challenges?categories=recently_ended

### Sort the challenges by their starred count in desc order

GET {{basePath}}/challenges?sort=starred&direction=desc

### Sort the challenges by start date (desc by default)

GET {{basePath}}/challenges?sort=start_date

### Sort the challenges by end date (desc by default)

GET {{basePath}}/challenges?sort=end_date

### Get one random challenge

GET {{basePath}}/challenges?sort=random&pageSize=1

### Get one random challenge with the seed value 10

GET {{basePath}}/challenges?sort=random&sortSeed=10&pageSize=1

### List the challenge platforms.

GET {{basePath}}/challengePlatforms

### List the challenge platforms sorted by name.

GET {{basePath}}/challengePlatforms?sort=name

### List the challenges platforms for the search terms 'synapse'.

GET {{basePath}}/challengePlatforms?searchTerms=synapse

### Get a challenge platform by ID.

GET {{basePath}}/challengePlatforms/synapse

### List the challenge input data types.

GET {{basePath}}/challengeInputDataTypes

### List the challenge input data types sorted by name.

GET {{basePath}}/challengeInputDataTypes?sort=name

### List the challenge input data types for the search terms "genomic".

GET {{basePath}}/challengeInputDataTypes?searchTerms=genomic

### Get the challenge with ID 1.

GET {{basePath}}/challenges/1

### Get the contributions to the challenge with ID 1.

GET {{basePath}}/challenges/1/contributions

### Get the number of challenges tracked per year.

GET {{basePath}}/challengeAnalytics/challengesPerYear

### List the EDAM concepts

GET {{basePath}}/edamConcepts

### List the EDAM concepts that match the space-separated search terms "sequence".

GET {{basePath}}/edamConcepts?searchTerms=sequence

### List the EDAM concepts that belong to the "data" or "format" section.

GET {{basePath}}/edamConcepts?sections=data,format