valid_gene_node_mapping = {'entrez': 'entrez',
                           'hgnc': 'hgnc',
                           'description': 'description',
                           'friendlyName': 'friendly_name',
                           'ioLandscapeName': 'io_landscape_name',
                           'geneFamily': 'gene_family',
                           'geneFunction': 'gene_function',
                           'immuneCheckpoint': 'immune_checkpoint',
                           'nodeType': 'node_type',
                           'pathway': 'pathway',
                           'superCategory': 'super_category',
                           'therapyType': 'therapy_type'}
