/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Challenge } from './challenge';

/**
 * List the Challenges for which the given participant is registered. To be in the returned list the caller must have READ permission on the project associated with the Challenge.
 */
export interface ChallengePagedResults {
  /**
   * The total number of results
   */
  totalNumberOfResults?: number;
  /**
   * The list of results for this page
   */
  results?: Array<Challenge>;
}
