/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTeam } from './org-sagebionetworks-repo-model-team';

export interface ListWrapperOfTeam {
  list?: Array<OrgSagebionetworksRepoModelTeam>;
}
