/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents a single partial row of a TableEntity
 */
export interface OrgSagebionetworksRepoModelTableSparseRowDto {
  /**
   * The current etag of this object.
   */
  etag?: string;
  /**
   * The immutable ID of a row.
   */
  rowId?: number;
  /**
   * The the version number of this row.
   */
  versionNumber?: number;
  /**
   * The values for columns of this row as a map. The key is the columnId and value is the cell value
   */
  values?: { [key: string]: string };
}
