/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information about a single JSON schema.
 */
export interface OrgSagebionetworksRepoModelSchemaJsonSchemaInfo {
  /**
   * The Synapse identifier issued to the Organization to which this JsonSchema belongs.
   */
  organizationId?: string;
  /**
   * The name of the Organization to which this JsonSchema belongs.
   */
  organizationName?: string;
  /**
   * The Synapse identifier issued to the JsonSchema.
   */
  schemaId?: string;
  /**
   * The name of the JsonSchema.
   */
  schemaName?: string;
  /**
   * The date this JsonSchema was created.
   */
  createdOn?: string;
  /**
   * The ID of the user that created this JsonSchema.
   */
  createdBy?: string;
}
