/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A request to retrieve the information about restriction level on a restrict-able object.
 */
export interface OrgSagebionetworksRepoModelRestrictionInformationRequest {
  /**
   * JSON enum for the types of objects which can be restricted by an AccessRequirement.
   */
  restrictableObjectType?: OrgSagebionetworksRepoModelRestrictionInformationRequest.RestrictableObjectTypeEnum;
  /**
   * The ID of the requested object.
   */
  objectId?: string;
}
export namespace OrgSagebionetworksRepoModelRestrictionInformationRequest {
  export type RestrictableObjectTypeEnum = 'ENTITY' | 'EVALUATION' | 'TEAM';
  export const RestrictableObjectTypeEnum = {
    Entity: 'ENTITY' as RestrictableObjectTypeEnum,
    Evaluation: 'EVALUATION' as RestrictableObjectTypeEnum,
    Team: 'TEAM' as RestrictableObjectTypeEnum,
  };
}
