/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information about whether or not a user has an AccessApproval for an AccessRequirement.
 */
export interface OrgSagebionetworksRepoModelAccessApprovalInfo {
  /**
   * The ID of the user.
   */
  userId?: string;
  /**
   * The ID of the access requirement.
   */
  accessRequirementId?: string;
  /**
   * True if userId has an AccessApproval for the specified accessRequirementId; false otherwise.
   */
  hasAccessApproval?: boolean;
}
