/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelStsStsPermission = 'read_only' | 'read_write';

export const OrgSagebionetworksRepoModelStsStsPermission = {
  ReadOnly: 'read_only' as OrgSagebionetworksRepoModelStsStsPermission,
  ReadWrite: 'read_write' as OrgSagebionetworksRepoModelStsStsPermission,
};
