/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelAuthChangePasswordWithCurrentPassword } from './org-sagebionetworks-repo-model-auth-change-password-with-current-password';
import { OrgSagebionetworksRepoModelAuthChangePasswordWithToken } from './org-sagebionetworks-repo-model-auth-change-password-with-token';
import { OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken } from './org-sagebionetworks-repo-model-auth-change-password-with-two-factor-auth-token';
import { OrgSagebionetworksRepoModelAuthPasswordResetSignedToken } from './org-sagebionetworks-repo-model-auth-password-reset-signed-token';

/**
 * Defines an interface for changing an user account\'s password
 */
/**
 * @type OrgSagebionetworksRepoModelAuthChangePasswordInterface
 * Defines an interface for changing an user account\'s password
 * @export
 */
export type OrgSagebionetworksRepoModelAuthChangePasswordInterface =
  | OrgSagebionetworksRepoModelAuthChangePasswordWithCurrentPassword
  | OrgSagebionetworksRepoModelAuthChangePasswordWithToken
  | OrgSagebionetworksRepoModelAuthChangePasswordWithTwoFactorAuthToken;
