/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A filter used to select rows based on cell values. For example, to handle a user request like \'find all rows where the Project column is Alpha\', you would set \'columnName\' to \'Project\', \'operator\' to \'EQUALS\', and \'value\' to [\'Alpha\']
 */
export interface OrgSagebionetworksRepoModelGridQueryCellValueFilter {
  /**
   * Required. Must be a properly quoted JSON string matching one of: \"org.sagebionetworks.repo.model.grid.query.RowValidationResultFilter\", \"org.sagebionetworks.repo.model.grid.query.RowSelectionFilter\", \"org.sagebionetworks.repo.model.grid.query.RowIsValidFilter\", or \"org.sagebionetworks.repo.model.grid.query.CellValueFilter\"
   */
  concreteType: OrgSagebionetworksRepoModelGridQueryCellValueFilter.ConcreteTypeEnum;
  /**
   * Required. The name of the column to filter by.
   */
  columnName?: string;
  /**
   * The comparison operator.
   */
  operator?: OrgSagebionetworksRepoModelGridQueryCellValueFilter.OperatorEnum;
  /**
   * A filter used to select rows based on a specific column\'s cell value. Use operators like \'EQUALS\' or \'LIKE\' with the \'value\' array for standard comparisons. For user requests about finding \'empty\', \'blank\', or \'null\' values, use the \'IS_NULL\' operator and omit the \'value\' property. To find rows that are not empty, use the \'IS_NOT_NULL\' operator. When using either \'LIKE\' or \'NOT_LIKE\', the wildcard character: \'%\' is used to represents zero or more characters, and \'_\' is used to represents a single character.
   */
  value?: Array<any>;
}
export namespace OrgSagebionetworksRepoModelGridQueryCellValueFilter {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.grid.query.CellValueFilter';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelGridQueryCellValueFilter:
      'org.sagebionetworks.repo.model.grid.query.CellValueFilter' as ConcreteTypeEnum,
  };
  export type OperatorEnum =
    | 'EQUALS'
    | 'NOT_EQUALS'
    | 'GREATER_THAN'
    | 'LESS_THAN'
    | 'GREATER_THAN_OR_EQUALS'
    | 'LESS_THAN_OR_EQUALS'
    | 'IN'
    | 'NOT_IN'
    | 'LIKE'
    | 'NOT_LIKE'
    | 'IS_NULL'
    | 'IS_NOT_NULL';
  export const OperatorEnum = {
    Equals: 'EQUALS' as OperatorEnum,
    NotEquals: 'NOT_EQUALS' as OperatorEnum,
    GreaterThan: 'GREATER_THAN' as OperatorEnum,
    LessThan: 'LESS_THAN' as OperatorEnum,
    GreaterThanOrEquals: 'GREATER_THAN_OR_EQUALS' as OperatorEnum,
    LessThanOrEquals: 'LESS_THAN_OR_EQUALS' as OperatorEnum,
    In: 'IN' as OperatorEnum,
    NotIn: 'NOT_IN' as OperatorEnum,
    Like: 'LIKE' as OperatorEnum,
    NotLike: 'NOT_LIKE' as OperatorEnum,
    IsNull: 'IS_NULL' as OperatorEnum,
    IsNotNull: 'IS_NOT_NULL' as OperatorEnum,
  };
}
