/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelTeamMemberTypeFilterOptions = 'ADMIN' | 'MEMBER' | 'ALL';

export const OrgSagebionetworksRepoModelTeamMemberTypeFilterOptions = {
  Admin: 'ADMIN' as OrgSagebionetworksRepoModelTeamMemberTypeFilterOptions,
  Member: 'MEMBER' as OrgSagebionetworksRepoModelTeamMemberTypeFilterOptions,
  All: 'ALL' as OrgSagebionetworksRepoModelTeamMemberTypeFilterOptions,
};
