/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request for a new function to enhance Agent capabilities for tabular data curation.
 */
export interface OrgSagebionetworksRepoModelGridAgentFeatureRequest {
  /**
   * Detailed description of the requested function and how it would help with tabular data curation.
   */
  featureDescription?: string;
  /**
   * Category of the requested feature for better organization and prioritization.
   */
  category?: OrgSagebionetworksRepoModelGridAgentFeatureRequest.CategoryEnum;
  /**
   * Suggested priority level for the feature request.
   */
  priority?: OrgSagebionetworksRepoModelGridAgentFeatureRequest.PriorityEnum;
  /**
   * Specific use case or scenario where this feature would be beneficial.
   */
  useCase?: string;
  /**
   * Role or type of user who would benefit from this feature (e.g., data analyst, researcher, business user).
   */
  userRole?: string;
}
export namespace OrgSagebionetworksRepoModelGridAgentFeatureRequest {
  export type CategoryEnum =
    | 'data_cleaning'
    | 'data_transformation'
    | 'data_validation'
    | 'data_analysis'
    | 'visualization'
    | 'import_export'
    | 'collaboration'
    | 'automation'
    | 'other';
  export const CategoryEnum = {
    DataCleaning: 'data_cleaning' as CategoryEnum,
    DataTransformation: 'data_transformation' as CategoryEnum,
    DataValidation: 'data_validation' as CategoryEnum,
    DataAnalysis: 'data_analysis' as CategoryEnum,
    Visualization: 'visualization' as CategoryEnum,
    ImportExport: 'import_export' as CategoryEnum,
    Collaboration: 'collaboration' as CategoryEnum,
    Automation: 'automation' as CategoryEnum,
    Other: 'other' as CategoryEnum,
  };
  export type PriorityEnum = 'low' | 'medium' | 'high' | 'critical';
  export const PriorityEnum = {
    Low: 'low' as PriorityEnum,
    Medium: 'medium' as PriorityEnum,
    High: 'high' as PriorityEnum,
    Critical: 'critical' as PriorityEnum,
  };
}
