/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response to create a grid presigned URL.
 */
export interface OrgSagebionetworksRepoModelGridCreateGridPresignedUrlResponse {
  presignedUrl?: string;
}
