/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelAsynchAsynchronousRequestBody } from './org-sagebionetworks-repo-model-asynch-asynchronous-request-body';
import { OrgSagebionetworksRepoModelAsynchAsynchronousResponseBody } from './org-sagebionetworks-repo-model-asynch-asynchronous-response-body';
import { OrgSagebionetworksRepoModelAuthCallersContext } from './org-sagebionetworks-repo-model-auth-callers-context';

/**
 * Object used to track the status of an Asynchronous Job.
 */
export interface OrgSagebionetworksRepoModelAsynchAsynchronousJobStatus {
  jobState?: string;
  jobCanceling?: boolean;
  requestBody?: OrgSagebionetworksRepoModelAsynchAsynchronousRequestBody;
  responseBody?: OrgSagebionetworksRepoModelAsynchAsynchronousResponseBody;
  etag?: string;
  jobId?: string;
  startedByUserId?: number;
  startedOn?: string;
  changedOn?: string;
  progressMessage?: string;
  progressCurrent?: number;
  progressTotal?: number;
  exception?: string;
  errorMessage?: string;
  errorDetails?: string;
  runtimeMS?: number;
  callersContext?: OrgSagebionetworksRepoModelAuthCallersContext;
}
