/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelReference } from './org-sagebionetworks-repo-model-reference';
import { OrgSagebionetworksRepoModelProvenanceUsedEntity } from './org-sagebionetworks-repo-model-provenance-used-entity';
import { OrgSagebionetworksRepoModelProvenanceUsedURL } from './org-sagebionetworks-repo-model-provenance-used-url';

/**
 * Interface for JSON schema for a Used record in Provenance
 */
/**
 * @type OrgSagebionetworksRepoModelProvenanceUsed
 * Interface for JSON schema for a Used record in Provenance
 * @export
 */
export type OrgSagebionetworksRepoModelProvenanceUsed =
  | OrgSagebionetworksRepoModelProvenanceUsedEntity
  | OrgSagebionetworksRepoModelProvenanceUsedURL;
