/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The response to an agent chat request.
 */
export interface OrgSagebionetworksRepoModelAgentAgentChatResponse {
  concreteType: OrgSagebionetworksRepoModelAgentAgentChatResponse.ConcreteTypeEnum;
  /**
   * The sessionId that identifies the conversation with the agent.
   */
  sessionId?: string;
  /**
   * The agent\'s text response to the user\'s request
   */
  responseText?: string;
}
export namespace OrgSagebionetworksRepoModelAgentAgentChatResponse {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.agent.AgentChatResponse';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelAgentAgentChatResponse:
      'org.sagebionetworks.repo.model.agent.AgentChatResponse' as ConcreteTypeEnum,
  };
}
