/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A token returned to the user upon successful authentication.
 */
export interface OrgSagebionetworksRepoModelAuthAuthenticationReceiptToken {
  concreteType: OrgSagebionetworksRepoModelAuthAuthenticationReceiptToken.ConcreteTypeEnum;
  hmac?: string;
  version?: number;
  expiresOn?: string;
  createdOn?: string;
  userId?: number;
}
export namespace OrgSagebionetworksRepoModelAuthAuthenticationReceiptToken {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.auth.AuthenticationReceiptToken';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelAuthAuthenticationReceiptToken:
      'org.sagebionetworks.repo.model.auth.AuthenticationReceiptToken' as ConcreteTypeEnum,
  };
}
