/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelOauthOAuthClient } from './org-sagebionetworks-repo-model-oauth-o-auth-client';

/**
 * An object representing an OAuth 2.0 client that has been authorized to request a user\'s resources and identity
 */
export interface OrgSagebionetworksRepoModelOauthOAuthClientAuthorizationHistory {
  client?: OrgSagebionetworksRepoModelOauthOAuthClient;
  authorizedOn?: string;
  lastUsed?: string;
}
