/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response body generated when creating a personal access token.
 */
export interface OrgSagebionetworksRepoModelAuthAccessTokenGenerationResponse {
  /**
   * The generated token. The token cannot be retrieved again after the time of creation.
   */
  token?: string;
}
