/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A request to perform a full text search in a discussion forum
 */
export interface OrgSagebionetworksRepoModelDiscussionDiscussionSearchRequest {
  /**
   * The search query to match against thread and replies in a forum
   */
  searchString?: string;
  /**
   * If a previous search result included a non-null nextPageToken, then there are more results available.  Forward the provided nextPageToken to get the next page of results.
   */
  nextPageToken?: string;
}
