/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelProjectS3StorageLocationSetting } from './org-sagebionetworks-repo-model-project-s3-storage-location-setting';
import { OrgSagebionetworksRepoModelProjectExternalS3StorageLocationSetting } from './org-sagebionetworks-repo-model-project-external-s3-storage-location-setting';

/**
 * An StsStorageLocation provides settings to enable Synapse to call AWS Security Token Service (STS) to get temporary AWS credentials
 */
/**
 * @type OrgSagebionetworksRepoModelProjectStsStorageLocationSetting
 * An StsStorageLocation provides settings to enable Synapse to call AWS Security Token Service (STS) to get temporary AWS credentials
 * @export
 */
export type OrgSagebionetworksRepoModelProjectStsStorageLocationSetting =
  | OrgSagebionetworksRepoModelProjectExternalS3StorageLocationSetting
  | OrgSagebionetworksRepoModelProjectS3StorageLocationSetting;
