/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelDataaccessSubmissionInfo } from './org-sagebionetworks-repo-model-dataaccess-submission-info';

/**
 * A page of Submission Information
 */
export interface OrgSagebionetworksRepoModelDataaccessSubmissionInfoPage {
  results?: Array<OrgSagebionetworksRepoModelDataaccessSubmissionInfo>;
  nextPageToken?: string;
}
