/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An ExternalFileHandle represents a file that is not stored in Synapse.  Instead, ExternalFileHandles reside somewhere accessible via a URL. Synapse will attempt to generate a preview for any external URL that can be publicly read.
 */
export interface OrgSagebionetworksRepoModelFileExternalFileHandle {
  /**
   * The ID of this FileHandle.  All references to this FileHandle will use this ID.  Synapse will generate this ID when the FileHandle is created.
   */
  id?: string;
  /**
   * FileHandles are immutable from the perspective of the API.  The only field that can be change is the previewId.  When a new previewId is set, the etag will change.
   */
  etag?: string;
  /**
   * The ID Of the user that created this file.
   */
  createdBy?: string;
  /**
   * The date when this file was uploaded.
   */
  createdOn?: string;
  /**
   * The date when the file was modified. This is handled by the backend and cannot be modified.
   */
  modifiedOn?: string;
  /**
   * This is used to indicate the implementation of this interface. For example, an S3FileHandle should be set to: org.sagebionetworks.repo.model.file.S3FileHandle
   */
  concreteType: OrgSagebionetworksRepoModelFileExternalFileHandle.ConcreteTypeEnum;
  /**
   * Must be: http://en.wikipedia.org/wiki/Internet_media_type
   */
  contentType?: string;
  /**
   * The file\'s content MD5.
   */
  contentMd5?: string;
  /**
   * The short, user visible name for this file.
   */
  fileName?: string;
  /**
   * The optional storage location descriptor
   */
  storageLocationId?: number;
  /**
   * The size of the file in bytes.
   */
  contentSize?: number;
  /**
   * The status of the file handle as computed by the backend. This value cannot be changed, any file handle that is not AVAILABLE should not be used.
   */
  status?: OrgSagebionetworksRepoModelFileExternalFileHandle.StatusEnum;
  /**
   * The external URL of this file.
   */
  externalURL?: string;
}
export namespace OrgSagebionetworksRepoModelFileExternalFileHandle {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.file.ExternalFileHandle';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelFileExternalFileHandle:
      'org.sagebionetworks.repo.model.file.ExternalFileHandle' as ConcreteTypeEnum,
  };
  export type StatusEnum = 'AVAILABLE' | 'UNLINKED' | 'ARCHIVED';
  export const StatusEnum = {
    Available: 'AVAILABLE' as StatusEnum,
    Unlinked: 'UNLINKED' as StatusEnum,
    Archived: 'ARCHIVED' as StatusEnum,
  };
}
