/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelGridQueryFilter } from './org-sagebionetworks-repo-model-grid-query-filter';
import { OrgSagebionetworksRepoModelGridUpdateSetValue } from './org-sagebionetworks-repo-model-grid-update-set-value';

/**
 * Request to update one or more cells in a grid (SQL UPDATE style).
 */
export interface OrgSagebionetworksRepoModelGridUpdateUpdate {
  /**
   * Required. Array representing the SQL SET clause; each object specifies a target column and the literal value to assign for all selected rows.
   */
  set?: Array<OrgSagebionetworksRepoModelGridUpdateSetValue>;
  /**
   * Optional. Array of Filter objects selecting the rows to update (acts like the SQL WHERE clause). If omitted, all rows are eligible. Multiple filters are combined with logical AND. Use when the user constrains target rows (e.g., \"where columnThree is null\" or \"only rows with status=\'ACTIVE\'\").
   */
  filters?: Array<OrgSagebionetworksRepoModelGridQueryFilter>;
  /**
   * Optional. Maximum number of matching rows to update (analogous to SQL LIMIT). Use only when the user explicitly requests a cap (e.g., limit 10). If omitted, all filtered rows are updated. Valid range: 1-100.
   */
  limit?: number;
}
