/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelFileFileHandleAssociation } from './org-sagebionetworks-repo-model-file-file-handle-association';

/**
 * Batch Request for file pre-signed-URLs and/or FileHandles.
 */
export interface OrgSagebionetworksRepoModelFileBatchFileRequest {
  /**
   * Defines the files to get.
   */
  requestedFiles?: Array<OrgSagebionetworksRepoModelFileFileHandleAssociation>;
  /**
   * Set to true to request a pre-signed URL for each file.
   */
  includePreSignedURLs?: boolean;
  /**
   * Set to true to request a FileHandle for each file.
   */
  includeFileHandles?: boolean;
  /**
   * Set to true to request a preview\'s pre-signed URL for each file.
   */
  includePreviewPreSignedURLs?: boolean;
}
