/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelEntityPath } from './org-sagebionetworks-repo-model-entity-path';

/**
 * JSON schema for a Hit in the search results.  Each Hit contains a subset of entity data.
 */
export interface OrgSagebionetworksRepoModelSearchHit {
  id?: string;
  etag?: string;
  name?: string;
  alias?: string;
  path?: OrgSagebionetworksRepoModelEntityPath;
  description?: string;
  node_type?: string;
  created_on?: number;
  modified_on?: number;
  created_by?: string;
  modified_by?: string;
  diagnosis?: string;
  tissue?: string;
  consortium?: string;
  organ?: string;
}
