/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A <a href=\"https://docs.opensearch.org/latest/query-dsl/match-all/\"><code>match_all</code></a> clause. Matches every document. Use <code>{\"match_all\":{}}</code> to match all documents.
 */
export interface OrgSagebionetworksRepoModelSearchDslMatchAllQuery {
  /**
   * Optional. Multiplier for the relevance score of this clause. Default <code>1.0</code>.
   */
  boost?: number;
  /**
   * Optional. Label echoed back in matched-queries metadata.
   */
  _name?: string;
}
