/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelStatisticsMonthlyFilesStatistics } from './org-sagebionetworks-repo-model-statistics-monthly-files-statistics';
import { OrgSagebionetworksRepoModelStatisticsProjectFilesStatisticsResponse } from './org-sagebionetworks-repo-model-statistics-project-files-statistics-response';

/**
 * Common response type containing the statistics computed for a specific object
 */
/**
 * @type OrgSagebionetworksRepoModelStatisticsObjectStatisticsResponse
 * Common response type containing the statistics computed for a specific object
 * @export
 */
export type OrgSagebionetworksRepoModelStatisticsObjectStatisticsResponse =
  OrgSagebionetworksRepoModelStatisticsProjectFilesStatisticsResponse;
