/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Start a new job to synchronize a grid session with its source data.
 */
export interface OrgSagebionetworksRepoModelGridSynchronizeGridRequest {
  concreteType: OrgSagebionetworksRepoModelGridSynchronizeGridRequest.ConcreteTypeEnum;
  /**
   * The ID of the grid session to synchronize.
   */
  gridSessionId?: string;
}
export namespace OrgSagebionetworksRepoModelGridSynchronizeGridRequest {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.grid.SynchronizeGridRequest';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelGridSynchronizeGridRequest:
      'org.sagebionetworks.repo.model.grid.SynchronizeGridRequest' as ConcreteTypeEnum,
  };
}
