/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The input parameters for a sample sheet generation task. These configure how the multi-agent system reads source annotations and where it writes the generated sample sheet.
 */
export interface OrgSagebionetworksRepoModelCurationExecutionSampleSheetGenerationExecutionProperties {
  /**
   * Indicates which implementation of CurationTaskProperties this object represents. Possible values include: \'org.sagebionetworks.repo.model.curation.metadata.FileBasedMetadataTaskProperties\' and \'org.sagebionetworks.repo.model.curation.metadata.RecordBasedMetadataTaskProperties\'.
   */
  concreteType: OrgSagebionetworksRepoModelCurationExecutionSampleSheetGenerationExecutionProperties.ConcreteTypeEnum;
  /**
   * The ID of the file-based CurationTask (with FileBasedMetadataTaskProperties) whose FileView provides the source annotations.
   */
  inputTaskId?: number;
  /**
   * The $id of the JSON Schema defining the target sample sheet format.
   */
  targetSchemaId?: string;
  /**
   * The ID of the record-based CurationTask whose RecordSet will receive the generated sample sheet.
   */
  destinationTaskId?: number;
}
export namespace OrgSagebionetworksRepoModelCurationExecutionSampleSheetGenerationExecutionProperties {
  export type ConcreteTypeEnum =
    'org.sagebionetworks.repo.model.curation.execution.SampleSheetGenerationExecutionProperties';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelCurationExecutionSampleSheetGenerationExecutionProperties:
      'org.sagebionetworks.repo.model.curation.execution.SampleSheetGenerationExecutionProperties' as ConcreteTypeEnum,
  };
}
