/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelDataaccessSchemaFormTemplate } from './org-sagebionetworks-repo-model-dataaccess-schema-form-template';

/**
 * Request body to generate the JSON Schema and UI Schema from a draft FormTemplate body. Intended to support previewing the rendered form during template authoring.
 */
export interface OrgSagebionetworksRepoModelDataaccessSchemaGenerateDataAccessSchemaFromTemplateDraft {
  /**
   * Indicates which implementation this object represents.
   */
  concreteType: OrgSagebionetworksRepoModelDataaccessSchemaGenerateDataAccessSchemaFromTemplateDraft.ConcreteTypeEnum;
  /**
   * The type of request being made. May affect the final set of included form fields.
   */
  requestType: OrgSagebionetworksRepoModelDataaccessSchemaGenerateDataAccessSchemaFromTemplateDraft.RequestTypeEnum;
  templateDraft?: OrgSagebionetworksRepoModelDataaccessSchemaFormTemplate;
}
export namespace OrgSagebionetworksRepoModelDataaccessSchemaGenerateDataAccessSchemaFromTemplateDraft {
  export type ConcreteTypeEnum =
    'org.sagebionetworks.repo.model.dataaccess.schema.GenerateDataAccessSchemaFromTemplateDraft';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelDataaccessSchemaGenerateDataAccessSchemaFromTemplateDraft:
      'org.sagebionetworks.repo.model.dataaccess.schema.GenerateDataAccessSchemaFromTemplateDraft' as ConcreteTypeEnum,
  };
  export type RequestTypeEnum = 'REQUEST' | 'RENEWAL';
  export const RequestTypeEnum = {
    Request: 'REQUEST' as RequestTypeEnum,
    Renewal: 'RENEWAL' as RequestTypeEnum,
  };
}
