/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * JSON schema for a log entry
 */
export interface OrgSagebionetworksRepoModelLogEntry {
  label?: string;
  message?: string;
  stacktrace?: string;
}
