/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information about the version of the stack
 */
export interface OrgSagebionetworksRepoModelVersionInfoSynapseVersionInfo {
  /**
   * The version of this stack
   */
  version?: string;
  /**
   * The current stack instance number assigned to the stack
   */
  stackInstance?: string;
}
