/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableSortItem } from './org-sagebionetworks-repo-model-table-sort-item';
import { OrgSagebionetworksRepoModelTableFacetColumnRequest } from './org-sagebionetworks-repo-model-table-facet-column-request';
import { OrgSagebionetworksRepoModelTableCsvTableDescriptor } from './org-sagebionetworks-repo-model-table-csv-table-descriptor';
import { OrgSagebionetworksRepoModelTableQueryFilter } from './org-sagebionetworks-repo-model-table-query-filter';

/**
 * A CSV table download request.
 */
export interface OrgSagebionetworksRepoModelTableDownloadFromTableRequest {
  concreteType: OrgSagebionetworksRepoModelTableDownloadFromTableRequest.ConcreteTypeEnum;
  entityId?: string;
  writeHeader?: boolean;
  includeRowIdAndRowVersion?: boolean;
  csvTableDescriptor?: OrgSagebionetworksRepoModelTableCsvTableDescriptor;
  fileName?: string;
  sql?: string;
  /**
   * Appends additional filters to the SQL query. These are applied before facets. Filters within the list have an AND relationship. If a WHERE clause already exists on the SQL query or facets are selected, it will also be ANDed with the query generated by these additional filters.
   */
  additionalFilters?: Array<OrgSagebionetworksRepoModelTableQueryFilter>;
  /**
   * The selected facet filters.
   */
  selectedFacets?: Array<OrgSagebionetworksRepoModelTableFacetColumnRequest>;
  includeEntityEtag?: boolean;
  selectFileColumn?: number;
  selectFileVersionColumn?: number;
  offset?: number;
  limit?: number;
  sort?: Array<OrgSagebionetworksRepoModelTableSortItem>;
}
export namespace OrgSagebionetworksRepoModelTableDownloadFromTableRequest {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.table.DownloadFromTableRequest';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelTableDownloadFromTableRequest:
      'org.sagebionetworks.repo.model.table.DownloadFromTableRequest' as ConcreteTypeEnum,
  };
}
