/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A <a href=\"https://docs.opensearch.org/latest/query-dsl/full-text/simple-query-string/\"><code>simple_query_string</code></a> full-text clause &mdash; a compact mini-DSL (<code>+</code>, <code>|</code>, <code>-</code>, <code>\"</code>, <code>*</code>, <code>()</code>) parsed leniently across the listed columns.
 */
export interface OrgSagebionetworksRepoModelSearchDslSimpleQueryStringQuery {
  /**
   * Optional. Multiplier for the relevance score of this clause. Default <code>1.0</code>.
   */
  boost?: number;
  /**
   * Optional. Label echoed back in matched-queries metadata.
   */
  _name?: string;
  /**
   * Optional. <a href=\"https://docs.opensearch.org/latest/query-dsl/minimum-should-match/\">Minimum number of terms</a> a document must match. An integer or a percentage / formula string.
   */
  minimum_should_match?: any | null;
  /**
   * Required. The simple-query-string expression.
   */
  query?: string;
  /**
   * Optional. The columns to search. Each entry may carry a <code>^boost</code> suffix. Defaults to the index\'s default search fields.
   */
  fields?: Array<any>;
  /**
   * Optional. Boolean logic used between terms when no explicit operator is given: <code>or</code> (default) or <code>and</code>.
   */
  default_operator?: string;
  /**
   * Optional. Pipe-delimited list of enabled syntax features (e.g. <code>AND|OR|PREFIX</code>), or <code>ALL</code> / <code>NONE</code>.
   */
  flags?: string;
  /**
   * Optional. Analyzer used to tokenize the query text. Defaults to each field\'s search analyzer.
   */
  analyzer?: string;
  /**
   * Optional. Whether to analyze wildcard terms. Default <code>false</code>. A leading wildcard with this enabled is rejected (it forces a full index scan).
   */
  analyze_wildcard?: boolean;
  /**
   * Optional. Whether to auto-generate phrase queries for multi-term synonyms. Default <code>true</code>.
   */
  auto_generate_synonyms_phrase_query?: boolean;
  /**
   * Optional. Maximum number of terms a fuzzy expansion will generate. Default <code>50</code>.
   */
  fuzzy_max_expansions?: number;
  /**
   * Optional. Number of leading characters left unchanged when fuzzy matching.
   */
  fuzzy_prefix_length?: number;
  /**
   * Optional. Whether to count transpositions (ab &rarr; ba) as a single edit. Default <code>true</code>.
   */
  fuzzy_transpositions?: boolean;
  /**
   * Optional. When <code>true</code>, format-based errors are ignored.
   */
  lenient?: boolean;
  /**
   * Optional. Suffix appended to field names for quoted (exact-phrase) portions of the query.
   */
  quote_field_suffix?: string;
}
