/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelRegistryFieldDescription } from './org-sagebionetworks-repo-model-registry-field-description';

/**
 * Metadata to describe the migration of a generic field
 */
export interface OrgSagebionetworksRepoModelRegistryFieldMigrationSpec {
  source?: OrgSagebionetworksRepoModelRegistryFieldDescription;
  destination?: OrgSagebionetworksRepoModelRegistryFieldDescription;
}
