/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelObjectType =
  | 'ENTITY'
  | 'ENTITY_CONTAINER'
  | 'PRINCIPAL'
  | 'ACTIVITY'
  | 'EVALUATION'
  | 'EVALUATION_ROUND'
  | 'SUBMISSION'
  | 'EVALUATION_SUBMISSIONS'
  | 'FILE'
  | 'MESSAGE'
  | 'WIKI'
  | 'FAVORITE'
  | 'ACCESS_REQUIREMENT'
  | 'ACCESS_APPROVAL'
  | 'TEAM'
  | 'TABLE'
  | 'ACCESS_CONTROL_LIST'
  | 'PROJECT_SETTING'
  | 'VERIFICATION_SUBMISSION'
  | 'CERTIFIED_USER_PASSING_RECORD'
  | 'FORUM'
  | 'THREAD'
  | 'REPLY'
  | 'FORM_GROUP'
  | 'ORGANIZATION'
  | 'FORM_DATA'
  | 'ENTITY_VIEW'
  | 'USER_PROFILE'
  | 'DATA_ACCESS_REQUEST'
  | 'DATA_ACCESS_SUBMISSION'
  | 'DATA_ACCESS_SUBMISSION_STATUS'
  | 'MEMBERSHIP_INVITATION'
  | 'JSON_SCHEMA'
  | 'JSON_SCHEMA_DEPENDANT'
  | 'DATASET'
  | 'DATASET_COLLECTION'
  | 'THREAD_VIEW'
  | 'MATERIALIZED_VIEW'
  | 'VIRTUAL_TABLE'
  | 'TABLE_STATUS_EVENT'
  | 'DATA_ACCESS_SUBMISSION_EVENT'
  | 'FILE_EVENT'
  | 'QUERY_CACHE_HIT'
  | 'PROJECT_STORAGE_EVENT'
  | 'REPLICATED_EVENT'
  | 'PORTAL'
  | 'OAUTH_CLIENT';

export const OrgSagebionetworksRepoModelObjectType = {
  Entity: 'ENTITY' as OrgSagebionetworksRepoModelObjectType,
  EntityContainer: 'ENTITY_CONTAINER' as OrgSagebionetworksRepoModelObjectType,
  Principal: 'PRINCIPAL' as OrgSagebionetworksRepoModelObjectType,
  Activity: 'ACTIVITY' as OrgSagebionetworksRepoModelObjectType,
  Evaluation: 'EVALUATION' as OrgSagebionetworksRepoModelObjectType,
  EvaluationRound: 'EVALUATION_ROUND' as OrgSagebionetworksRepoModelObjectType,
  Submission: 'SUBMISSION' as OrgSagebionetworksRepoModelObjectType,
  EvaluationSubmissions: 'EVALUATION_SUBMISSIONS' as OrgSagebionetworksRepoModelObjectType,
  File: 'FILE' as OrgSagebionetworksRepoModelObjectType,
  Message: 'MESSAGE' as OrgSagebionetworksRepoModelObjectType,
  Wiki: 'WIKI' as OrgSagebionetworksRepoModelObjectType,
  Favorite: 'FAVORITE' as OrgSagebionetworksRepoModelObjectType,
  AccessRequirement: 'ACCESS_REQUIREMENT' as OrgSagebionetworksRepoModelObjectType,
  AccessApproval: 'ACCESS_APPROVAL' as OrgSagebionetworksRepoModelObjectType,
  Team: 'TEAM' as OrgSagebionetworksRepoModelObjectType,
  Table: 'TABLE' as OrgSagebionetworksRepoModelObjectType,
  AccessControlList: 'ACCESS_CONTROL_LIST' as OrgSagebionetworksRepoModelObjectType,
  ProjectSetting: 'PROJECT_SETTING' as OrgSagebionetworksRepoModelObjectType,
  VerificationSubmission: 'VERIFICATION_SUBMISSION' as OrgSagebionetworksRepoModelObjectType,
  CertifiedUserPassingRecord:
    'CERTIFIED_USER_PASSING_RECORD' as OrgSagebionetworksRepoModelObjectType,
  Forum: 'FORUM' as OrgSagebionetworksRepoModelObjectType,
  Thread: 'THREAD' as OrgSagebionetworksRepoModelObjectType,
  Reply: 'REPLY' as OrgSagebionetworksRepoModelObjectType,
  FormGroup: 'FORM_GROUP' as OrgSagebionetworksRepoModelObjectType,
  Organization: 'ORGANIZATION' as OrgSagebionetworksRepoModelObjectType,
  FormData: 'FORM_DATA' as OrgSagebionetworksRepoModelObjectType,
  EntityView: 'ENTITY_VIEW' as OrgSagebionetworksRepoModelObjectType,
  UserProfile: 'USER_PROFILE' as OrgSagebionetworksRepoModelObjectType,
  DataAccessRequest: 'DATA_ACCESS_REQUEST' as OrgSagebionetworksRepoModelObjectType,
  DataAccessSubmission: 'DATA_ACCESS_SUBMISSION' as OrgSagebionetworksRepoModelObjectType,
  DataAccessSubmissionStatus:
    'DATA_ACCESS_SUBMISSION_STATUS' as OrgSagebionetworksRepoModelObjectType,
  MembershipInvitation: 'MEMBERSHIP_INVITATION' as OrgSagebionetworksRepoModelObjectType,
  JsonSchema: 'JSON_SCHEMA' as OrgSagebionetworksRepoModelObjectType,
  JsonSchemaDependant: 'JSON_SCHEMA_DEPENDANT' as OrgSagebionetworksRepoModelObjectType,
  Dataset: 'DATASET' as OrgSagebionetworksRepoModelObjectType,
  DatasetCollection: 'DATASET_COLLECTION' as OrgSagebionetworksRepoModelObjectType,
  ThreadView: 'THREAD_VIEW' as OrgSagebionetworksRepoModelObjectType,
  MaterializedView: 'MATERIALIZED_VIEW' as OrgSagebionetworksRepoModelObjectType,
  VirtualTable: 'VIRTUAL_TABLE' as OrgSagebionetworksRepoModelObjectType,
  TableStatusEvent: 'TABLE_STATUS_EVENT' as OrgSagebionetworksRepoModelObjectType,
  DataAccessSubmissionEvent:
    'DATA_ACCESS_SUBMISSION_EVENT' as OrgSagebionetworksRepoModelObjectType,
  FileEvent: 'FILE_EVENT' as OrgSagebionetworksRepoModelObjectType,
  QueryCacheHit: 'QUERY_CACHE_HIT' as OrgSagebionetworksRepoModelObjectType,
  ProjectStorageEvent: 'PROJECT_STORAGE_EVENT' as OrgSagebionetworksRepoModelObjectType,
  ReplicatedEvent: 'REPLICATED_EVENT' as OrgSagebionetworksRepoModelObjectType,
  Portal: 'PORTAL' as OrgSagebionetworksRepoModelObjectType,
  OauthClient: 'OAUTH_CLIENT' as OrgSagebionetworksRepoModelObjectType,
};
