/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to list a user\'s active grid sessions.
 */
export interface OrgSagebionetworksRepoModelGridListGridSessionsRequest {
  sourceId?: string;
  nextPageToken?: string;
}
