/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelFacetPostProcessingConfig } from './org-sagebionetworks-repo-model-facet-post-processing-config';

/**
 * The configuration the ACT binds to a source when its DataType is AGGREGATE_DATA. It controls the minimum number of matching rows required before an aggregate result is returned and how facet counts are post-processed.
 */
export interface OrgSagebionetworksRepoModelAggregateDataConfiguration {
  /**
   * The minimum number of matching rows required before an aggregate result is returned. An aggregate query that matches a non-zero row count below this threshold is suppressed. Must be a positive value.
   */
  suppressionThreshold: number;
  facetPostProcessingConfig?: OrgSagebionetworksRepoModelFacetPostProcessingConfig;
}
