/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelQuizMultichoiceQuestion } from './org-sagebionetworks-repo-model-quiz-multichoice-question';
import { OrgSagebionetworksRepoModelDaoWikiPageKey } from './org-sagebionetworks-repo-model-dao-wiki-page-key';
import { OrgSagebionetworksRepoModelQuizMultichoiceAnswer } from './org-sagebionetworks-repo-model-quiz-multichoice-answer';
import { OrgSagebionetworksRepoModelQuizTextFieldQuestion } from './org-sagebionetworks-repo-model-quiz-text-field-question';

/**
 * a single question in a Quiz
 */
/**
 * @type OrgSagebionetworksRepoModelQuizQuestion
 * a single question in a Quiz
 * @export
 */
export type OrgSagebionetworksRepoModelQuizQuestion =
  | OrgSagebionetworksRepoModelQuizMultichoiceQuestion
  | OrgSagebionetworksRepoModelQuizTextFieldQuestion;
