/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The response body from validateDefiningSql
 */
export interface OrgSagebionetworksRepoModelTableValidateDefiningSqlResponse {
  /**
   * True if the provided SQL is valid, false otherwise.
   */
  isValid?: boolean;
  /**
   * If the definingSQL is invalid, this will contain a string describing why it is invalid. Otherwise, this will be null.
   */
  invalidReason?: string;
}
