/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Event send when project storage changes needs to be propagated.
 */
export interface OrgSagebionetworksRepoModelLimitsProjectStorageEvent {
  concreteType: OrgSagebionetworksRepoModelLimitsProjectStorageEvent.ConcreteTypeEnum;
  objectId?: string;
  objectVersion?: number;
  objectType?: string;
  timestamp?: string;
  projectId?: number;
}
export namespace OrgSagebionetworksRepoModelLimitsProjectStorageEvent {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.limits.ProjectStorageEvent';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelLimitsProjectStorageEvent:
      'org.sagebionetworks.repo.model.limits.ProjectStorageEvent' as ConcreteTypeEnum,
  };
}
