/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableCsvTableDescriptor } from './org-sagebionetworks-repo-model-table-csv-table-descriptor';

/**
 * A CSV table upload request.
 */
export interface OrgSagebionetworksRepoModelTableUploadToTableRequest {
  concreteType: OrgSagebionetworksRepoModelTableUploadToTableRequest.ConcreteTypeEnum;
  entityId?: string;
  /**
   * The ID of the table.
   */
  tableId?: string;
  /**
   * The ID of the file handle for a type of UPLOAD
   */
  uploadFileHandleId?: string;
  /**
   * Any RowSet returned from Synapse will contain the current etag of the change set.  To update any rows from a RowSet the etag must be provided with the POST.
   */
  updateEtag?: string;
  /**
   * The number of lines to skip from the start of the file.  The default value of 0 will be used if this is not provided by the caller.
   */
  linesToSkip?: number;
  csvTableDescriptor?: OrgSagebionetworksRepoModelTableCsvTableDescriptor;
  /**
   * Deprecated.
   */
  columnIds?: Array<string>;
}
export namespace OrgSagebionetworksRepoModelTableUploadToTableRequest {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.table.UploadToTableRequest';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelTableUploadToTableRequest:
      'org.sagebionetworks.repo.model.table.UploadToTableRequest' as ConcreteTypeEnum,
  };
}
