/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to create a new presigned URL that is used to establish a grid websocket connection.
 */
export interface OrgSagebionetworksRepoModelGridCreateGridPresignedUrlRequest {
  gridSessionId?: string;
  replicaId?: number;
}
