/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelAuthTwoFactorAuthToken } from './org-sagebionetworks-repo-model-auth-two-factor-auth-token';
import { OrgSagebionetworksRepoModelAuthAuthenticationReceiptToken } from './org-sagebionetworks-repo-model-auth-authentication-receipt-token';
import { OrgSagebionetworksRepoModelAuthTwoFactorAuthResetToken } from './org-sagebionetworks-repo-model-auth-two-factor-auth-reset-token';
import { OrgSagebionetworksRepoModelJoinTeamSignedToken } from './org-sagebionetworks-repo-model-join-team-signed-token';
import { OrgSagebionetworksRepoModelMessageSettings } from './org-sagebionetworks-repo-model-message-settings';
import { OrgSagebionetworksRepoModelInviteeVerificationSignedToken } from './org-sagebionetworks-repo-model-invitee-verification-signed-token';
import { OrgSagebionetworksRepoModelMembershipInvtnSignedToken } from './org-sagebionetworks-repo-model-membership-invtn-signed-token';
import { OrgSagebionetworksRepoModelMessageNotificationSettingsSignedToken } from './org-sagebionetworks-repo-model-message-notification-settings-signed-token';
import { OrgSagebionetworksRepoModelAuthNewUserSignedToken } from './org-sagebionetworks-repo-model-auth-new-user-signed-token';
import { OrgSagebionetworksRepoModelAuthPasswordResetSignedToken } from './org-sagebionetworks-repo-model-auth-password-reset-signed-token';
import { OrgSagebionetworksRepoModelPrincipalEmailValidationSignedToken } from './org-sagebionetworks-repo-model-principal-email-validation-signed-token';

/**
 * Interface for signed tokens
 */
/**
 * @type OrgSagebionetworksRepoModelSignedTokenInterface
 * Interface for signed tokens
 * @export
 */
export type OrgSagebionetworksRepoModelSignedTokenInterface =
  | OrgSagebionetworksRepoModelAuthAuthenticationReceiptToken
  | OrgSagebionetworksRepoModelAuthNewUserSignedToken
  | OrgSagebionetworksRepoModelAuthPasswordResetSignedToken
  | OrgSagebionetworksRepoModelAuthTwoFactorAuthResetToken
  | OrgSagebionetworksRepoModelAuthTwoFactorAuthToken
  | OrgSagebionetworksRepoModelInviteeVerificationSignedToken
  | OrgSagebionetworksRepoModelJoinTeamSignedToken
  | OrgSagebionetworksRepoModelMembershipInvtnSignedToken
  | OrgSagebionetworksRepoModelMessageNotificationSettingsSignedToken
  | OrgSagebionetworksRepoModelPrincipalEmailValidationSignedToken;
