/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelSearchDslQuery } from './org-sagebionetworks-repo-model-search-dsl-query';
import { OrgSagebionetworksRepoModelSearchDslHighlight } from './org-sagebionetworks-repo-model-search-dsl-highlight';
import { OrgSagebionetworksRepoModelSearchDslHighlightField } from './org-sagebionetworks-repo-model-search-dsl-highlight-field';

/**
 * Highlight options shared by the top-level highlight block and the per-field highlight overrides.
 */
/**
 * @type OrgSagebionetworksRepoModelSearchDslHighlightCommonOptions
 * Highlight options shared by the top-level highlight block and the per-field highlight overrides.
 * @export
 */
export type OrgSagebionetworksRepoModelSearchDslHighlightCommonOptions =
  | OrgSagebionetworksRepoModelSearchDslHighlight
  | OrgSagebionetworksRepoModelSearchDslHighlightField;
