/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A filter using a single value against a column. Values within the values list have an OR relationship
 */
export interface OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter {
  concreteType: OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter.ConcreteTypeEnum;
  /**
   * When null (default) or false, this condition will be applied to WHERE clause of table/view query.  When set to true, for a query against a VirtualTable, this condition will be applied to the WHERE clause of the VirtualTable\'s definingSQL.
   */
  isDefiningCondition?: boolean;
  /**
   * Values to be used with the filter.
   */
  values?: Array<string>;
  /**
   * name of the column to filter
   */
  columnName?: string;
  /**
   * Determines the filter operation to perform
   */
  operator?: OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter.OperatorEnum;
}
export namespace OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter {
  export type ConcreteTypeEnum =
    'org.sagebionetworks.repo.model.table.ColumnSingleValueQueryFilter';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter:
      'org.sagebionetworks.repo.model.table.ColumnSingleValueQueryFilter' as ConcreteTypeEnum,
  };
  export type OperatorEnum = 'LIKE' | 'EQUAL' | 'IN';
  export const OperatorEnum = {
    Like: 'LIKE' as OperatorEnum,
    Equal: 'EQUAL' as OperatorEnum,
    In: 'IN' as OperatorEnum,
  };
}
