/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTablePartialRow } from './org-sagebionetworks-repo-model-table-partial-row';
import { OrgSagebionetworksRepoModelTableSparseRowDto } from './org-sagebionetworks-repo-model-table-sparse-row-dto';

/**
 * Implementation has an etag.
 */
/**
 * @type OrgSagebionetworksRepoModelHasEtag
 * Implementation has an etag.
 * @export
 */
export type OrgSagebionetworksRepoModelHasEtag =
  | OrgSagebionetworksRepoModelTablePartialRow
  | OrgSagebionetworksRepoModelTableSparseRowDto;
