/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelGridSqlSqlExpression } from './org-sagebionetworks-repo-model-grid-sql-sql-expression';

export interface OrgSagebionetworksRepoModelGridSqlFunctionCall {
  concreteType: OrgSagebionetworksRepoModelGridSqlFunctionCall.ConcreteTypeEnum;
  name?: string;
  /**
   * An array of arguments passed to the function.
   */
  arguments?: Array<OrgSagebionetworksRepoModelGridSqlSqlExpression>;
  distinct?: boolean;
}
export namespace OrgSagebionetworksRepoModelGridSqlFunctionCall {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.grid.sql.FunctionCall';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelGridSqlFunctionCall:
      'org.sagebionetworks.repo.model.grid.sql.FunctionCall' as ConcreteTypeEnum,
  };
}
