/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelRegistryEntityTypeMigrationSpec } from './org-sagebionetworks-repo-model-registry-entity-type-migration-spec';

/**
 * Metadata to describe the migration of nodes
 */
export interface OrgSagebionetworksRepoModelRegistryMigrationSpec {
  migrationMetadata?: Array<OrgSagebionetworksRepoModelRegistryEntityTypeMigrationSpec>;
}
