/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelFileS3UploadDestination } from './org-sagebionetworks-repo-model-file-s3-upload-destination';
import { OrgSagebionetworksRepoModelFileExternalS3UploadDestination } from './org-sagebionetworks-repo-model-file-external-s3-upload-destination';
import { OrgSagebionetworksRepoModelLimitsProjectStorageLocationUsage } from './org-sagebionetworks-repo-model-limits-project-storage-location-usage';
import { OrgSagebionetworksRepoModelFileExternalObjectStoreUploadDestination } from './org-sagebionetworks-repo-model-file-external-object-store-upload-destination';
import { OrgSagebionetworksRepoModelFileExternalGoogleCloudUploadDestination } from './org-sagebionetworks-repo-model-file-external-google-cloud-upload-destination';
import { OrgSagebionetworksRepoModelFileExternalUploadDestination } from './org-sagebionetworks-repo-model-file-external-upload-destination';

/**
 * The upload destination contains information to start an upload of a file generated according to the underlying <a href=\"${org.sagebionetworks.repo.model.project.StorageLocationSetting}\">StorageLocationSetting</a>.
 */
/**
 * @type OrgSagebionetworksRepoModelFileUploadDestination
 * The upload destination contains information to start an upload of a file generated according to the underlying <a href=\"${org.sagebionetworks.repo.model.project.StorageLocationSetting}\">StorageLocationSetting</a>.
 * @export
 */
export type OrgSagebionetworksRepoModelFileUploadDestination =
  | OrgSagebionetworksRepoModelFileExternalGoogleCloudUploadDestination
  | OrgSagebionetworksRepoModelFileExternalObjectStoreUploadDestination
  | OrgSagebionetworksRepoModelFileExternalS3UploadDestination
  | OrgSagebionetworksRepoModelFileExternalUploadDestination
  | OrgSagebionetworksRepoModelFileS3UploadDestination;
