/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelReference } from './org-sagebionetworks-repo-model-reference';

/**
 * JSON schema for a Link
 */
export interface OrgSagebionetworksRepoModelLink {
  /**
   * The name of this entity.  Must be 256 characters or less. Names may only contain: letters, numbers, spaces, underscores, hyphens, periods, plus signs, apostrophes, and parentheses
   */
  name?: string;
  /**
   * The description of this entity.  Must be 1000 characters or less.
   */
  description?: string;
  /**
   * The unique immutable ID for this entity.  A new ID will be generated for new Entities.  Once issued, this ID is guaranteed to never change or be re-issued
   */
  id?: string;
  /**
   * Synapse employs an Optimistic Concurrency Control (OCC) scheme to handle concurrent updates. Since the E-Tag changes every time an entity is updated it is used to detect when a client\'s current representation of an entity is out-of-date.
   */
  etag?: string;
  /**
   * The date this entity was created.
   */
  createdOn?: string;
  /**
   * The date this entity was last modified.
   */
  modifiedOn?: string;
  /**
   * The ID of the user that created this entity.
   */
  createdBy?: string;
  /**
   * The ID of the user that last modified this entity.
   */
  modifiedBy?: string;
  /**
   * The ID of the Entity that is the parent of this Entity.
   */
  parentId?: string;
  /**
   * Indicates which implementation of Entity this object represents.  The value is the fully qualified class name, e.g. org.sagebionetworks.repo.model.FileEntity.
   */
  concreteType: OrgSagebionetworksRepoModelLink.ConcreteTypeEnum;
  linksTo?: OrgSagebionetworksRepoModelReference;
  /**
   * The synapse Entity\'s class name that this link points to.
   */
  linksToClassName?: string;
}
export namespace OrgSagebionetworksRepoModelLink {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.Link';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelLink: 'org.sagebionetworks.repo.model.Link' as ConcreteTypeEnum,
  };
}
