/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Temporary AWS credentials vended by STS (Security Token Service).
 */
export interface OrgSagebionetworksRepoModelStsStsCredentials {
  /**
   * The bucket that these credentials have access to.
   */
  bucket?: string;
  /**
   * The S3 key prefix that these credentials have access to.
   */
  baseKey?: string;
  /**
   * AWS access key ID.
   */
  accessKeyId?: string;
  /**
   * AWS secret access key.
   */
  secretAccessKey?: string;
  /**
   * AWS temporary session token.
   */
  sessionToken?: string;
  /**
   * The date-time that these credentials expire.
   */
  expiration?: string;
}
