/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelSearchSearchQueryPart =
  | 'HITS'
  | 'TOTAL_HITS'
  | 'SELECT_COLUMNS'
  | 'FACETS';

export const OrgSagebionetworksRepoModelSearchSearchQueryPart = {
  Hits: 'HITS' as OrgSagebionetworksRepoModelSearchSearchQueryPart,
  TotalHits: 'TOTAL_HITS' as OrgSagebionetworksRepoModelSearchSearchQueryPart,
  SelectColumns: 'SELECT_COLUMNS' as OrgSagebionetworksRepoModelSearchSearchQueryPart,
  Facets: 'FACETS' as OrgSagebionetworksRepoModelSearchSearchQueryPart,
};
