/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A request to list eDUC templates.
 */
export interface OrgSagebionetworksRepoModelEducEDucTemplateListRequest {
  /**
   * A token used to get the next page of results.
   */
  nextPageToken?: string;
}
