/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request for a single page of CurationTasks with optional filtering.
 */
export interface OrgSagebionetworksRepoModelCurationListCurationTaskRequest {
  /**
   * Optional. The synId of the project. If omitted, results are aggregated across projects.
   */
  projectId?: string;
  /**
   * Optional. Filter tasks assigned to specific users or teams.
   */
  assigneeIds?: Array<string>;
  /**
   * Optional. When true, filter to tasks assigned to the caller or any team the caller belongs to. Cannot be combined with assigneeIds.
   */
  assignedToMe?: boolean;
  /**
   * Optional. Filter tasks by their current state.
   */
  stateFilter?: Array<OrgSagebionetworksRepoModelCurationListCurationTaskRequest.StateFilterEnum>;
  /**
   * Optional. Filter tasks by their task IDs.
   */
  taskIds?: Array<number>;
  /**
   * Forward the returned \'nextPageToken\' to get the next page of results.
   */
  nextPageToken?: string;
}
export namespace OrgSagebionetworksRepoModelCurationListCurationTaskRequest {
  export type StateFilterEnum =
    | 'NOT_STARTED'
    | 'IN_PROGRESS'
    | 'EXECUTING'
    | 'IN_REVIEW'
    | 'COMPLETED'
    | 'CANCELED';
  export const StateFilterEnum = {
    NotStarted: 'NOT_STARTED' as StateFilterEnum,
    InProgress: 'IN_PROGRESS' as StateFilterEnum,
    Executing: 'EXECUTING' as StateFilterEnum,
    InReview: 'IN_REVIEW' as StateFilterEnum,
    Completed: 'COMPLETED' as StateFilterEnum,
    Canceled: 'CANCELED' as StateFilterEnum,
  };
}
