/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelSearchDslQuery } from './org-sagebionetworks-repo-model-search-dsl-query';

/**
 * Per-field <a href=\"https://docs.opensearch.org/latest/search-plugins/searching-data/highlight/\">highlight</a> options, carried as the value of a <a href=\"${org.sagebionetworks.repo.model.search.dsl.Highlight}\">Highlight</a> <code>fields</code> entry (the map key is the column name). Any option set here overrides the top-level highlight option for this field.
 */
export interface OrgSagebionetworksRepoModelSearchDslHighlightField {
  /**
   * Optional. Maximum characters per highlighted fragment. Capped server-side.
   */
  fragment_size?: number;
  /**
   * Optional. Character offset at which to start highlighting (fvh only).
   */
  fragment_offset?: number;
  /**
   * Optional. Number of leading characters to return when there is no match.
   */
  no_match_size?: number;
  /**
   * Optional. Fragment ordering: <code>none</code> (default) or <code>score</code>.
   */
  order?: string;
  /**
   * Optional. Fragmentation strategy: <code>simple</code> or <code>span</code> (plain highlighter).
   */
  fragmenter?: string;
  /**
   * Optional. Boundary detection: <code>chars</code>, <code>sentence</code>, or <code>word</code>.
   */
  boundary_scanner?: string;
  /**
   * Optional. Locale used by the boundary scanner.
   */
  boundary_scanner_locale?: string;
  /**
   * Optional. Characters treated as boundaries by the <code>chars</code> scanner.
   */
  boundary_chars?: string;
  /**
   * Optional. How far the boundary scanner looks for a boundary.
   */
  boundary_max_scan?: number;
  /**
   * Optional. Maximum length of a fragment.
   */
  max_fragment_length?: number;
  /**
   * Optional. Maximum character offset analyzed for highlighting.
   */
  max_analyzer_offset?: number;
  /**
   * Optional. Maximum number of matching phrases considered (fvh only).
   */
  phrase_limit?: number;
  /**
   * Optional. Whether only fields that matched the query are highlighted. Default <code>true</code>.
   */
  require_field_match?: boolean;
  /**
   * Optional. Whether to highlight only fields that passed the query filter.
   */
  highlight_filter?: boolean;
  /**
   * Optional. Whether to highlight from the original <code>_source</code> rather than stored fields.
   */
  force_source?: boolean;
  /**
   * Optional. Built-in tag schema (<code>styled</code>) for the highlight markup.
   */
  tags_schema?: string;
  /**
   * Optional. Highlighter implementation: <code>unified</code> (default), <code>plain</code>, or <code>fvh</code>. The <code>semantic</code> highlighter is rejected.
   */
  type?: string;
  /**
   * Optional. Maximum number of fragments to return for this field. Capped server-side.
   */
  number_of_fragments?: number;
  /**
   * Optional. Opening tags wrapped around highlighted terms.
   */
  pre_tags?: Array<string>;
  /**
   * Optional. Closing tags wrapped around highlighted terms.
   */
  post_tags?: Array<string>;
  /**
   * Optional. Other fields whose matches also highlight this field (fvh only).
   */
  matched_fields?: Array<string>;
  highlight_query?: OrgSagebionetworksRepoModelSearchDslQuery;
}
