/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelEntityHeader } from './org-sagebionetworks-repo-model-entity-header';

/**
 * Response of EntityHeaders for the children of a given parent Entity
 */
export interface OrgSagebionetworksRepoModelEntityChildrenResponse {
  /**
   * The headers of each child.
   */
  page?: Array<OrgSagebionetworksRepoModelEntityHeader>;
  nextPageToken?: string;
  totalChildCount?: number;
  sumFileSizesBytes?: number;
}
