/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represent the current size and limits for a single project storage location.
 */
export interface OrgSagebionetworksRepoModelLimitsProjectStorageLocationUsage {
  storageLocationId?: number;
  sumFileBytes?: number;
  maxAllowedFileBytes?: number;
  isOverLimit?: boolean;
}
