/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * JSON schema for a log entry
 */
export interface OrgSagebionetworksRepoModelLogEntry {
  /**
   * The label for the message to log, which determines grouping in cloudwatch.
   */
  label?: string;
  /**
   * The message to log.
   */
  message?: string;
  /**
   * The optional stacktrace to log.
   */
  stacktrace?: string;
}
