/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The registration of a custom AWS agent.
 */
export interface OrgSagebionetworksRepoModelAgentAgentRegistration {
  agentRegistrationId?: string;
  awsAgentId?: string;
  awsAliasId?: string;
  registeredOn?: string;
  type?: string;
}
