/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface OrgSagebionetworksRepoModelGridSqlIdentifier {
  concreteType: OrgSagebionetworksRepoModelGridSqlIdentifier.ConcreteTypeEnum;
  value?: string;
}
export namespace OrgSagebionetworksRepoModelGridSqlIdentifier {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.grid.sql.Identifier';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelGridSqlIdentifier:
      'org.sagebionetworks.repo.model.grid.sql.Identifier' as ConcreteTypeEnum,
  };
}
