/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelDownloadActionRequiredRequest } from './org-sagebionetworks-repo-model-download-action-required-request';
import { OrgSagebionetworksRepoModelDownloadFilesStatisticsRequest } from './org-sagebionetworks-repo-model-download-files-statistics-request';
import { OrgSagebionetworksRepoModelDownloadAvailableFilesRequest } from './org-sagebionetworks-repo-model-download-available-files-request';
import { OrgSagebionetworksRepoModelDownloadSort } from './org-sagebionetworks-repo-model-download-sort';

/**
 * Required.  Must be one of the implementations of QueryRequestDetails.
 */
/**
 * @type OrgSagebionetworksRepoModelDownloadQueryRequestDetails
 * Required.  Must be one of the implementations of QueryRequestDetails.
 * @export
 */
export type OrgSagebionetworksRepoModelDownloadQueryRequestDetails =
  | OrgSagebionetworksRepoModelDownloadActionRequiredRequest
  | OrgSagebionetworksRepoModelDownloadAvailableFilesRequest
  | OrgSagebionetworksRepoModelDownloadFilesStatisticsRequest;
