/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelAggregateDataConfiguration } from './org-sagebionetworks-repo-model-aggregate-data-configuration';

/**
 * Request to change the DataType of an object.
 */
export interface OrgSagebionetworksRepoModelChangeDataTypeRequest {
  /**
   * Enumeration of data types the describe the contents of objects like Tables and Files.
   */
  dataType?: OrgSagebionetworksRepoModelChangeDataTypeRequest.DataTypeEnum;
  aggregateDataConfiguration?: OrgSagebionetworksRepoModelAggregateDataConfiguration;
}
export namespace OrgSagebionetworksRepoModelChangeDataTypeRequest {
  export type DataTypeEnum = 'SENSITIVE_DATA' | 'OPEN_DATA' | 'AGGREGATE_DATA';
  export const DataTypeEnum = {
    SensitiveData: 'SENSITIVE_DATA' as DataTypeEnum,
    OpenData: 'OPEN_DATA' as DataTypeEnum,
    AggregateData: 'AGGREGATE_DATA' as DataTypeEnum,
  };
}
