/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelWebhookWebhook } from './orgSagebionetworksRepoModelWebhookWebhook';

/**
 * Response body containing the list of webhook for a user.
 */
export interface OrgSagebionetworksRepoModelWebhookListUserWebhooksResponse {
  /**
   * The Webhooks belonging to a given user.
   */
  page?: Array<OrgSagebionetworksRepoModelWebhookWebhook>;
  nextPageToken?: string;
}
