/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to create an account, validated via OAuth
 */
export interface OrgSagebionetworksRepoModelOauthOAuthAccountCreationRequest {
  provider?: string;
  authenticationCode?: string;
  redirectUrl?: string;
  userName?: string;
}
