/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelDataaccessSubmissionOrder = 'CREATED_ON' | 'MODIFIED_ON';

export const OrgSagebionetworksRepoModelDataaccessSubmissionOrder = {
  CreatedOn: 'CREATED_ON' as OrgSagebionetworksRepoModelDataaccessSubmissionOrder,
  ModifiedOn: 'MODIFIED_ON' as OrgSagebionetworksRepoModelDataaccessSubmissionOrder,
};
