/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelDownloadDownloadListItem } from './orgSagebionetworksRepoModelDownloadDownloadListItem';

/**
 * Request to remove a single batch of files to the user\'s download list.
 */
export interface OrgSagebionetworksRepoModelDownloadRemoveBatchOfFilesFromDownloadListRequest {
  /**
   * The batch of files to remove from the user\'s download list. Note: There is a limit of 1000 files per batch.
   */
  batchToRemove?: Array<OrgSagebionetworksRepoModelDownloadDownloadListItem>;
}
