/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelDataaccessAccessRequirementSortField =
  | 'CREATED_ON'
  | 'NAME'
  | 'CONCRETE_TYPE';

export const OrgSagebionetworksRepoModelDataaccessAccessRequirementSortField = {
  CreatedOn: 'CREATED_ON' as OrgSagebionetworksRepoModelDataaccessAccessRequirementSortField,
  Name: 'NAME' as OrgSagebionetworksRepoModelDataaccessAccessRequirementSortField,
  ConcreteType: 'CONCRETE_TYPE' as OrgSagebionetworksRepoModelDataaccessAccessRequirementSortField,
};
