/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Summary of files included in a download order.
 */
export interface OrgSagebionetworksRepoModelFileDownloadOrderSummary {
  orderId?: string;
  createdBy?: string;
  createdOn?: string;
  zipFileName?: string;
  totalSizeBytes?: number;
  totalNumberOfFiles?: number;
}
