/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelDrsPackageInformation } from './orgSagebionetworksRepoModelDrsPackageInformation';
import { OrgSagebionetworksRepoModelDrsOrganizationInformation } from './orgSagebionetworksRepoModelDrsOrganizationInformation';

/**
 * Drs service information
 */
export interface OrgSagebionetworksRepoModelDrsServiceInformation {
  id?: string;
  name?: string;
  type?: OrgSagebionetworksRepoModelDrsPackageInformation;
  description?: string;
  organization?: OrgSagebionetworksRepoModelDrsOrganizationInformation;
  contactUrl?: string;
  documentationUrl?: string;
  createdAt?: string;
  updatedAt?: string;
  environment?: string;
  version?: string;
}
