/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request for a batch of AccessApprovalInfo.
 */
export interface OrgSagebionetworksRepoModelBatchAccessApprovalInfoRequest {
  userId?: string;
  /**
   * The ID of the access requirements.
   */
  accessRequirementIds?: Array<string>;
}
