/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * JSON schema for a faceted key-value-range. This filter will match for values where min<=value<=max. At least one of either \'min\' or \'max\' must be set for this range to be valid
 */
export interface OrgSagebionetworksRepoModelSearchQueryKeyRange {
  key: string;
  min?: string;
  max?: string;
}
