/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * JSON schema for Team POJO
 */
export interface OrgSagebionetworksRepoModelTeam {
  id?: string;
  name?: string;
  description?: string;
  icon?: string;
  canPublicJoin?: boolean;
  canRequestMembership?: boolean;
  etag?: string;
  createdOn?: string;
  modifiedOn?: string;
  createdBy?: string;
  modifiedBy?: string;
}
