/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableColumnModel } from './orgSagebionetworksRepoModelTableColumnModel';

/**
 * Metadata about a TableEntity that can be included in an EntityBundle
 */
export interface OrgSagebionetworksRepoModelTableTableBundle {
  /**
   * The list of ColumnModels currently used by this table.
   */
  columnModels?: Array<OrgSagebionetworksRepoModelTableColumnModel>;
  maxRowsPerPage?: number;
}
