/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelVerificationVerificationStateEnum =
  | 'SUBMITTED'
  | 'APPROVED'
  | 'REJECTED'
  | 'SUSPENDED';

export const OrgSagebionetworksRepoModelVerificationVerificationStateEnum = {
  Submitted: 'SUBMITTED' as OrgSagebionetworksRepoModelVerificationVerificationStateEnum,
  Approved: 'APPROVED' as OrgSagebionetworksRepoModelVerificationVerificationStateEnum,
  Rejected: 'REJECTED' as OrgSagebionetworksRepoModelVerificationVerificationStateEnum,
  Suspended: 'SUSPENDED' as OrgSagebionetworksRepoModelVerificationVerificationStateEnum,
};
