/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelOauthOAuthRefreshTokenInformation } from './orgSagebionetworksRepoModelOauthOAuthRefreshTokenInformation';

/**
 * Metadata for a paginated list of refresh token metadata that give OAuth 2.0 clients access to access a user\'s resources in Synapse.
 */
export interface OrgSagebionetworksRepoModelOauthOAuthRefreshTokenInformationList {
  results?: Array<OrgSagebionetworksRepoModelOauthOAuthRefreshTokenInformation>;
  nextPageToken?: string;
}
