/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Data recored from a single web-services methods.
 */
export interface OrgSagebionetworksRepoModelAuditAccessRecord {
  sessionId?: string;
  timestamp?: number;
  userId?: number;
  method?: string;
  requestURL?: string;
  userAgent?: string;
  host?: string;
  origin?: string;
  xForwardedFor?: string;
  via?: string;
  threadId?: number;
  elapseMS?: number;
  success?: boolean;
  stack?: string;
  instance?: string;
  date?: string;
  vmId?: string;
  returnObjectId?: string;
  queryString?: string;
  responseStatus?: number;
  oauthClientId?: string;
  basicAuthUsername?: string;
  authenticationMethod?: string;
}
