/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableDatasetCollection } from './orgSagebionetworksRepoModelTableDatasetCollection';
import { OrgSagebionetworksRepoModelProject } from './orgSagebionetworksRepoModelProject';
import { OrgSagebionetworksRepoModelTableEntityView } from './orgSagebionetworksRepoModelTableEntityView';
import { OrgSagebionetworksRepoModelRow } from './orgSagebionetworksRepoModelRow';
import { OrgSagebionetworksRepoModelTableMaterializedView } from './orgSagebionetworksRepoModelTableMaterializedView';
import { OrgSagebionetworksRepoModelEnvironmentDescriptor } from './orgSagebionetworksRepoModelEnvironmentDescriptor';
import { OrgSagebionetworksRepoModelLink } from './orgSagebionetworksRepoModelLink';
import { OrgSagebionetworksRepoModelTableVirtualTable } from './orgSagebionetworksRepoModelTableVirtualTable';
import { OrgSagebionetworksRepoModelTableTableEntity } from './orgSagebionetworksRepoModelTableTableEntity';
import { OrgSagebionetworksRepoModelTableDataset } from './orgSagebionetworksRepoModelTableDataset';
import { OrgSagebionetworksRepoModelTableSubmissionView } from './orgSagebionetworksRepoModelTableSubmissionView';
import { OrgSagebionetworksRepoModelFileEntity } from './orgSagebionetworksRepoModelFileEntity';
import { OrgSagebionetworksRepoModelEntityRef } from './orgSagebionetworksRepoModelEntityRef';
import { OrgSagebionetworksRepoModelReference } from './orgSagebionetworksRepoModelReference';
import { OrgSagebionetworksRepoModelFolder } from './orgSagebionetworksRepoModelFolder';
import { OrgSagebionetworksRepoModelPreview } from './orgSagebionetworksRepoModelPreview';
import { OrgSagebionetworksRepoModelDockerDockerRepository } from './orgSagebionetworksRepoModelDockerDockerRepository';
import { OrgSagebionetworksRepoModelExampleEntity } from './orgSagebionetworksRepoModelExampleEntity';

/**
 * This is the base interface that all Entities implement.
 */
/**
 * @type OrgSagebionetworksRepoModelEntity
 * This is the base interface that all Entities implement.
 * @export
 */
export type OrgSagebionetworksRepoModelEntity =
  | OrgSagebionetworksRepoModelDockerDockerRepository
  | OrgSagebionetworksRepoModelExampleEntity
  | OrgSagebionetworksRepoModelFileEntity
  | OrgSagebionetworksRepoModelFolder
  | OrgSagebionetworksRepoModelLink
  | OrgSagebionetworksRepoModelPreview
  | OrgSagebionetworksRepoModelProject
  | OrgSagebionetworksRepoModelTableDataset
  | OrgSagebionetworksRepoModelTableDatasetCollection
  | OrgSagebionetworksRepoModelTableEntityView
  | OrgSagebionetworksRepoModelTableMaterializedView
  | OrgSagebionetworksRepoModelTableSubmissionView
  | OrgSagebionetworksRepoModelTableTableEntity
  | OrgSagebionetworksRepoModelTableVirtualTable;
