/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Object used to propagate table status changes
 */
export interface OrgSagebionetworksRepoModelTableTableStatusChangeEvent {
  concreteType: OrgSagebionetworksRepoModelTableTableStatusChangeEvent.ConcreteTypeEnum;
  objectId?: string;
  objectVersion?: number;
  objectType?: string;
  timestamp?: string;
  state?: string;
}
export namespace OrgSagebionetworksRepoModelTableTableStatusChangeEvent {
  export type ConcreteTypeEnum = 'org.sagebionetworks.repo.model.table.TableStatusChangeEvent';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelTableTableStatusChangeEvent:
      'org.sagebionetworks.repo.model.table.TableStatusChangeEvent' as ConcreteTypeEnum,
  };
}
