/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableColumnModel } from './orgSagebionetworksRepoModelTableColumnModel';
import { OrgSagebionetworksRepoModelTableJsonSubColumnModel } from './orgSagebionetworksRepoModelTableJsonSubColumnModel';

/**
 * Common properties of all ColumnModel implementation
 */
/**
 * @type OrgSagebionetworksRepoModelTableColumnModelInterface
 * Common properties of all ColumnModel implementation
 * @export
 */
export type OrgSagebionetworksRepoModelTableColumnModelInterface =
  | OrgSagebionetworksRepoModelTableColumnModel
  | OrgSagebionetworksRepoModelTableJsonSubColumnModel;
