/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response for an OAuth2 authorization url.
 */
export interface OrgSagebionetworksRepoModelOauthOAuthUrlResponse {
  authorizationUrl?: string;
}
