/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Metadata about entities
 */
export interface OrgSagebionetworksRepoModelRegistryEntityTypeMetadata {
  name: string;
  displayName?: string;
  className?: string;
  entityType?: string;
  defaultParentPath?: string;
  /**
   * The full path of the entity schema.
   */
  validParentTypes?: Array<string>;
  /**
   * The list of aliases that can be used to look an entity type with a query.
   */
  aliases?: Array<string>;
}
