/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelOauthOAuthAccountCreationRequest } from './orgSagebionetworksRepoModelOauthOAuthAccountCreationRequest';
import { OrgSagebionetworksRepoModelOauthOAuthValidationRequest } from './orgSagebionetworksRepoModelOauthOAuthValidationRequest';

/**
 * Request for an OAuth2 user validation.
 */
/**
 * @type OrgSagebionetworksRepoModelOauthOAuthValidationRequestInterface
 * Request for an OAuth2 user validation.
 * @export
 */
export type OrgSagebionetworksRepoModelOauthOAuthValidationRequestInterface =
  | OrgSagebionetworksRepoModelOauthOAuthAccountCreationRequest
  | OrgSagebionetworksRepoModelOauthOAuthValidationRequest;
