/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableEntityView } from './orgSagebionetworksRepoModelTableEntityView';
import { OrgSagebionetworksRepoModelTableViewScope } from './orgSagebionetworksRepoModelTableViewScope';

/**
 * Common definition of the ViewTypeMask
 */
/**
 * @type OrgSagebionetworksRepoModelTableHasViewTypeMask
 * Common definition of the ViewTypeMask
 * @export
 */
export type OrgSagebionetworksRepoModelTableHasViewTypeMask =
  | OrgSagebionetworksRepoModelTableEntityView
  | OrgSagebionetworksRepoModelTableViewScope;
