/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelPets = 'CAT' | 'DOG' | 'FISH';

export const OrgSagebionetworksRepoModelPets = {
  Cat: 'CAT' as OrgSagebionetworksRepoModelPets,
  Dog: 'DOG' as OrgSagebionetworksRepoModelPets,
  Fish: 'FISH' as OrgSagebionetworksRepoModelPets,
};
