/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelEntityGroupRecord } from './orgSagebionetworksRepoModelEntityGroupRecord';

/**
 * JSON schema for an Entity Group POJO
 */
export interface OrgSagebionetworksRepoModelEntityGroup {
  name?: string;
  description?: string;
  /**
   * The set of EntityGroupRecords for this group.
   */
  records?: Array<OrgSagebionetworksRepoModelEntityGroupRecord>;
}
