/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelFileFileHandle } from './orgSagebionetworksRepoModelFileFileHandle';

/**
 * Result of a FileHandleCopyRequest.
 */
export interface OrgSagebionetworksRepoModelFileFileHandleCopyResult {
  newFileHandle?: OrgSagebionetworksRepoModelFileFileHandle;
  originalFileHandleId?: string;
  failureCode?: string;
}
