/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A column model contains the metadata of a single column of a TableEntity
 */
export interface OrgSagebionetworksRepoModelTableSelectColumn {
  name?: string;
  columnType?: string;
  id?: string;
}
