/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * JSON schema for the possible status of a User with respect to Team membership.
 */
export interface OrgSagebionetworksRepoModelTeamMembershipStatus {
  teamId?: string;
  userId?: string;
  isMember?: boolean;
  hasOpenInvitation?: boolean;
  hasOpenRequest?: boolean;
  canJoin?: boolean;
  membershipApprovalRequired?: boolean;
  hasUnmetAccessRequirement?: boolean;
  canSendEmail?: boolean;
}
