/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The status of a Submission.
 */
export interface OrgSagebionetworksRepoModelDataaccessSubmissionStatus {
  submissionId?: string;
  submittedBy?: string;
  rejectedReason?: string;
  state?: string;
  modifiedOn?: string;
}
