/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelStatisticsFilesCountStatistics } from './orgSagebionetworksRepoModelStatisticsFilesCountStatistics';

/**
 * Container for the statistics relative to file downloads or uploads for the past 12 months (Excluding the current month).
 */
export interface OrgSagebionetworksRepoModelStatisticsMonthlyFilesStatistics {
  lastUpdatedOn?: string;
  /**
   * The file count buckets ordered by month, always contains the past 12 months (No matter if statistics are computed or not)
   */
  months?: Array<OrgSagebionetworksRepoModelStatisticsFilesCountStatistics>;
}
