/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes an aggregate of file actions (e.g. downloads/uploads) and (unique) users count for a specific time frame
 */
export interface OrgSagebionetworksRepoModelStatisticsFilesCountStatistics {
  rangeStart?: string;
  rangeEnd?: string;
  filesCount?: number;
  usersCount?: number;
}
