/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelAnnotationLongAnnotation } from './orgSagebionetworksRepoModelAnnotationLongAnnotation';
import { OrgSagebionetworksRepoModelAnnotationStringAnnotation } from './orgSagebionetworksRepoModelAnnotationStringAnnotation';
import { OrgSagebionetworksRepoModelAnnotationDoubleAnnotation } from './orgSagebionetworksRepoModelAnnotationDoubleAnnotation';

/**
 * Generic interface for a key-value Annotation pair
 */
/**
 * @type OrgSagebionetworksRepoModelAnnotationAnnotationBase
 * Generic interface for a key-value Annotation pair
 * @export
 */
export type OrgSagebionetworksRepoModelAnnotationAnnotationBase =
  | OrgSagebionetworksRepoModelAnnotationDoubleAnnotation
  | OrgSagebionetworksRepoModelAnnotationLongAnnotation
  | OrgSagebionetworksRepoModelAnnotationStringAnnotation;
