/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelDownloadActionRequiredRequest } from './orgSagebionetworksRepoModelDownloadActionRequiredRequest';
import { OrgSagebionetworksRepoModelDownloadFilesStatisticsRequest } from './orgSagebionetworksRepoModelDownloadFilesStatisticsRequest';
import { OrgSagebionetworksRepoModelDownloadAvailableFilesRequest } from './orgSagebionetworksRepoModelDownloadAvailableFilesRequest';
import { OrgSagebionetworksRepoModelDownloadSort } from './orgSagebionetworksRepoModelDownloadSort';

/**
 * Required.  Must be one of the implementations of QueryRequestDetails.
 */
/**
 * @type OrgSagebionetworksRepoModelDownloadQueryRequestDetails
 * Required.  Must be one of the implementations of QueryRequestDetails.
 * @export
 */
export type OrgSagebionetworksRepoModelDownloadQueryRequestDetails =
  | OrgSagebionetworksRepoModelDownloadActionRequiredRequest
  | OrgSagebionetworksRepoModelDownloadAvailableFilesRequest
  | OrgSagebionetworksRepoModelDownloadFilesStatisticsRequest;
