/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A request to convert an ACTAccessRequirement to a ManagedACTAccessRequirement.
 */
export interface OrgSagebionetworksRepoModelDataaccessAccessRequirementConversionRequest {
  accessRequirementId?: string;
  etag?: string;
  currentVersion?: number;
}
