/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Reference to a WikiPage
 */
export interface OrgSagebionetworksRepoModelDaoWikiPageKey {
  wikiPageId?: string;
  ownerObjectId?: string;
  ownerObjectType?: string;
}
