/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelRestrictableObjectDescriptor } from './orgSagebionetworksRepoModelRestrictableObjectDescriptor';
import { OrgSagebionetworksRepoModelTermsOfUseAccessRequirement } from './orgSagebionetworksRepoModelTermsOfUseAccessRequirement';
import { OrgSagebionetworksRepoModelSelfSignAccessRequirement } from './orgSagebionetworksRepoModelSelfSignAccessRequirement';
import { OrgSagebionetworksRepoModelPostMessageContentAccessRequirement } from './orgSagebionetworksRepoModelPostMessageContentAccessRequirement';

/**
 * JSON schema for the super-type of requirements which a user may approve themselves.
 */
/**
 * @type OrgSagebionetworksRepoModelSelfSignAccessRequirementInterface
 * JSON schema for the super-type of requirements which a user may approve themselves.
 * @export
 */
export type OrgSagebionetworksRepoModelSelfSignAccessRequirementInterface =
  | OrgSagebionetworksRepoModelPostMessageContentAccessRequirement
  | OrgSagebionetworksRepoModelSelfSignAccessRequirement
  | OrgSagebionetworksRepoModelTermsOfUseAccessRequirement;
