/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableDatasetCollection } from './orgSagebionetworksRepoModelTableDatasetCollection';
import { OrgSagebionetworksRepoModelEntityRef } from './orgSagebionetworksRepoModelEntityRef';
import { OrgSagebionetworksRepoModelTableDataset } from './orgSagebionetworksRepoModelTableDataset';

/**
 * A view referencing a fixed collections of entities
 */
/**
 * @type OrgSagebionetworksRepoModelTableEntityRefCollectionView
 * A view referencing a fixed collections of entities
 * @export
 */
export type OrgSagebionetworksRepoModelTableEntityRefCollectionView =
  | OrgSagebionetworksRepoModelTableDataset
  | OrgSagebionetworksRepoModelTableDatasetCollection;
