/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An Annotation containing a Double value
 */
export interface OrgSagebionetworksRepoModelAnnotationDoubleAnnotation {
  key?: string;
  isPrivate?: boolean;
  value?: number;
}
