/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus =
  | 'PENDING'
  | 'CODE_SENT'
  | 'FAILED'
  | 'REVOKED'
  | 'VERIFIED';

export const OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus = {
  Pending: 'PENDING' as OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus,
  CodeSent: 'CODE_SENT' as OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus,
  Failed: 'FAILED' as OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus,
  Revoked: 'REVOKED' as OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus,
  Verified: 'VERIFIED' as OrgSagebionetworksRepoModelWebhookWebhookVerificationStatus,
};
