/**
 * Synapse REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelProjectS3StorageLocationSetting } from './orgSagebionetworksRepoModelProjectS3StorageLocationSetting';
import { OrgSagebionetworksRepoModelProjectExternalGoogleCloudStorageLocationSetting } from './orgSagebionetworksRepoModelProjectExternalGoogleCloudStorageLocationSetting';
import { OrgSagebionetworksRepoModelProjectExternalS3StorageLocationSetting } from './orgSagebionetworksRepoModelProjectExternalS3StorageLocationSetting';

/**
 * A storage location with an optional base key
 */
/**
 * @type OrgSagebionetworksRepoModelProjectBaseKeyStorageLocationSetting
 * A storage location with an optional base key
 * @export
 */
export type OrgSagebionetworksRepoModelProjectBaseKeyStorageLocationSetting =
  | OrgSagebionetworksRepoModelProjectExternalGoogleCloudStorageLocationSetting
  | OrgSagebionetworksRepoModelProjectExternalS3StorageLocationSetting
  | OrgSagebionetworksRepoModelProjectS3StorageLocationSetting;
