/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter } from './orgSagebionetworksRepoModelTableColumnSingleValueQueryFilter';
import { OrgSagebionetworksRepoModelTableColumnMultiValueFunctionQueryFilter } from './orgSagebionetworksRepoModelTableColumnMultiValueFunctionQueryFilter';

/**
 * @type OrgSagebionetworksRepoModelTableHasValues
 * @export
 */
export type OrgSagebionetworksRepoModelTableHasValues =
  | OrgSagebionetworksRepoModelTableColumnMultiValueFunctionQueryFilter
  | OrgSagebionetworksRepoModelTableColumnSingleValueQueryFilter;
