/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * This setting type contains the list of upload locations for files in a project. Each id in the locations attribute points to an existing <a href=\"${org.sagebionetworks.repo.model.project.StorageLocationSetting}\">StorageLocationSetting</a>. The maximum number of storage locations that can be stored for a project is 10.
 */
export interface OrgSagebionetworksRepoModelProjectUploadDestinationListSetting {
  concreteType: OrgSagebionetworksRepoModelProjectUploadDestinationListSetting.ConcreteTypeEnum;
  id?: string;
  projectId?: string;
  settingsType?: string;
  etag?: string;
  /**
   * List of ids pointing to <a href=\"${org.sagebionetworks.repo.model.project.StorageLocationSetting}\">StorageLocationSetting</a>. The first one in the list is the default location; The maximum number of storage locations for a project is limited to 10.
   */
  locations?: Array<number>;
}
export namespace OrgSagebionetworksRepoModelProjectUploadDestinationListSetting {
  export type ConcreteTypeEnum =
    'org.sagebionetworks.repo.model.project.UploadDestinationListSetting';
  export const ConcreteTypeEnum = {
    OrgSagebionetworksRepoModelProjectUploadDestinationListSetting:
      'org.sagebionetworks.repo.model.project.UploadDestinationListSetting' as ConcreteTypeEnum,
  };
}
