/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Contains the user\'s email
 */
export interface OrgSagebionetworksRepoModelAuthUsername {
  email?: string;
}
