/**
 * Synapse REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrgSagebionetworksRepoModelMembershipInvitation } from './orgSagebionetworksRepoModelMembershipInvitation';

export interface PaginatedResultsOfMembershipInvitation {
  totalNumberOfResults?: number;
  results?: Array<OrgSagebionetworksRepoModelMembershipInvitation>;
}
