#!/usr/bin/env bash
# Inspired from https://github.com/docker-library/healthcheck/blob/master/postgres/docker-healthcheck
set -eo pipefail

host="$(hostname -i || echo '127.0.0.1')"
port="8401" # TODO read port from config
user="${MARIADB_USER:-root}"
password="${MARIADB_PASSWORD}"

# TODO check that the artifacts/tables created during initialization have been created
mysqladmin ping --port="$port" --user="$user" --password="$password" | grep 'mysqld is alive' || exit 1