# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StorageApi")

api_instance <- StorageApi$new()

test_that("GetAssetViewJson", {
  # tests for GetAssetViewJson
  # base path: http://localhost/api/v1
  # Gets the asset view table in json form
  # Gets the asset view table in json form
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param asset_type AssetType Type of asset, such as Synapse
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetFileMetadataArray", {
  # tests for GetDatasetFileMetadataArray
  # base path: http://localhost/api/v1
  # Gets all files associated with a dataset.
  # Gets all files associated with a dataset.
  # @param dataset_id character The ID of a dataset.
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param file_names array[character] A list of file names used to filter the output. (optional)
  # @param use_full_file_path character Whether or not to return the full path of output, or just the basename. (optional)
  # @return [FileMetadataArray]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetFileMetadataPage", {
  # tests for GetDatasetFileMetadataPage
  # base path: http://localhost/api/v1
  # Gets all files associated with a dataset.
  # Gets all files associated with a dataset.
  # @param dataset_id character The ID of a dataset.
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param file_names array[character] A list of file names used to filter the output. (optional)
  # @param use_full_file_path character Whether or not to return the full path of output, or just the basename. (optional)
  # @param page_number integer The page number to get for a paginated query (optional)
  # @param page_max_items integer The maximum number of items per page (up to 100,000) for paginated endpoints (optional)
  # @return [FileMetadataPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDatasetManifestJson", {
  # tests for GetDatasetManifestJson
  # base path: http://localhost/api/v1
  # Gets the manifest in json form
  # Gets the manifest in json form
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param dataset_id character The ID of a dataset.
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetManifestJson", {
  # tests for GetManifestJson
  # base path: http://localhost/api/v1
  # Gets the manifest in json form
  # Gets the manifest in json form
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param manifest_id character ID of a manifest
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProjectDatasetMetadataArray", {
  # tests for GetProjectDatasetMetadataArray
  # base path: http://localhost/api/v1
  # Gets all dataset metadata in folder under a given storage project that the current user has access to.
  # Gets all dataset meatdata in folder under a given storage project that the current user has access to.
  # @param project_id character The Synapse ID of a storage project.
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @return [DatasetMetadataArray]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProjectDatasetMetadataPage", {
  # tests for GetProjectDatasetMetadataPage
  # base path: http://localhost/api/v1
  # Gets a page of dataset metadata in folder under a given storage project that the current user has access to.
  # Gets a page of dataset meatdata in folder under a given storage project that the current user has access to.
  # @param project_id character The Synapse ID of a storage project.
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param page_number integer The page number to get for a paginated query (optional)
  # @param page_max_items integer The maximum number of items per page (up to 100,000) for paginated endpoints (optional)
  # @return [DatasetMetadataPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProjectManifestMetadataArray", {
  # tests for GetProjectManifestMetadataArray
  # base path: http://localhost/api/v1
  # Gets all manifests in a project folder that users have access to
  # Gets all manifests in a project folder that the current user has access to.
  # @param project_id character The Synapse ID of a storage project.
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @return [ManifestMetadataArray]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProjectManifestMetadataPage", {
  # tests for GetProjectManifestMetadataPage
  # base path: http://localhost/api/v1
  # Gets all manifests in a project folder that users have access to
  # Gets all manifests in a project folder that the current user has access to.
  # @param project_id character The Synapse ID of a storage project.
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param page_number integer The page number to get for a paginated query (optional)
  # @param page_max_items integer The maximum number of items per page (up to 100,000) for paginated endpoints (optional)
  # @return [ManifestMetadataPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProjectMetadataArray", {
  # tests for GetProjectMetadataArray
  # base path: http://localhost/api/v1
  # Gets all storage projects the current user has access to.
  # Gets all storage projects the current user has access to.
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param asset_type AssetType Type of asset, such as Synapse
  # @return [ProjectMetadataArray]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProjectMetadataPage", {
  # tests for GetProjectMetadataPage
  # base path: http://localhost/api/v1
  # Gets all storage projects the current user has access to.
  # Gets all storage projects the current user has access to.
  # @param asset_view_id character ID of view listing all project data assets. E.g. for Synapse this would be the Synapse ID of the fileview listing all data assets for a given project
  # @param asset_type AssetType Type of asset, such as Synapse
  # @param page_number integer The page number to get for a paginated query (optional)
  # @param page_max_items integer The maximum number of items per page (up to 100,000) for paginated endpoints (optional)
  # @return [ProjectMetadataPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
