# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ConnectedNodePairArray")

model_instance <- ConnectedNodePairArray$new()

test_that("connectedNodes", {
  # tests for the property `connectedNodes` (array[ConnectedNodePair])
  # An array of conncted node pairs.

  # uncomment below to test the property
  #expect_equal(model.instance$`connectedNodes`, "EXPECTED_RESULT")
})
