# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeContributionApi")

api_instance <- ChallengeContributionApi$new()

test_that("ListChallengeContributions", {
  # tests for ListChallengeContributions
  # base path: http://localhost/v1
  # List challenge contributions
  # List challenge contributions
  # @param challenge_id integer The unique identifier of the challenge.
  # @return [ChallengeContributionsPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
