# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidationRuleArray")

model_instance <- ValidationRuleArray$new()

test_that("validation_rules", {
  # tests for the property `validation_rules` (array[ValidationRule])
  # An array of validation rules.

  # uncomment below to test the property
  #expect_equal(model.instance$`validation_rules`, "EXPECTED_RESULT")
})
