# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SimpleChallengePlatform")

model_instance <- SimpleChallengePlatform$new()

test_that("id", {
  # tests for the property `id` (integer)
  # The unique identifier of a challenge platform.

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("slug", {
  # tests for the property `slug` (character)
  # The slug of the challenge platform.

  # uncomment below to test the property
  #expect_equal(model.instance$`slug`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the challenge platform.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})
