# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeContributionsPageAllOf")

model_instance <- ChallengeContributionsPageAllOf$new()

test_that("challengeContributions", {
  # tests for the property `challengeContributions` (array[ChallengeContribution])
  # A list of challenge contributions.

  # uncomment below to test the property
  #expect_equal(model.instance$`challengeContributions`, "EXPECTED_RESULT")
})
