# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChallengeInputDataTypesPageAllOf")

model_instance <- ChallengeInputDataTypesPageAllOf$new()

test_that("challengeInputDataTypes", {
  # tests for the property `challengeInputDataTypes` (array[ChallengeInputDataType])
  # A list of challenge input data types.

  # uncomment below to test the property
  #expect_equal(model.instance$`challengeInputDataTypes`, "EXPECTED_RESULT")
})
