# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsersPageAllOf")

model_instance <- UsersPageAllOf$new()

test_that("users", {
  # tests for the property `users` (array[User])
  # A list of users

  # uncomment below to test the property
  #expect_equal(model.instance$`users`, "EXPECTED_RESULT")
})
