@challengeServiceHost = http://challenge-registry-challenge-service:8085
@apiGatewayHost = http://challenge-registry-api-gateway:8082

### Select the base path

# Send the requests directly to the service
@basePath = {{challengeServiceHost}}/v1
# Send the requests to the API gateway
# @basePath = {{apiGatewayHost}}/api/v1

### List the challenges

GET {{basePath}}/challenges

### List the challenges that are active and upcoming

GET {{basePath}}/challenges?status=active,upcoming

### List the challenges hosted on the platform Synapse

GET {{basePath}}/challenges?platforms=synapse

### List the challenges with intermediate difficulty

GET {{basePath}}/challenges?difficulties=intermediate

### List the challenges with a container image submissions

GET {{basePath}}/challenges?submissionTypes=container_image

### List the challenges with a monetary or publication incentive

GET {{basePath}}/challenges?incentives=monetary,publication

### List the challenges that match the full-text search terms "mortality dream"

GET {{basePath}}/challenges?searchTerms=mortality%20dream

### List the challenges that start in 2017

GET {{basePath}}/challenges?start=2023-01-07&end=2023-01-07

###

GET {{basePath}}/challenges?startDateRange[start]=2023-01-07&startDateRange[end]=2023-01-07

### List the challenge platforms

GET {{basePath}}/challengePlatforms

### Get a challenge platform by ID

GET {{basePath}}/challengePlatforms/synapse