# coding: utf-8

"""
BixArena API

Advance bioinformatics by evaluating and ranking AI agents.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from bixarena_api_client_python.models.historical_leaderboard_entry import (
    HistoricalLeaderboardEntry,
)
from typing import Optional, Set
from typing_extensions import Self


class LeaderboardModelHistoryPage(BaseModel):
    """
    A page of historical leaderboard entries for a specific model.
    """  # noqa: E501

    number: StrictInt = Field(description="The page number.")
    size: StrictInt = Field(description="The number of items in a single page.")
    total_elements: StrictInt = Field(
        description="Total number of elements in the result set.", alias="totalElements"
    )
    total_pages: StrictInt = Field(
        description="Total number of pages in the result set.", alias="totalPages"
    )
    has_next: StrictBool = Field(
        description="Returns if there is a next page.", alias="hasNext"
    )
    has_previous: StrictBool = Field(
        description="Returns if there is a previous page.", alias="hasPrevious"
    )
    model_id: StrictStr = Field(description="Identifier for the model", alias="modelId")
    model_name: StrictStr = Field(
        description="Display name of the model", alias="modelName"
    )
    history: List[HistoricalLeaderboardEntry] = Field(
        description="A list of historical leaderboard entries."
    )
    __properties: ClassVar[List[str]] = [
        "number",
        "size",
        "totalElements",
        "totalPages",
        "hasNext",
        "hasPrevious",
        "modelId",
        "modelName",
        "history",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LeaderboardModelHistoryPage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item_history in self.history:
                if _item_history:
                    _items.append(_item_history.to_dict())
            _dict["history"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LeaderboardModelHistoryPage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "number": obj.get("number"),
                "size": obj.get("size"),
                "totalElements": obj.get("totalElements"),
                "totalPages": obj.get("totalPages"),
                "hasNext": obj.get("hasNext"),
                "hasPrevious": obj.get("hasPrevious"),
                "modelId": obj.get("modelId"),
                "modelName": obj.get("modelName"),
                "history": [
                    HistoricalLeaderboardEntry.from_dict(_item)
                    for _item in obj["history"]
                ]
                if obj.get("history") is not None
                else None,
            }
        )
        return _obj
