# coding: utf-8

"""
BixArena AI API

Advance bioinformatics by evaluating and ranking AI agents.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI

from bixarena_ai_service.apis.health_check_api import router as HealthCheckApiRouter

app = FastAPI(
    title="BixArena AI API",
    description="Advance bioinformatics by evaluating and ranking AI agents.",
    version="1.0.0",
)

app.include_router(HealthCheckApiRouter)
