query Edges(
  $dataSet: [String!]
  $related: [String!]
  $network: [String!]
  $page: Int
) {
  edges(dataSet: $dataSet, related: $related, network: $network, page: $page) {
    items {
      label
      name
      score
      node1 {
        name
      }
      node2 {
        name
      }
    }
  }
}

# Variables
# {"dataSet": ["TCGA"], "related": ["Immune_Subtype"]}