query MutationsBySamples(
  $dataSet: [String!]
  $entrez: [Int!]
  $feature: [String!]
  $featureClass: [String!]
  $mutationCode: [String!]
  $mutationId: [String!]
  $mutationType: [String!]
  $related: [String!]
  $sample: [String!]
  $tag: [String!]
  $status: [StatusEnum!]
) {
  mutationsBySamples(
    dataSet: $dataSet
    entrez: $entrez
    feature: $feature
    featureClass: $featureClass
    mutationCode: $mutationCode
    mutationId: $mutationId
    mutationType: $mutationType
    related: $related
    sample: $sample
    tag: $tag
    status: $status
  ) {
    name
    mutations {
      gene {
        entrez
        hgnc
      }
      mutationCode
      mutationType {
        name
        display
      }
      status
    }
  }
}

# Variables
# {}