query MutationsBySample(
  $entrez: [Int!]
  $mutationCode: [String!]
  $mutationId: [Int!]
  $mutationType: [String!]
  $page: Int
  $sample: [String!]
  $status: [StatusEnum!]
) {
  mutationsBySample(
    entrez: $entrez
    mutationCode: $mutationCode
    mutationId: $mutationId
    mutationType: $mutationType
    page: $page
    sample: $sample
    status: $status
  ) {
    items {
      name
      mutations {
        gene {
          entrez
          hgnc
        }
        mutationCode
        mutationType {
          name
          display
        }
        status
      }
    }
    page
    pages
    total
  }
}

# Variables
# { "entrez": [207], "sample": ["TCGA-02-0047"] }
