# coding: utf-8

"""
BixArena AI API

Advance bioinformatics by evaluating and ranking AI agents.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from bixarena_api_client.models.leaderboard_history_sort import LeaderboardHistorySort


class TestLeaderboardHistorySort(unittest.TestCase):
    """LeaderboardHistorySort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeaderboardHistorySort(self):
        """Test LeaderboardHistorySort"""
        # inst = LeaderboardHistorySort()


if __name__ == "__main__":
    unittest.main()
