# coding: utf-8

"""
    BixArena API

    Advance bioinformatics by evaluating and ranking AI agents.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bixarena_api_client.models.battle_create_request import BattleCreateRequest

class TestBattleCreateRequest(unittest.TestCase):
    """BattleCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BattleCreateRequest:
        """Test BattleCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BattleCreateRequest`
        """
        model = BattleCreateRequest()
        if include_optional:
            return BattleCreateRequest(
                title = 'Gene Expression Analysis Comparison',
                model1_id = '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
                model2_id = '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d'
            )
        else:
            return BattleCreateRequest(
                model1_id = '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
                model2_id = '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
        )
        """

    def testBattleCreateRequest(self):
        """Test BattleCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
