# coding: utf-8

"""
BixArena API

Advance bioinformatics by evaluating and ranking AI agents.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from bixarena_api_client.models.model_chat_request import ModelChatRequest


class TestModelChatRequest(unittest.TestCase):
    """ModelChatRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelChatRequest:
        """Test ModelChatRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ModelChatRequest`
        """
        model = ModelChatRequest()
        if include_optional:
            return ModelChatRequest(
                model_id = '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
                api_model_name = 'anthropic/claude-sonnet-4.5',
                api_base = 'https://openrouter.ai/api/v1',
                messages = [
                    bixarena_api_client.models.message_create.MessageCreate(
                        role = 'user', 
                        content = 'What is the capital of France?', )
                    ]
            )
        else:
            return ModelChatRequest(
                model_id = '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
                api_model_name = 'anthropic/claude-sonnet-4.5',
                api_base = 'https://openrouter.ai/api/v1',
                messages = [
                    bixarena_api_client.models.message_create.MessageCreate(
                        role = 'user', 
                        content = 'What is the capital of France?', )
                    ],
        )
        """

    def testModelChatRequest(self):
        """Test ModelChatRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
