/*
 * OpenChallenges REST API
 * Discover, explore, and contribute to open biomedical challenges.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.sagebionetworks.openchallenges.api.client.api;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.sagebionetworks.openchallenges.api.client.model.BasicError;
import org.sagebionetworks.openchallenges.api.client.model.ChallengesPerYear;

/**
 * API tests for ChallengeAnalyticsApi
 */
@Disabled
public class ChallengeAnalyticsApiTest {

  private final ChallengeAnalyticsApi api = new ChallengeAnalyticsApi();

  /**
   * Get the number of challenges tracked per year
   *
   * Returns the number of challenges tracked per year
   */
  @Test
  public void getChallengesPerYearTest() {
    ChallengesPerYear response = api.getChallengesPerYear();
    // TODO: test validations
  }
}
