# coding: utf-8

"""
OpenChallenges API

Discover, explore, and contribute to open biomedical challenges.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuthScope(str, Enum):
    """
    Permission scope defining specific access rights
    """

    """
    allowed enum values
    """
    OPENID = "openid"
    PROFILE = "profile"
    EMAIL = "email"
    READ_COLON_PROFILE = "read:profile"
    UPDATE_COLON_PROFILE = "update:profile"
    READ_COLON_API_MINUS_KEY = "read:api-key"
    CREATE_COLON_API_MINUS_KEY = "create:api-key"
    UPDATE_COLON_API_MINUS_KEY = "update:api-key"
    DELETE_COLON_API_MINUS_KEY = "delete:api-key"
    ROTATE_COLON_API_MINUS_KEY = "rotate:api-key"
    READ_COLON_ORGANIZATIONS = "read:organizations"
    CREATE_COLON_ORGANIZATIONS = "create:organizations"
    UPDATE_COLON_ORGANIZATIONS = "update:organizations"
    DELETE_COLON_ORGANIZATIONS = "delete:organizations"
    READ_COLON_CHALLENGES = "read:challenges"
    CREATE_COLON_CHALLENGES = "create:challenges"
    UPDATE_COLON_CHALLENGES = "update:challenges"
    DELETE_COLON_CHALLENGES = "delete:challenges"
    READ_COLON_CHALLENGES_MINUS_ANALYTICS = "read:challenges-analytics"
    READ_COLON_CHALLENGE_MINUS_PLATFORMS = "read:challenge-platforms"
    CREATE_COLON_CHALLENGE_MINUS_PLATFORMS = "create:challenge-platforms"
    UPDATE_COLON_CHALLENGE_MINUS_PLATFORMS = "update:challenge-platforms"
    DELETE_COLON_CHALLENGE_MINUS_PLATFORMS = "delete:challenge-platforms"
    READ_COLON_EDAM_MINUS_CONCEPTS = "read:edam-concepts"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuthScope from a JSON string"""
        return cls(json.loads(json_str))
