# coding: utf-8

"""
    OpenChallenges REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openchallenges_api_client_python.models.edam_concept import EdamConcept


class TestEdamConcept(unittest.TestCase):
    """EdamConcept unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdamConcept:
        """Test EdamConcept
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EdamConcept`
        """
        model = EdamConcept()
        if include_optional:
            return EdamConcept(
                id = 1,
                class_id = 'http://edamontology.org/data_0850',
                preferred_label = 'Sequence set'
            )
        else:
            return EdamConcept(
                id = 1,
                class_id = 'http://edamontology.org/data_0850',
                preferred_label = 'Sequence set',
        )
        """

    def testEdamConcept(self):
        """Test EdamConcept"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
