# coding: utf-8

"""
OpenChallenges REST API

Discover, explore, and contribute to open biomedical challenges.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openchallenges_api_client_python.models.basic_error import BasicError


class TestBasicError(unittest.TestCase):
    """BasicError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasicError:
        """Test BasicError
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BasicError`
        """
        model = BasicError()
        if include_optional:
            return BasicError(
                title = '',
                status = 56,
                detail = '',
                type = ''
            )
        else:
            return BasicError(
                title = '',
                status = 56,
        )
        """

    def testBasicError(self):
        """Test BasicError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
