# coding: utf-8

"""
    OpenChallenges REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openchallenges_api_client_python.models.challenge_contribution_role import (
    ChallengeContributionRole,
)


class TestChallengeContributionRole(unittest.TestCase):
    """ChallengeContributionRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChallengeContributionRole(self):
        """Test ChallengeContributionRole"""
        # inst = ChallengeContributionRole()


if __name__ == "__main__":
    unittest.main()
