# coding: utf-8

"""
    OpenChallenges REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openchallenges.models.user_create_response import UserCreateResponse


class TestUserCreateResponse(unittest.TestCase):
    """UserCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCreateResponse:
        """Test UserCreateResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserCreateResponse`
        """
        model = UserCreateResponse()
        if include_optional:
            return UserCreateResponse(
                id = 1
            )
        else:
            return UserCreateResponse(
                id = 1,
        )
        """

    def testUserCreateResponse(self):
        """Test UserCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
