# coding: utf-8

"""
OpenChallenges API

Discover, explore, and contribute to open biomedical challenges.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from openchallenges_api_client.models.challenge_contribution import (
    ChallengeContribution,
)


class TestChallengeContribution(unittest.TestCase):
    """ChallengeContribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeContribution:
        """Test ChallengeContribution
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ChallengeContribution`
        """
        model = ChallengeContribution()
        if include_optional:
            return ChallengeContribution(
                id = 1,
                challenge_id = 1,
                organization_id = 1,
                role = 'challenge_organizer'
            )
        else:
            return ChallengeContribution(
                id = 1,
                challenge_id = 1,
                organization_id = 1,
                role = 'challenge_organizer',
        )
        """

    def testChallengeContribution(self):
        """Test ChallengeContribution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
