"""
OpenChallenges API

Discover, explore, and contribute to open biomedical challenges.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestUserRole(unittest.TestCase):
    """UserRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRole(self):
        """Test UserRole"""
        # inst = UserRole()


if __name__ == "__main__":
    unittest.main()
