"""
    Schematic REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.api.storage_api import StorageApi  # noqa: E501


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_storage_project_datasets(self):
        """Test case for list_storage_project_datasets

        Gets all datasets in folder under a given storage project that the current user has access to.  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
