@organizationServiceHost = http://openchallenges-organization-service:8084
@apiGatewayHost = http://openchallenges-api-gateway:8082

### Select the base path

# Send the requests directly to the service
@basePath = {{organizationServiceHost}}/v1
# Send the requests to the API gateway
# @basePath = {{apiGatewayHost}}/api/v1

### List the organizations

GET {{basePath}}/organizations

### List the orgs that match the full-text search terms "dream".

GET {{basePath}}/organizations?searchTerms=dream


### List the organizations by ids

GET {{basePath}}/organizations?ids=1

### List the organizations that categorized as featured

GET {{basePath}}/organizations?categories=featured

### List the organizations that contributed as either sponsor and/or data_contributor.

GET {{basePath}}/organizations?challengeContributionRoles=sponsor,data_contributor

### Sort the orgs by their creation time in desc order.

GET {{basePath}}/organizations?sort=created&direction=desc

### Sort the orgs by their name.

GET {{basePath}}/organizations?sort=name

### Sort the orgs by the number of challenges they contributed to.

GET {{basePath}}/organizations?sort=challenge_count&pageSize=5

### Get an organization by login

GET {{basePath}}/organizations/dream

### Get an organization by ID

GET {{basePath}}/organizations/1