query CopyNumberResults(
  $paging: PagingInput
  $distinct: Boolean
  $dataSet: [String!]
  $feature: [String!]
  $entrez: [Int!]
  $tag: [String!]
  $direction: DirectionEnum
  $minPValue: Float
  $maxPValue: Float
  $minLog10PValue: Float
  $maxLog10PValue: Float
  $minMeanNormal: Float
  $minMeanCnv: Float
  $minTStat: Float
) {
  copyNumberResults(
    paging: $paging
    distinct: $distinct
    dataSet: $dataSet
    feature: $feature
    entrez: $entrez
    tag: $tag
    direction: $direction
    minPValue: $minPValue
    maxPValue: $maxPValue
    minLog10PValue: $minLog10PValue
    maxLog10PValue: $maxLog10PValue
    minMeanNormal: $minMeanNormal
    minMeanCnv: $minMeanCnv
    minTStat: $minTStat
  ) {
    items {
      direction
      meanNormal
      meanCnv
      pValue
      log10PValue
      tStat
      tag {
        name
      }
      gene {
        entrez
        hgnc
      }
    }
    error
    paging {
      type
      pages
      total
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
      page
      limit
    }
  }
}

query CopyNumberResults(
  $paging: PagingInput
  $distinct: Boolean
  $dataSet: [String!]
  $feature: [String!]
  $entrez: [Int!]
  $tag: [String!]
  $direction: DirectionEnum
  $minPValue: Float
  $maxPValue: Float
  $minLog10PValue: Float
  $maxLog10PValue: Float
  $minMeanNormal: Float
  $minMeanCnv: Float
  $minTStat: Float
) {
  copyNumberResults(
    paging: $paging
    distinct: $distinct
    dataSet: $dataSet
    feature: $feature
    entrez: $entrez
    tag: $tag
    direction: $direction
    minPValue: $minPValue
    maxPValue: $maxPValue
    minLog10PValue: $minLog10PValue
    maxLog10PValue: $maxLog10PValue
    minMeanNormal: $minMeanNormal
    minMeanCnv: $minMeanCnv
    minTStat: $minTStat
  ) {
    paging {
      type
      pages
      total
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
      page
      limit
    }
    error
    items {
      id
      direction
      meanNormal
      meanCnv
      pValue
      log10PValue
      tStat
      dataSet {
        name
      }
      tag {
        name
      }
      gene {
        entrez
        hgnc
      }
      feature {
        name
      }
    }
  }
}

# Variables
# {"dataSet": ["TCGA"], "feature": ["frac_altered"]}
