query FeaturesByTag(
  $dataSet: [String!]
  $related: [String!]
  $tag: [String!]
  $feature: [String!]
  $featureClass: [String!]
  $sample: [String!]
  $minValue: Float
  $maxValue: Float
) {
  featuresByTag(
    dataSet: $dataSet
    related: $related
    tag: $tag
    feature: $feature
    featureClass: $featureClass
    sample: $sample
    minValue: $minValue
    maxValue: $maxValue
  ) {
    tag
    characteristics
    shortDisplay
    features {
      class
      display
      methodTag
      name
      order
      samples { name }
      valueMin
      valueMax
      unit
    }
  }
}

# Variables
# {"dataSet": ["TCGA"], "related": ["Immune_Subtype"], "feature": ["Det_Ratio"], "minValue": 0.094192693, "maxValue": 5.7561021}
# or
# {"dataSet": ["TCGA"], "related": ["Immune_Subtype"], "feature": ["Det_Ratio"], "featureClass": ["TIL Map Characteristic"]}