query GenesByTag(
  $dataSet: [String!]
  $entrez: [Int!]
  $feature: [String!]
  $featureClass: [String!]
  $geneType: [String!]
  $maxRnaSeqExpr: Float
  $minRnaSeqExpr: Float
  $related: [String!]
  $sample: [String!]
  $tag: [String!]
) {
  genesByTag(
    dataSet: $dataSet
    entrez: $entrez
    feature: $feature
    featureClass: $featureClass
    geneType: $geneType
    maxRnaSeqExpr: $maxRnaSeqExpr
    minRnaSeqExpr: $minRnaSeqExpr
    related: $related
    sample: $sample
    tag: $tag
  ) {
    tag
    characteristics
    color
    shortDisplay
    genes {
      entrez
      geneFamily
      samples {
        name
        rnaSeqExpr
      }
    }
  }
}

# Variables
# {"dataSet": ["TCGA"], "related": ["Immune_Subtype"], "tag": ["C1"], "feature": ["Det_Ratio"], "sample": ["TCGA-05-4420"], "entrez": [3627]}
