query Slides(
  $barcode: [String!]
  $ethnicity: [EthnicityEnum!]
  $gender: [GenderEnum!]
  $maxAgeAtDiagnosis: Int
  $maxHeight: Float
  $maxWeight: Float
  $minAgeAtDiagnosis: Int
  $minHeight: Float
  $minWeight: Float
  $name: [String!]
  $race: [RaceEnum!]
  $sample: [String!]
) {
  slides(
    barcode: $barcode
    ethnicity: $ethnicity
    gender: $gender
    maxAgeAtDiagnosis: $maxAgeAtDiagnosis
    maxHeight: $maxHeight
    maxWeight: $maxWeight
    minAgeAtDiagnosis: $minAgeAtDiagnosis
    minHeight: $minHeight
    minWeight: $minWeight
    name: $name
    race: $race
    sample: $sample
  ) {
    name
    patient {
      ageAtDiagnosis
    }
  }
}

# Variables
# {"barcode": ["TCGA-21-5787"]}
