import { Challenge } from '@sagebionetworks/challenge-registry/api-client-angular-deprecated';

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: '',
    name: 'awesome-challenge',
    displayName: 'Awesome Challenge',
    description:
      'This is the challenge tagline. It should be a short descriptive summary of the challenge',
    websiteUrl: 'https://www.synapse.org/',
    status: 'active',
    startDate: '2000-01-01',
    endDate: '2030-01-01',
    readmeId: '61b26e5ee98893556289e1b3',
    platformId: '61b26e5ee98893556289e1a8',
    ownerId: '61b26e5ce98893556289df29',
    organizations: ['awesome-org'],
    topics: ['breast', 'cancer'],
    fullName: 'dream/awesome-challenge',
    inputDataTypes: [
      'demographic',
      'clinical',
      'genomic',
      'survival',
      'mutation',
      'copy-number-variation',
      'gene-expression',
      'microarray',
    ],
    submissionTypes: ['PredictionFile'],
    incentiveTypes: ['Publication', 'SpeakingEngagement'],
    featured: true,
    starredCount: 99,
    viewCount: 9999,
    difficulty: 'GoodForBeginners',
    doi: '09.1937/09219137',
    createdAt: '2000-01-01',
    updatedAt: '2000-01-01',
  },
  {
    id: '',
    name: 'synapse-challenge',
    displayName: 'Synapse Challenge',
    description:
      'This is the challenge tagline. It should be a short descriptive summary of the challenge',
    websiteUrl: '',
    status: 'active',
    startDate: '2021-01-01',
    endDate: '2023-01-01',
    readmeId: '61b26e5ee98893556289e1b3',
    platformId: '61b26e5ee98893556289e1a8',
    ownerId: '61b26e5ce98893556289df29',
    organizations: ['synapse'],
    topics: ['drug', 'multi-targeting-drug'],
    fullName: 'dream/active-challenge',
    inputDataTypes: ['other', 'clinical', 'chemical-structure', 'drug-target'],
    submissionTypes: ['PredictionFile'],
    incentiveTypes: ['Publication'],
    featured: false,
    starredCount: 99,
    viewCount: 9999,
    difficulty: 'Intermediate',
    doi: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: '',
    name: 'dream-challenge',
    displayName: 'Dream Challenge',
    description:
      'This is the challenge tagline. It should be a short descriptive summary of the challenge',
    websiteUrl: '',
    status: 'completed',
    startDate: '2012-01-01',
    endDate: '2013-01-01',
    readmeId: '61b26e5ee98893556289e1b3',
    platformId: '61b26e5ee98893556289e1a8',
    ownerId: '61b26e5ce98893556289df29',
    organizations: ['dream'],
    topics: ['preterm-birth'],
    fullName: 'dream/completed-challenge',
    inputDataTypes: ['genomic', 'gene-expression', 'microarray'],
    submissionTypes: ['PredictionFile'],
    incentiveTypes: [],
    featured: false,
    starredCount: 99,
    viewCount: 9999,
    difficulty: 'Intermediate',
    doi: null,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: '',
    name: 'upcoming-challenge',
    displayName: 'Upcoming Challenge',
    description:
      'This is the challenge tagline. It should be a short descriptive summary of the challenge',
    websiteUrl: '',
    status: 'upcoming',
    startDate: '2023-01-01',
    endDate: '2030-01-01',
    readmeId: '61b26e5ee98893556289e1b3',
    platformId: '61b26e5ee98893556289e1a8',
    ownerId: '61b26e5ce98893556289df29',
    topics: ['cancer', 'drug', 'pd1'],
    fullName: 'dream/upcoming-challenge',
    inputDataTypes: [
      'demographic',
      'tmb',
      'other',
      'ihc',
      'genomic',
      'clinical',
      'gene-expression',
      'rna-sequencing',
    ],
    submissionTypes: ['DockerImage'],
    incentiveTypes: [],
    featured: false,
    starredCount: 99,
    viewCount: 9999,
    difficulty: 'Advanced',
    doi: null,
    createdAt: '',
    updatedAt: '',
  },
];
