@elasticsearchHost = http://openchallenges-elasticsearch:9200

### Get information about the ES cluster

GET {{elasticsearchHost}}

### Create challenge index

PUT {{elasticsearchHost}}/challenge-index
content-type: application/json

{
  "mappings": {
    "properties": {
      "userId": {
        "type": "long"
      },
      "id": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "createdAt": {
        "type": "date",
        "format": "yyyy-MM-dd'T'HH:mm:ssZZ"
      },
      "text": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  }
}

### Create example document

POST {{elasticsearchHost}}/challenge-index/_doc/1
content-type: application/json

{
  "userId": "1",
  "id": "1",
  "createdAt": "2020-01-01T23:00:50+0000",
  "text": "test multi word"
}

### Search example document with id="1"

GET {{elasticsearchHost}}/challenge-index/_search?q=id:1