@challengeServiceHost = http://challenge-service:8085
@apiGatewayHost = http://challenge-api-gateway:8082

### Select the base path

# Send the requests directly to the service 
# @basePath = {{challengeServiceHost}}/v1
# Send the requests to the API gateway
@basePath = {{apiGatewayHost}}/api/v1

### List the challenges

GET {{basePath}}/challenges

### List the challenge platforms

GET {{basePath}}/challengePlatforms

### Get a challenge platform by ID

GET {{basePath}}/challengePlatforms/synapse
