@apiGatewayHost = http://challenge-api-gateway:8082
@challengeServiceHost = http://challenge-organization-service:8085

### Select the desired base path

# Send the request directly to the service 
# @basePath = {{challengeServiceHost}}/v1
# Send the request to the API gateway
@basePath = {{apiGatewayHost}}/api/v1

### List the challenges

GET {{basePath}}/challenges

### List the challenge platform

GET {{basePath}}/challengePlatforms

### List the challenge platform (via the API gateway)

GET {{basePath}}/challengePlatforms/synapse
