services:
  bixarena-app-angular:
    image: ghcr.io/sage-bionetworks/bixarena-app-angular:${BIXARENA_VERSION:-local}
    container_name: bixarena-app-angular
    restart: always
    networks:
      - bixarena
    ports:
      - '4200:4200'
    env_file:
      - ../../../apps/bixarena/app-angular/.env
    depends_on:
      bixarena-api-gateway:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '--fail', '--silent', 'http://localhost:4200/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
