services:
  bixarena-lambda:
    image: ghcr.io/sage-bionetworks/bixarena-lambda:${BIXARENA_VERSION:-local}
    container_name: bixarena-lambda
    env_file:
      - ../../../apps/bixarena/lambda/.env
    networks:
      - bixarena
    ports:
      - '8117:8080'
    depends_on:
      - bixarena-postgres
