services:
  bixarena-worker:
    image: ghcr.io/sage-bionetworks/bixarena-worker:${BIXARENA_VERSION:-local}
    container_name: bixarena-worker
    env_file:
      - ../../../apps/bixarena/worker/.env
    networks:
      - bixarena
    ports:
      - '8117:8080'
    depends_on:
      - bixarena-postgres
