@clientId = test-client
@clientSecret = MiZwMWx3Tuw1mkySKId10lk7kPgKV9IZ

# Visitor account
@username = luke
@password = changeme

# Admin account
# @username = tschaffter
# @password = changeme

# @name login

POST http://localhost:8081/realms/test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&scope=openid
&client_id={{clientId}}
&client_secret={{clientSecret}}
&username={{username}}
&password={{password}}

### Check that /actuator endpoint is not protected

GET http://localhost:9000/actuator

### Get the list of movies

GET http://localhost:9000/movies
Authorization: Bearer {{login.response.body.$.access_token}}

### Get the movie specified

GET http://localhost:9000/movies/1
Authorization: Bearer {{login.response.body.$.access_token}}