@imageServiceHost = http://openchallenges-image-service:8086
@apiGatewayHost = http://openchallenges-api-gateway:8082

### Select the base path

# Send the requests directly to the service
@basePath = {{imageServiceHost}}/v1
# Send the requests to the API gateway
# @basePath = {{apiGatewayHost}}/api/v1

### Get the image with the key triforce.png

GET {{basePath}}/images/triforce.png

### Get the logo of the DREAM organization

GET {{basePath}}/images?objectKey=logo/dream.png
