@imageServiceHost = http://openchallenges-image-service:8086
@apiGatewayHost = http://openchallenges-api-gateway:8082

### Select the base path

# Send the requests directly to the service
@basePath = {{imageServiceHost}}/v1
# Send the requests to the API gateway
# @basePath = {{apiGatewayHost}}/api/v1

### Get the image with the key triforce.png

GET {{basePath}}/images?objectKey=triforce.png

### Get the logo of the DREAM organization

GET {{basePath}}/images?objectKey=logo%2Fdream.png

### Get the triforce with the height set to 100 px

GET {{basePath}}/images?objectKey=triforce.png&height=100px

### Get the triforce with the height set to 100 px and 16:9 aspect ratio

GET {{basePath}}/images?objectKey=triforce.png&height=100px&aspectRatio=16:9

### Get the triforce when specifying the aspect ratio but not the height generates an error

GET {{basePath}}/images?objectKey=triforce.png&aspectRatio=16:9