/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.sagebionetworks.model.ad.api.next.api;

import org.sagebionetworks.model.ad.api.next.model.dto.BasicErrorDto;
import org.sagebionetworks.model.ad.api.next.model.dto.GeneExpressionIndividualDto;
import org.sagebionetworks.model.ad.api.next.model.dto.GeneExpressionIndividualFilterQueryDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.lang.Nullable;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.14.0")
@Validated
@Tag(name = "Gene Expression Individual", description = "Operations about Individual Gene Expression results.")
public interface GeneExpressionIndividualApi {

    default GeneExpressionIndividualApiDelegate getDelegate() {
        return new GeneExpressionIndividualApiDelegate() {};
    }

    /**
     * GET /gene-expression-individual : Get gene expression individual data
     * Retrieve gene expression individual data based on specified filter criteria.
     *
     * @param geneExpressionIndividualFilterQuery The filter query used to retrieve a specific set of gene expression individual data. (optional)
     * @return Successfully retrieved individual gene expression data (status code 200)
     *         or Invalid request (status code 400)
     *         or The specified resource was not found (status code 404)
     *         or The request cannot be fulfilled due to an unexpected server error (status code 500)
     */
    @Operation(
        operationId = "getGeneExpressionIndividual",
        summary = "Get gene expression individual data",
        description = "Retrieve gene expression individual data based on specified filter criteria.",
        tags = { "Gene Expression Individual" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successfully retrieved individual gene expression data", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = GeneExpressionIndividualDto.class))),
                @Content(mediaType = "application/problem+json", array = @ArraySchema(schema = @Schema(implementation = GeneExpressionIndividualDto.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BasicErrorDto.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = BasicErrorDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "The specified resource was not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BasicErrorDto.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = BasicErrorDto.class))
            }),
            @ApiResponse(responseCode = "500", description = "The request cannot be fulfilled due to an unexpected server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BasicErrorDto.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = BasicErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/gene-expression-individual",
        produces = { "application/json", "application/problem+json" }
    )
    
    default ResponseEntity<List<GeneExpressionIndividualDto>> getGeneExpressionIndividual(
        @Parameter(name = "geneExpressionIndividualFilterQuery", description = "The filter query used to retrieve a specific set of gene expression individual data.", in = ParameterIn.QUERY) @Valid @Nullable GeneExpressionIndividualFilterQueryDto geneExpressionIndividualFilterQuery
    ) {
        return getDelegate().getGeneExpressionIndividual(geneExpressionIndividualFilterQuery);
    }

}
