#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Install the Node.js dependencies.
# rm -rf node_modules && yarn install --frozen-lockfile
node tools/check-nodejs-packages.js
node tools/check-java-packages.js
node tools/check-devcontainer-version.js