#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "post-rebased hook called"

# rm -rf node_modules && yarn install --frozen-lockfile

# # Notify the developer when a different dev container must be used.
# node tools/check-devcontainer-version.js
