#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node tools/check-nodejs-packages.js
node tools/check-devcontainer-version.js

# Install the Java dependencies.
yarn nx run-many --target=prepare-java --parallel=1
