#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

node tools/prepare-nodejs-envs.js
node tools/prepare-java-envs.js
node tools/prepare-python-envs.js
node tools/prepare-r-envs.js
# node tools/check-container-images.js
node tools/check-devcontainer-version.js