#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Install the Node.js dependencies.
yarn install --frozen-lockfile

# Install the Java dependencies.
yarn nx run-many --target=prepare-java --parallel=1

# Notify the developer when a different dev container must be used.
node tools/check-devcontainer-version.js