#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Install the Node.js dependencies.
# rm -rf node_modules && yarn install --immutable
node tools/check-nodejs-dependencies.js post-merge
node tools/check-java-environments.js
node tools/check-python-dependencies.js
node tools/check-container-images.js
node tools/check-devcontainer-version.js