#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# From the post-checkout docs https://git-scm.com/docs/githooks#_post_checkout
# The hook is given three parameters:
#  - the ref of the previous HEAD
#  - the ref of the new HEAD (which may or may not have changed)
#  - a flag indicating whether the checkout was:
#     - a branch checkout (changing branches, flag=1)
#     - a file checkout (retrieving a file from the index, flag=0).

# When the third script parameter is "1" we are executing a branch checkout
if [ "$3" = "1" ]; then

  DEPENDENCY_HASH_FILE=/tmp/dependency_hash
  if [ -f "$DEPENDENCY_HASH_FILE"]; then
    source "$DEPENDENCY_HASH_FILE"
  fi

  expected_yarn_lock_hash=$(sha256sum yarn.lock | awk '{print $1}')
  current_yarn_lock_hash=$YARN_LOCK_HASH

  echo "📦 Installing Node.js packages"
  if [ "$expected_yarn_lock_hash" != "$current_yarn_lock_hash" ]; then
    yarn install --frozen-lockfile
    echo "YARN_LOCK_HASH=$expected_yarn_lock_hash" > "$DEPENDENCY_HASH_FILE"
  fi

  # Install the Java dependencies.
  # yarn nx run-many --target=prepare-java --parallel=1

  # Notify the developer when a different dev container must be used.
  node tools/check-devcontainer-version.js
fi
