#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn nx affected --uncommitted --target=format
yarn nx affected --uncommitted --target=lint

# Re-index the staged files
git diff --name-only --cached | xargs -l git add