#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

nx affected --uncommitted --target=lint
nx affected --uncommitted --target=format

# Re-index the staged files after they have been formatted
# git diff --name-only --cached | xargs -l git add