/*
 * OpenChallenges REST API
 * Discover, explore, and contribute to open biomedical challenges.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.sagebionetworks.openchallenges.api.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateApiKeyRequest
 */
class CreateApiKeyRequestTest {

  private final CreateApiKeyRequest model = new CreateApiKeyRequest();

  /**
   * Model tests for CreateApiKeyRequest
   */
  @Test
  void testCreateApiKeyRequest() {
    // TODO: test CreateApiKeyRequest
  }

  /**
   * Test the property 'name'
   */
  @Test
  void nameTest() {
    // TODO: test name
  }

  /**
   * Test the property 'expiresIn'
   */
  @Test
  void expiresInTest() {
    // TODO: test expiresIn
  }
}
