/**
 * Model-AD API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemFilterTypeQuery } from './item-filter-type-query';

/**
 * Gene expression search query with pagination and filtering options.
 */
export interface GeneExpressionSearchQuery {
  /**
   * The page number.
   */
  pageNumber?: number;
  /**
   * The number of items in a single page.
   */
  pageSize?: number;
  /**
   * Array of category values from the dropdown selections. The API will parse these to extract the tissue and sex information. Expected format: [mainCategory, tissueCategory, sexCategory]
   */
  categories: Array<string>;
  /**
   * List of composite identifiers to filter by. Each identifier uses the format \"ensembl_gene_id~name\" where each identifier represents one complete combination of ensembl gene ID and gene name.  Example: \"ENSMUSG00000000001~Gnai3\" filters for documents matching that exact gene ID and name. Multiple items can be provided to filter for multiple specific combinations.
   */
  items?: Array<string> | null;
  itemFilterType?: ItemFilterTypeQuery;
}
export namespace GeneExpressionSearchQuery {}
