/**
 * Model-AD API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Sex } from './sex';

/**
 * Data for an individual
 */
export interface IndividualData {
  /**
   * Genotype of the individual
   */
  genotype: string;
  sex: Sex;
  /**
   * Unique identifier for the individual
   */
  individual_id: string;
  /**
   * Value for the individual
   */
  value: number;
}
export namespace IndividualData {}
