/**
 * Model-AD API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Link
 */
export interface Link {
  /**
   * Link text
   */
  link_text?: string;
  /**
   * URL for the related resource
   */
  link_url?: string;
}
