/**
 * Model-AD API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';

/**
 * Marmoset Model Overview object for comparison tools
 */
export interface MarmosetModelOverview {
  /**
   * Unique identifier for the marmoset model overview object
   */
  _id: string;
  /**
   * Model name
   */
  name: string;
  /**
   * Model type (e.g., Late Onset AD, Familial AD)
   */
  model_type: string;
  biomarkers?: Link;
  study_data: Link;
  /**
   * List of modified genes in the model
   */
  modified_genes: Array<string>;
  available_data: Array<MarmosetModelOverview.AvailableDataEnum>;
}
export namespace MarmosetModelOverview {
  export type AvailableDataEnum = 'Plasma Biomarkers';
  export const AvailableDataEnum = {
    PlasmaBiomarkers: 'Plasma Biomarkers' as AvailableDataEnum,
  };
}
