/**
 * Model-AD API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Specifies whether a model identifier refers to a name or modelGroup. - name: The identifier is a model name. - modelGroup: The identifier is a model group.
 */
export type ModelIdentifierType = 'name' | 'modelGroup';

export const ModelIdentifierType = {
  Name: 'name' as ModelIdentifierType,
  ModelGroup: 'modelGroup' as ModelIdentifierType,
};
