/**
 * Model-AD API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelData } from './modelData';
import { GeneticInfo } from './geneticInfo';

/**
 * Model details
 */
export interface Model {
  /**
   * Name of the model
   */
  name: string;
  /**
   * List of matched controls
   */
  matched_controls: Array<string>;
  /**
   * Type of the model
   */
  model_type: string;
  /**
   * Group contributing the model
   */
  contributing_group: string;
  /**
   * Synapse ID of the study
   */
  study_synid: string;
  /**
   * RRID of the model
   */
  rrid: string;
  /**
   * JAX ID of the model
   */
  jax_id: number;
  /**
   * AlzForum ID of the model
   */
  alzforum_id: string;
  /**
   * Genotype of the model
   */
  genotype: string;
  /**
   * List of aliases for the model
   */
  aliases: Array<string>;
  /**
   * Genetic information related to the Model
   */
  genetic_info: Array<GeneticInfo>;
  /**
   * List of biomarker data associated with the model
   */
  biomarkers: Array<ModelData>;
  /**
   * List of pathology data associated with the model
   */
  pathology: Array<ModelData>;
}
