name: Lint Dockerfiles

on:
  push:
    branches:
      - main
      - 'agora/**'
      - 'iatlas/**'
      - 'sage-monorepo/**'
      - 'sage/**'
  pull_request:

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout
        with:
          fetch-depth: 1

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          recursive: true
