name: Lint Dockerfiles

on:
  push:
    branches:
      - main
      - 'agora/**'
      - 'iatlas/**'
      - 'openchallenges/**'
      - 'sage-monorepo/**'
      - 'sage/**'
  pull_request:

permissions:
  contents: read

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        name: Checkout
        with:
          fetch-depth: 1

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          recursive: true
