name: release

on:
  push:
    tags:
      - 'agora/v*'
      - 'bixarena/v*'
      - 'model-ad/v*'
      - 'openchallenges/v*'
      - 'sage/v*'

permissions:
  contents: read
  packages: write # push images to ghcr.io

env:
  PRODUCT: ''
  VERSION: ''
  SHORT_SHA: ''

jobs:
  deploy:
    runs-on: ubuntu-22.04-4core-16GBRAM-150GBSSD
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 1

      - name: Extract product and version from Git tag
        run: |
          # Extract the product name (part before the first slash) and version (part after the first slash)
          PRODUCT=$(echo "${GITHUB_REF#refs/tags/}" | cut -d'/' -f1)
          VERSION=$(echo "${GITHUB_REF#refs/tags/}" | cut -d'/' -f2 | sed 's/^v//')
          SHORT_SHA=${GITHUB_SHA::7}

          # Output extracted values for the rest of the job
          echo "PRODUCT=${PRODUCT}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0

      - name: Set up the dev container
        uses: ./.github/actions/setup-dev-container

        # TODO: Identify the projects that actually need to be prepared. Here I'm not expecting any
        # affected project since this workflow does not affect projects. For now I'm keeping the
        # same behavior as before this change.
      - name: Prepare the affected projects
        run: |
          devcontainer exec --workspace-folder ../sage-monorepo bash -c ". ./dev-env.sh \
            && workspace-install-affected"

      - name: Build the Docker images for the specified product
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTOR: ${{ github.actor }}
        run: |
          devcontainer exec --workspace-folder ../sage-monorepo \
            --remote-env GH_TOKEN="$GH_TOKEN" \
            --remote-env GH_ACTOR="$GH_ACTOR" \
            bash -c '. ./dev-env.sh \
            && export VERSION=${{ env.VERSION }} \
            && echo "$GH_TOKEN" | docker login ghcr.io -u "$GH_ACTOR" --password-stdin \
            && nx run-many --target=build-image --projects=${{ env.PRODUCT }}-* --configuration=release'

      - name: Upload Sentry sourcemaps for the specified product
        run: |
          devcontainer exec --workspace-folder ../sage-monorepo \
            --remote-env SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
            --remote-env SENTRY_RELEASE=$SENTRY_RELEASE \
            bash -c ". ./dev-env.sh \
            && nx run-many --target=sentry-sourcemaps --projects=${{ env.PRODUCT }}-*"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ env.VERSION }}+${{ env.SHORT_SHA }}
