INSERT INTO challenge_organization (
    id,
    name,
    email,
    login,
    avatar_url,
    website_url,
    description
  )
VALUES (
    '1',
    'DREAM',
    'dream@sagebionetworks.org',
    'dream',
    'https://via.placeholder.com/300.png',
    'https://dreamchallenges.org',
    'Together, we share a vision to enable individuals and groups to collaborate openly so that the “wisdom of the crowd” provides the greatest impact on science and human health.'
  ),
  (
    '2',
    'BioCreative',
    '',
    'biocreative',
    'https://via.placeholder.com/300.png',
    'https://biocreative.bioinformatics.udel.edu/',
    ''
  ),
  (
    '3',
    'CAFA',
    '',
    'cafa',
    'https://via.placeholder.com/300.png',
    'https://www.biofunctionprediction.org/cafa/',
    ''
  ),
  (
    '4',
    'CAGI',
    '',
    'cagi',
    'https://via.placeholder.com/300.png',
    'https://genomeinterpretation.org/challenges.html',
    ''
  ),
  (
    '5',
    'CAMDA',
    '',
    'camda',
    'https://via.placeholder.com/300.png',
    'http://www.camda.info/',
    ''
  ),
  (
    '6',
    'CAMEO',
    '',
    'cameo',
    'https://via.placeholder.com/300.png',
    'https://www.cameo3d.org/',
    ''
  ),
  (
    '7',
    'CAMI',
    '',
    'cami',
    'https://via.placeholder.com/300.png',
    'https://data.cami-challenge.org/',
    ''
  ),
  (
    '8',
    'CAPRI',
    '',
    'capri',
    'https://via.placeholder.com/300.png',
    'https://www.ebi.ac.uk/msd-srv/capri/',
    ''
  ),
  (
    '9',
    'CASP',
    '',
    'casp',
    'https://via.placeholder.com/300.png',
    'https://predictioncenter.org/',
    ''
  ),
  (
    '10',
    'GAW',
    '',
    'gaw',
    'https://via.placeholder.com/300.png',
    'https://www.gaworkshop.org/',
    ''
  ),
  (
    '11',
    'iDash',
    '',
    'idash',
    'https://via.placeholder.com/300.png',
    'http://www.humangenomeprivacy.org/2022/competition-tasks.html',
    ''
  ),
  (
    '12',
    'MICCAI',
    '',
    'miccai',
    'https://via.placeholder.com/300.png',
    'http://www.miccai.org/special-interest-groups/challenges/miccai-registered-challenges/',
    ''
  ),
  (
    '13',
    'precisionFDA',
    '',
    'pfda',
    'https://via.placeholder.com/300.png',
    'https://precision.fda.gov/challenges',
    ''
  ),
  (
    '14',
    'sbv IMPROVER',
    '',
    'sbv-improver',
    'https://via.placeholder.com/300.png',
    'https://www.intervals.science/resources/sbv-improver',
    ''
  ),
  (
    '15',
    'NIH',
    '',
    'nih',
    'https://via.placeholder.com/300.png',
    'https://www.nih.gov/',
    ''
  ),
  (
    '16',
    'Allen Institute',
    '',
    'allen-institute',
    'https://via.placeholder.com/300.png',
    'https://alleninstitute.org/ ',
    ''
  ),
  (
    '17',
    'ALS Therapy Alliance',
    '',
    'ata',
    'https://via.placeholder.com/300.png',
    'https://alstherapyalliance.org/',
    ''
  ),
  (
    '18',
    'Alzheimer''s Disease Neuroimaging Initiative',
    '',
    'adni',
    'https://via.placeholder.com/300.png',
    'http://adni.loni.usc.edu/',
    ''
  ),
  (
    '19',
    'Alzheimer''s Research UK',
    '',
    'alzheimers-research-uk',
    'https://via.placeholder.com/300.png',
    'https://www.alzheimersresearchuk.org/',
    ''
  ),
  (
    '20',
    'Amazon Web Services',
    '',
    'aws',
    'https://via.placeholder.com/300.png',
    'https://aws.amazon.com/',
    ''
  ),
  (
    '21',
    'American Joint Committee on Cancer',
    '',
    'ajcc',
    'https://via.placeholder.com/300.png',
    'https://www.facs.org/quality-programs/cancer/ajcc',
    ''
  ),
  (
    '22',
    'APOLLO network',
    '',
    'apollo',
    'https://via.placeholder.com/300.png',
    'https://proteomics.cancer.gov/programs/apollo-network',
    ''
  ),
  (
    '23',
    'Apple Health',
    '',
    'apple-health',
    'https://via.placeholder.com/300.png',
    'https://www.hca.wa.gov/health-care-services-supports/apple-health-medicaid-coverage',
    ''
  ),
  (
    '24',
    'Arthritis Foundation',
    '',
    'arthritis-foundation',
    'https://via.placeholder.com/300.png',
    'https://www.arthritis.org/',
    ''
  ),
  (
    '25',
    'Arthritis Internet Registry',
    '',
    'arthritis-internet-registry',
    'https://via.placeholder.com/300.png',
    'https://www.arthritis-research.org/join-research/arthritis-internet-registry',
    ''
  ),
  (
    '26',
    'AstraZeneca',
    '',
    'astrazeneca',
    'https://via.placeholder.com/300.png',
    'https://www.astrazeneca.com/',
    ''
  ),
  (
    '27',
    'Autodesk',
    '',
    'autodesk',
    'https://via.placeholder.com/300.png',
    'https://www.autodesk.com/',
    ''
  ),
  (
    '28',
    'BC Cancer Research Centre',
    '',
    'bccrc',
    'https://via.placeholder.com/300.png',
    'https://www.bccrc.ca/',
    ''
  ),
  (
    '29',
    'Bellvitge Institute for Biomedical Research',
    '',
    'idibell',
    'https://via.placeholder.com/300.png',
    'https://www.ub.edu/web/ub/en/recerca_innovacio/recerca_a_la_UB/instituts/institutsparticipats/idibell.html',
    ''
  ),
  (
    '30',
    'Berlin Institute of Health',
    '',
    'bih',
    'https://via.placeholder.com/300.png',
    'https://www.bihealth.org/en/',
    ''
  ),
  (
    '31',
    'Bill and Melinda Gates Foundation',
    '',
    'bill-and-melinda-gates-foundation',
    'https://via.placeholder.com/300.png',
    'https://www.gatesfoundation.org/',
    ''
  ),
  (
    '32',
    'Biogen',
    '',
    'biogen',
    'https://via.placeholder.com/300.png',
    'https://www.biogen.com/en_us/home.html',
    ''
  ),
  (
    '33',
    'BioMarin Pharmaceutical Inc.',
    '',
    'biomarin-',
    'https://via.placeholder.com/300.png',
    'https://www.biomarin.com/',
    ''
  ),
  (
    '34',
    'Booz Allen Hamilton',
    '',
    'booz-allen',
    'https://via.placeholder.com/300.png',
    'https://www.boozallen.com/',
    'Booz Allen Hamilton has been at the forefront of strategy and technology for more than 100 years. Today, the firm provides management and technology consulting and engineering services to leading Fortune 500 corporations, governments, and not-for-profits across the globe. Bo...'
  ),
  (
    '35',
    'Braille Authority of North America',
    '',
    'bana',
    'https://via.placeholder.com/300.png',
    'http://www.brailleauthority.org/',
    ''
  ),
  (
    '36',
    'Breast Cancer Surveillance Consortium',
    '',
    'bcsc',
    'https://via.placeholder.com/300.png',
    'https://www.bcsc-research.org/',
    ''
  ),
  (
    '37',
    'Brigham And Women''s Hospital',
    '',
    'ƒnumer',
    'https://via.placeholder.com/300.png',
    'https://www.brighamandwomens.org/',
    ''
  ),
  (
    '38',
    'Brigham Young University',
    '',
    'byu',
    'https://via.placeholder.com/300.png',
    'https://www.byu.edu/',
    ''
  ),
  (
    '39',
    'BrightFocus Foundation',
    '',
    'brightfocus-foundation',
    'https://via.placeholder.com/300.png',
    'https://www.brightfocus.org/',
    ''
  ),
  (
    '40',
    'Bristol Myers Squibb',
    '',
    'bms',
    'https://via.placeholder.com/300.png',
    'https://www.bms.com/',
    ''
  ),
  (
    '41',
    'Broad Institute',
    '',
    'broad',
    'https://via.placeholder.com/300.png',
    'https://www.broadinstitute.org/',
    ''
  ),
  (
    '42',
    'Brown University',
    '',
    'brown',
    'https://via.placeholder.com/300.png',
    'https://www.brown.edu/',
    ''
  ),
  (
    '43',
    'California Institute of Technology',
    '',
    'caltech',
    'https://via.placeholder.com/300.png',
    'https://www.caltech.edu/',
    ''
  ),
  (
    '44',
    'Cancer Imaging Archive',
    '',
    'tcia',
    'https://via.placeholder.com/300.png',
    'https://www.cancerimagingarchive.net/',
    ''
  ),
  (
    '45',
    'Cancer Research UK',
    '',
    'cancer-research-uk',
    'https://via.placeholder.com/300.png',
    'https://www.cancerresearchuk.org/',
    ''
  ),
  (
    '46',
    'Cancer Target Discovery and Development',
    '',
    'cdt2',
    'https://via.placeholder.com/300.png',
    'https://ocg.cancer.gov/programs/ctd2',
    ''
  ),
  (
    '47',
    'Celgene',
    '',
    'celgene',
    'https://via.placeholder.com/300.png',
    'https://www.celgene.com',
    ''
  ),
  (
    '48',
    'Center for Research Computing',
    '',
    'center-for-research-computing',
    'https://via.placeholder.com/300.png',
    'https://crc.nd.edu/',
    ''
  ),
  (
    '49',
    'Cincinnati Children''s Hospital Medical Center',
    '',
    'cchmc',
    'https://via.placeholder.com/300.png',
    'https://www.cincinnatichildrens.org/',
    ''
  ),
  (
    '50',
    'Climb 4 Kidney Cancer',
    '',
    'c4kc',
    'https://via.placeholder.com/300.png',
    'https://climb4kc.org/',
    ''
  ),
  (
    '51',
    'Clinical Proteomic Tumor Analysis Consortium',
    '',
    'cptac',
    'https://via.placeholder.com/300.png',
    'https://proteomics.cancer.gov/programs/cptac',
    ''
  ),
  (
    '52',
    'Columbia University',
    '',
    'columbia',
    'https://via.placeholder.com/300.png',
    'https://www.columbia.edu/',
    ''
  ),
  (
    '53',
    'Conceptant',
    '',
    'conceptant',
    'https://via.placeholder.com/300.png',
    'https://www.conceptant.com/',
    ''
  ),
  (
    '54',
    'Consejo Superior de Investigaciones Cientificas',
    '',
    'csic',
    'https://via.placeholder.com/300.png',
    'https://www.csic.es/',
    ''
  ),
  (
    '55',
    'CorEvitas',
    '',
    'cor-evitas',
    'https://via.placeholder.com/300.png',
    'https://www.corevitas.com/',
    ''
  ),
  (
    '56',
    'Corrona',
    '',
    'corrona',
    'https://via.placeholder.com/300.png',
    'https://www.corrona.org/',
    ''
  ),
  (
    '57',
    'Covert Lab',
    '',
    'covert-lab',
    'https://via.placeholder.com/300.png',
    'https://www.covert.stanford.edu/',
    ''
  ),
  (
    '58',
    'Dana-Farber Cancer Institute',
    '',
    'dfci',
    'https://via.placeholder.com/300.png',
    'https://www.dana-farber.org/',
    ''
  ),
  (
    '59',
    'Defense Advanced Research Projects Agency',
    '',
    'darpa',
    'https://via.placeholder.com/300.png',
    'https://www.darpa.mil/',
    ''
  ),
  (
    '60',
    'Department of Energy',
    '',
    'doe',
    'https://via.placeholder.com/300.png',
    'https://www.energy.gov/',
    ''
  ),
  (
    '61',
    'Diagnosticos da America SA',
    '',
    'dasa',
    'https://via.placeholder.com/300.png',
    'https://dasa.com.br/',
    ''
  ),
  (
    '62',
    'DNAnexus',
    '',
    'dnanexus',
    'https://via.placeholder.com/300.png',
    'https://www.dnanexus.com/',
    ''
  ),
  (
    '63',
    'Dockstore',
    '',
    'dockstore',
    'https://via.placeholder.com/300.png',
    'https://dockstore.org/',
    ''
  ),
  (
    '64',
    'Duke University',
    '',
    'duke',
    'https://via.placeholder.com/300.png',
    'https://duke.edu/',
    ''
  ),
  (
    '65',
    'VA Durham Health Care',
    '',
    'va-durham-health-care',
    'https://via.placeholder.com/300.png',
    'https://www.durham.va.gov/ ',
    ''
  ),
  (
    '66',
    'Early Signal Foundation',
    '',
    'early-signal',
    'https://via.placeholder.com/300.png',
    'http://www.earlysignal.org',
    ''
  ),
  (
    '67',
    'Eck Institute for Global Health',
    '',
    'eck-institute-for-global-health',
    'https://via.placeholder.com/300.png',
    'https://globalhealth.nd.edu/',
    ''
  ),
  (
    '68',
    'Eli Lilly and Company',
    '',
    'lilly',
    'https://via.placeholder.com/300.png',
    'https://www.lilly.com/',
    ''
  ),
  (
    '69',
    'Elixir',
    '',
    'elixir',
    'https://via.placeholder.com/300.png',
    'https://www.elixirsolutions.com/',
    ''
  ),
  (
    '70',
    'Encyclopedia of DNA Elements Data Coordinating Center',
    '',
    'encode',
    'https://via.placeholder.com/300.png',
    'https://www.encodeproject.org/',
    ''
  ),
  (
    '71',
    'ENIGMA Consortium',
    '',
    'enigma',
    'https://via.placeholder.com/300.png',
    'http://enigma.ini.usc.edu/',
    ''
  ),
  (
    '72',
    'ETH Zurich',
    '',
    'eth',
    'https://via.placeholder.com/300.png',
    'https://ethz.ch/en.html',
    ''
  ),
  (
    '73',
    'Eunice Kennedy Shriver National Institute',
    '',
    'nichd',
    'https://via.placeholder.com/300.png',
    'https://www.nichd.nih.gov/',
    ''
  ),
  (
    '74',
    'European Bioinformatics Institute',
    '',
    'embl-ebi',
    'https://via.placeholder.com/300.png',
    'https://www.ebi.ac.uk/',
    ''
  ),
  (
    '75',
    'European Medicines Agency',
    '',
    'european-medicines-agency',
    'https://via.placeholder.com/300.png',
    'https://www.ema.europa.eu/en',
    ''
  ),
  (
    '76',
    'European Union',
    '',
    'eu',
    'https://via.placeholder.com/300.png',
    'https://europa.eu/european-union/index_en',
    ''
  ),
  (
    '77',
    'Evidation Health',
    '',
    'evidation',
    'https://via.placeholder.com/300.png',
    'https://evidation.com/',
    ''
  ),
  (
    '78',
    'Fehling Instruments',
    '',
    'fehling-instruments',
    'https://via.placeholder.com/300.png',
    'https://www.fehling-instruments.de/en/',
    ''
  ),
  (
    '79',
    'Feinstein Institutes for Medical Research',
    '',
    'feinstein-institute',
    'https://via.placeholder.com/300.png',
    'https://feinstein.northwell.edu/',
    ''
  ),
  (
    '80',
    'Francis Crick Institute',
    '',
    'francis-crick-institute',
    'https://via.placeholder.com/300.png',
    'https://www.crick.ac.uk/',
    ''
  ),
  (
    '81',
    'Fred Hutchinson Cancer Research Center',
    '',
    'fred-hutchinson-cancer-research-center',
    'https://via.placeholder.com/300.png',
    'https://www.fredhutch.org/en/about/education-outreach/coding-for-cancer.html',
    ''
  ),
  (
    '82',
    'Genome Canada',
    '',
    'genome-canada',
    'https://via.placeholder.com/300.png',
    'https://www.genomecanada.ca/',
    ''
  ),
  (
    '83',
    'George Washington University',
    '',
    'gwu',
    'https://via.placeholder.com/300.png',
    'https://www.gwu.edu/',
    ''
  ),
  (
    '84',
    'Georgetown University',
    '',
    'georgetown-university',
    'https://via.placeholder.com/300.png',
    'https://www.georgetown.edu/',
    ''
  ),
  (
    '85',
    'German Cancer Research Center',
    '',
    'dkfz',
    'https://via.placeholder.com/300.png',
    'https://www.dkfz.de/en/index.html',
    ''
  ),
  (
    '86',
    'Global Alliance for Genomics and Health',
    '',
    'ga4gh',
    'https://via.placeholder.com/300.png',
    'https://www.ga4gh.org/',
    ''
  ),
  (
    '87',
    'H. Lee Moffitt Cancer Center and Research Institute',
    '',
    'moffitt',
    'https://via.placeholder.com/300.png',
    'https://moffitt.org/',
    ''
  ),
  (
    '88',
    'H3ABioNet',
    '',
    'h3abionet',
    'https://via.placeholder.com/300.png',
    'https://h3abionet.org/',
    ''
  ),
  (
    '89',
    'Harvard University',
    '',
    'harvard',
    'https://via.placeholder.com/300.png',
    'https://www.harvard.edu/',
    ''
  ),
  (
    '90',
    'Heidelberg University',
    '',
    'heidelberg-university',
    'https://via.placeholder.com/300.png',
    'https://www.heidelberg.edu/',
    ''
  ),
  (
    '91',
    'HistoSonics Inc.',
    '',
    'histosonics-inc.',
    'https://via.placeholder.com/300.png',
    'https://histosonics.com/',
    ''
  ),
  (
    '92',
    'Hospital for Sick Children',
    '',
    'sickkids',
    'https://via.placeholder.com/300.png',
    'https://www.sickkids.ca/Research/',
    ''
  ),
  (
    '93',
    'Human Protein Atlas',
    '',
    'hpa',
    'https://via.placeholder.com/300.png',
    'www.proteinatlas.org',
    'The Human Protein Atlas is a Swedish-based program initiated in 2003 with the aim to map the expression and spatial distribution of all human proteins in cells and tissues using an integration of various omics technologies, including antibody-based imaging, mass spectrometry...'
  ),
  (
    '94',
    'IBM',
    '',
    'ibm',
    'https://via.placeholder.com/300.png',
    'https://www.research.ibm.com/',
    ''
  ),
  (
    '95',
    'Innovative Medicines Initiative',
    '',
    'imi',
    'https://via.placeholder.com/300.png',
    'http://www.imi.europa.eu/',
    ''
  ),
  (
    '96',
    'Institut Curie',
    '',
    'institut-curie',
    'https://via.placeholder.com/300.png',
    'https://institut-curie.org/',
    ''
  ),
  (
    '97',
    'Institute for Molecular Medicine Finland',
    '',
    'fimm',
    'https://via.placeholder.com/300.png',
    'https://www.fimm.fi/en/',
    ''
  ),
  (
    '98',
    'Institute of Translational Health Sciences',
    '',
    'iths',
    'https://via.placeholder.com/300.png',
    'https://www.iths.org/',
    ''
  ),
  (
    '99',
    'Intel',
    '',
    'intel',
    'https://via.placeholder.com/300.png',
    'https://www.intel.com/content/www/us/en/homepage.html',
    'Intel(R) Software sits at the intersection of hardware, interoperability, and amazing customer experiences. We partner with the global technology ecosystem to make development EASY, OPEN, and SCALABLE so developers can do what they do best: deliver groundbreaking application...'
  ),
  (
    '100',
    'International Cancer Genome Consortium',
    '',
    'icgc',
    'https://via.placeholder.com/300.png',
    'https://dcc.icgc.org/',
    ''
  ),
  (
    '101',
    'International Flavors and Fragrances Inc.',
    '',
    'iff',
    'https://via.placeholder.com/300.png',
    'https://www.iff.com/',
    ''
  ),
  (
    '102',
    'International Genome Sample Resource',
    '',
    'igsr',
    'https://via.placeholder.com/300.png',
    'https://www.internationalgenome.org/home',
    ''
  ),
  (
    '103',
    'International Society for Computational Biology',
    '',
    'cosi',
    'https://via.placeholder.com/300.png',
    'https://www.iscb.org/cms_addon/conferences/ismbeccb2021/tracks/function',
    ''
  ),
  (
    '104',
    'Intuitive Surgical Inc.',
    '',
    'intuitive',
    'https://via.placeholder.com/300.png',
    'https://www.intuitive.com/en-us',
    ''
  ),
  (
    '105',
    'Iowa State University',
    '',
    'iowa-state-university',
    'https://via.placeholder.com/300.png',
    'https://www.iastate.edu/',
    ''
  ),
  (
    '106',
    'Kaggle',
    '',
    'kaggle',
    'https://via.placeholder.com/300.png',
    'https://www.kaggle.com/',
    'Kaggle is a community of data scientists and data enthusiasts. Our platform enables you to learn from and mentor each other on your personal, academic, and professional data science journeys. \n\nTo get involved, you can [enter a machine learning competition](https://www.kag...'
  ),
  (
    '107',
    'King''s College London',
    '',
    'kcl',
    'https://via.placeholder.com/300.png',
    'https://www.kcl.ac.uk/',
    ''
  ),
  (
    '108',
    'KnowEnG',
    '',
    'knoweng',
    'https://via.placeholder.com/300.png',
    'https://knoweng.org/',
    ''
  ),
  (
    '109',
    'Koch Institute',
    '',
    'koch-institute',
    'https://via.placeholder.com/300.png',
    'https://ki.mit.edu/',
    ''
  ),
  (
    '110',
    'Laura and John Arnold Foundation',
    '',
    'arnold-ventures',
    'https://via.placeholder.com/300.png',
    'https://www.arnoldventures.org/people/laura-arnold-john-arnold/',
    ''
  ),
  (
    '111',
    'Lausanne University Hospital',
    '',
    'chuv',
    'https://via.placeholder.com/300.png',
    'https://www.lausanneuniversityhospital.com/home',
    ''
  ),
  (
    '112',
    'Leukemia and Lymphoma Society',
    '',
    'lls',
    'https://via.placeholder.com/300.png',
    'https://www.lls.org/',
    ''
  ),
  (
    '113',
    'London''s Global University',
    '',
    'ucl',
    'https://via.placeholder.com/300.png',
    'https://www.ucl.ac.uk/',
    ''
  ),
  (
    '114',
    'Ludwig Maximilian University of Munich',
    '',
    'lmu-munich',
    'https://via.placeholder.com/300.png',
    'https://www.en.uni-muenchen.de/index.html',
    ''
  ),
  (
    '115',
    'Mahidol Oxford Tropical Medicine Research Unit',
    '',
    'moru',
    'https://via.placeholder.com/300.png',
    'https://www.tropmedres.ac/',
    ''
  ),
  (
    '116',
    'March of Dimes',
    '',
    'march-of-dimes',
    'https://via.placeholder.com/300.png',
    'https://www.marchofdimes.org/',
    ''
  ),
  (
    '117',
    'Massachusetts General Hospital',
    '',
    'mgh',
    'https://via.placeholder.com/300.png',
    'https://www.massgeneral.org/',
    ''
  ),
  (
    '118',
    'Massachusetts Institute of Technology',
    '',
    'mit',
    'https://via.placeholder.com/300.png',
    'https://www.mit.edu/',
    ''
  ),
  (
    '119',
    'MathWorks',
    '',
    'mathworks',
    'https://via.placeholder.com/300.png',
    'https://www.mathworks.com/',
    ''
  ),
  (
    '120',
    'Max Delbruck Center for Molecular Medicine',
    '',
    'mdc',
    'https://via.placeholder.com/300.png',
    'https://www.mdc-berlin.de/',
    ''
  ),
  (
    '121',
    'MD Anderson Cancer Center',
    '',
    'md-anderson-cancer-center',
    'https://via.placeholder.com/300.png',
    'https://www.mdanderson.org/',
    ''
  ),
  (
    '122',
    'Medical Research Council',
    '',
    'mrc',
    'https://via.placeholder.com/300.png',
    'https://mrc.ukri.org/',
    ''
  ),
  (
    '123',
    'Memorial Sloan Kettering Cancer Center',
    '',
    'msk',
    'https://via.placeholder.com/300.png',
    'https://www.mskcc.org/',
    ''
  ),
  (
    '124',
    'Merck Co.',
    '',
    'merck',
    'https://via.placeholder.com/300.png',
    'https://www.merck.com/',
    ''
  ),
  (
    '125',
    'Michael J. Fox Foundation',
    '',
    'michael-j.-fox-foundation',
    'https://via.placeholder.com/300.png',
    'https://www.michaeljfox.org/',
    ''
  ),
  (
    '126',
    'MINES ParisTech',
    '',
    'mines-paristech',
    'https://via.placeholder.com/300.png',
    'http://www.mines-paristech.eu/',
    ''
  ),
  (
    '127',
    'Mount Sinai',
    '',
    'mt.-sinai',
    'https://via.placeholder.com/300.png',
    'https://www.mountsinai.org/',
    ''
  ),
  (
    '128',
    'Nathan S. Kline Institute for Psychiatric Research',
    '',
    'nki',
    'https://via.placeholder.com/300.png',
    'https://www.nki.rfmh.org/',
    ''
  ),
  (
    '129',
    'National Cancer Institute',
    '',
    'nci',
    'https://via.placeholder.com/300.png',
    'https://www.cancer.gov/',
    ''
  ),
  (
    '130',
    'National Center for Advancing Translational Sciences',
    '',
    'ncats',
    'https://via.placeholder.com/300.png',
    'https://ncats.nih.gov/',
    ''
  ),
  (
    '131',
    'National Center for Data to Health',
    '',
    'cd2h',
    'https://via.placeholder.com/300.png',
    'https://cd2h.org/',
    ''
  ),
  (
    '132',
    'National Institute of Environmental Health Sciences',
    '',
    'niehs',
    'https://via.placeholder.com/300.png',
    'https://www.niehs.nih.gov/',
    ''
  ),
  (
    '133',
    'National Institute of General Medical Sciences',
    '',
    'nigms',
    'https://via.placeholder.com/300.png',
    'https://www.nigms.nih.gov/',
    ''
  ),
  (
    '134',
    'National Institute of Standards and Technology',
    '',
    'nist',
    'https://via.placeholder.com/300.png',
    'https://www.nist.gov/',
    ''
  ),
  (
    '135',
    'National Science Foundation',
    '',
    'nsf',
    'https://via.placeholder.com/300.png',
    'https://www.nsf.gov/',
    ''
  ),
  (
    '136',
    'Natural Sciences and Engineering Research Council',
    '',
    'nserc',
    'https://via.placeholder.com/300.png',
    'https://www.nserc-crsng.gc.ca/index_eng.asp',
    ''
  ),
  (
    '137',
    'Neosoma Inc.',
    '',
    'neosoma-inc.',
    'https://via.placeholder.com/300.png',
    'https://neosomainc.com/',
    ''
  ),
  (
    '138',
    'Neurological Clinical Research Institute',
    '',
    'ncri',
    'https://via.placeholder.com/300.png',
    'https://www.massgeneral.org/ncri',
    ''
  ),
  (
    '139',
    'New York University',
    '',
    'nyc',
    'https://via.placeholder.com/300.png',
    'https://www.nyu.edu/',
    ''
  ),
  (
    '140',
    'Northeast ALS Consortium',
    '',
    'neals',
    'https://via.placeholder.com/300.png',
    'https://www.neals.org/',
    ''
  ),
  (
    '141',
    'Northeastern University',
    '',
    'neu',
    'https://via.placeholder.com/300.png',
    'https://www.northeastern.edu/',
    ''
  ),
  (
    '142',
    'Northwestern University',
    '',
    'nu',
    'https://via.placeholder.com/300.png',
    'https://www.northwestern.edu/',
    ''
  ),
  (
    '143',
    'Novo Nordisk',
    '',
    'novo-nordisk',
    'https://via.placeholder.com/300.png',
    'https://www.novonordisk-us.com/',
    ''
  ),
  (
    '144',
    'Numerate',
    '',
    'numerate',
    'https://via.placeholder.com/300.png',
    'http://www.numerate.com/',
    ''
  ),
  (
    '145',
    'NVIDIA',
    '',
    'nvidia',
    'https://via.placeholder.com/300.png',
    'https://www.nvidia.com/en-us/',
    ''
  ),
  (
    '146',
    'Ohio State University',
    '',
    'osu',
    'https://via.placeholder.com/300.png',
    'https://www.osu.edu/',
    ''
  ),
  (
    '147',
    'Ontario Institute for Cancer Research',
    '',
    'oicr',
    'https://via.placeholder.com/300.png',
    'https://oicr.on.ca/',
    ''
  ),
  (
    '148',
    'Oregon Health and Science University',
    '',
    'ohsu',
    'https://via.placeholder.com/300.png',
    'https://www.ohsu.edu/',
    ''
  ),
  (
    '149',
    'Oslo University Hospital',
    '',
    'oslo-university-hospital',
    'https://via.placeholder.com/300.png',
    'https://oslo-universitetssykehus.no/oslo-university-hospital',
    ''
  ),
  (
    '150',
    'Pacific Northwest National Laboratory',
    '',
    'pnnl',
    'https://via.placeholder.com/300.png',
    'https://www.pnnl.gov/',
    ''
  ),
  (
    '151',
    'Pfizer',
    '',
    'pfizer',
    'https://via.placeholder.com/300.png',
    'https://www.pfizer.com/',
    ''
  ),
  (
    '152',
    'Prize4Life',
    '',
    'prize4life',
    'https://via.placeholder.com/300.png',
    'https://en.wikipedia.org/wiki/Prize4Life',
    ''
  ),
  (
    '153',
    'Prostate Cancer Canada',
    '',
    'prostate-cancer-canada',
    'https://via.placeholder.com/300.png',
    'https://cancer.ca/en/about-us/prostate-cancer',
    ''
  ),
  (
    '154',
    'Prostate Cancer Foundation',
    '',
    'pcf',
    'https://via.placeholder.com/300.png',
    'https://www.pcf.org/',
    ''
  ),
  (
    '155',
    'Providence Health and Services',
    '',
    'providence',
    'https://via.placeholder.com/300.png',
    'https://www.providence.org/en',
    ''
  ),
  (
    '156',
    'QIMR Berghofer Medical Research Institute',
    '',
    'qimr-berghofer',
    'https://via.placeholder.com/300.png',
    'https://www.qimrberghofer.edu.au/',
    ''
  ),
  (
    '157',
    'Queen''s University',
    '',
    'queens',
    'https://via.placeholder.com/300.png',
    'https://www.queensu.ca/',
    ''
  ),
  (
    '158',
    'Radboud University',
    '',
    'radboudumc',
    'https://via.placeholder.com/300.png',
    'https://www.radboudumc.nl/en/research',
    ''
  ),
  (
    '159',
    'Radiological Society of North America',
    '',
    'rsna',
    'https://via.placeholder.com/300.png',
    'https://www.rsna.org/',
    'The Radiological Society of North America (RSNA(R)) is an international society of radiologists, medical physicists and other medical professionals with more than 53,400 members from 136 countries across the globe. RSNA hosts the world’s premier radiology forum, drawing appr...'
  ),
  (
    '160',
    'Ray and Dagmar Dolby Family Fund',
    '',
    'ray-and-dagmar-dolby-family-fund',
    'https://via.placeholder.com/300.png',
    'http://www.dolbyventures.com/',
    ''
  ),
  (
    '161',
    'Rice University',
    '',
    'rice',
    'https://via.placeholder.com/300.png',
    'https://www.rice.edu/',
    ''
  ),
  (
    '162',
    'Robert Wood Johnson Foundation',
    '',
    'rwjf',
    'https://via.placeholder.com/300.png',
    'https://www.rwjf.org/',
    ''
  ),
  (
    '163',
    'Rockefeller University',
    '',
    'rockefeller',
    'https://via.placeholder.com/300.png',
    'https://www.rockefeller.edu/',
    ''
  ),
  (
    '164',
    'Rosenberg Alzheimer''s Project',
    '',
    'rosenberg-alzheimers-project',
    'https://via.placeholder.com/300.png',
    'https://en.wikipedia.org/wiki/Douglas_Rosenberg',
    ''
  ),
  (
    '165',
    'Rush University Medical Center',
    '',
    'rush',
    'https://via.placeholder.com/300.png',
    'https://www.rush.edu/',
    ''
  ),
  (
    '166',
    'RWTH Aachen University',
    '',
    'rwth-aachen',
    'https://via.placeholder.com/300.png',
    'https://www.rwth-aachen.de/go/id/a/?lidx=1',
    ''
  ),
  (
    '167',
    'Sage Bionetworks',
    '',
    'sage',
    'https://via.placeholder.com/300.png',
    'https://sagebionetworks.org/',
    ''
  ),
  (
    '168',
    'Sanofi',
    '',
    'sanofi',
    'https://via.placeholder.com/300.png',
    'https://www.sanofi.com/',
    ''
  ),
  (
    '169',
    'Sapienza University of Rome',
    '',
    'bologna',
    'https://via.placeholder.com/300.png',
    'https://www.uniroma1.it/en/pagina-strutturale/home',
    ''
  ),
  (
    '170',
    'Sartorius AG',
    '',
    'sartorius',
    'https://via.placeholder.com/300.png',
    'https://www.sartorius.com/en',
    'Sartorius AG is an international pharmaceutical and laboratory equipment supplier, covering the segments of Bioprocess Solutions and Lab Products & Services.'
  ),
  (
    '171',
    'Seattle Cancer Care Alliance',
    '',
    'scca',
    'https://via.placeholder.com/300.png',
    'https://www.seattlecca.org/',
    ''
  ),
  (
    '172',
    'Semmelweis University',
    '',
    'semmelweis-university',
    'https://via.placeholder.com/300.png',
    'https://semmelweis.hu/english/',
    ''
  ),
  (
    '173',
    'Sentieon',
    '',
    'sentieon',
    'https://via.placeholder.com/300.png',
    'https://www.sentieon.com/',
    ''
  ),
  (
    '174',
    'Siemens Healthineers',
    '',
    'siemens-healthineers',
    'https://via.placeholder.com/300.png',
    'https://www.siemens-healthineers.com/',
    ''
  ),
  (
    '175',
    'Stanford University',
    '',
    'stanford',
    'https://via.placeholder.com/300.png',
    'https://www.stanford.edu/',
    ''
  ),
  (
    '176',
    'Swiss Initiative in Systems Biology',
    '',
    'systemsx',
    'https://via.placeholder.com/300.png',
    'http://www.systemsx.ch/',
    ''
  ),
  (
    '177',
    'Takeda',
    '',
    'takeda',
    'https://via.placeholder.com/300.png',
    'https://www.takeda.com/en-us/',
    ''
  ),
  (
    '178',
    'Texas Biomedical Research Institute',
    '',
    'texas-biomedical-research-institute',
    'https://via.placeholder.com/300.png',
    'https://www.txbiomed.org/',
    ''
  ),
  (
    '180',
    'The University of California-Davis',
    '',
    'uc-davis',
    'https://via.placeholder.com/300.png',
    'https://www.ucdavis.edu/',
    ''
  ),
  (
    '181',
    'The University of Texas at Austin',
    '',
    'ut',
    'https://via.placeholder.com/300.png',
    'https://www.utexas.edu/',
    ''
  ),
  (
    '182',
    'Thomas Jefferson University Hospital',
    '',
    'thomas-jefferson-university-hospital',
    'https://via.placeholder.com/300.png',
    'https://hospitals.jefferson.edu/',
    ''
  ),
  (
    '183',
    'TracInnovations',
    '',
    'tracinnovations',
    'https://via.placeholder.com/300.png',
    'https://tracinnovations.com/',
    ''
  ),
  (
    '184',
    'Trinity College Institute of Neuroscience',
    '',
    'tcd---neuroscience',
    'https://via.placeholder.com/300.png',
    'https://www.tcd.ie/Neuroscience/',
    ''
  ),
  (
    '185',
    'Tulane University',
    '',
    'tulane',
    'https://via.placeholder.com/300.png',
    'https://tulane.edu/',
    ''
  ),
  (
    '186',
    'U.S. Food and Drug Administration',
    '',
    'fda',
    'https://via.placeholder.com/300.png',
    'https://www.fda.gov/home',
    ''
  ),
  (
    '187',
    'UNC Eshelman School of Pharmacy',
    '',
    'unc-eshelman-school-of-pharmacy',
    'https://via.placeholder.com/300.png',
    'https://pharmacy.unc.edu/',
    ''
  ),
  (
    '188',
    'University of Alabama',
    '',
    'ua',
    'https://via.placeholder.com/300.png',
    'https://www.ua.edu/',
    ''
  ),
  (
    '189',
    'University of Alabama at Birmingham',
    '',
    'uab',
    'https://via.placeholder.com/300.png',
    'https://www.uab.edu/home/',
    ''
  ),
  (
    '190',
    'University of Arkansas for Medical Sciences',
    '',
    'uams',
    'https://via.placeholder.com/300.png',
    'https://www.uams.edu/',
    ''
  ),
  (
    '191',
    'University of Basel',
    '',
    'university-of-basel',
    'https://via.placeholder.com/300.png',
    'https://www.unibas.ch/en.html',
    ''
  ),
  (
    '192',
    'University of California San Diego',
    '',
    'ucsd',
    'https://via.placeholder.com/300.png',
    'https://ucsd.edu/',
    ''
  ),
  (
    '193',
    'University of California San Francisco',
    '',
    'ucsf',
    'https://via.placeholder.com/300.png',
    'https://www.ucsf.edu/',
    ''
  ),
  (
    '194',
    'University of California Santa Cruz',
    '',
    'ucsc',
    'https://via.placeholder.com/300.png',
    'https://www.ucsc.edu/',
    ''
  ),
  (
    '195',
    'University of Cincinnati',
    '',
    'uc',
    'https://via.placeholder.com/300.png',
    'https://www.uc.edu/',
    ''
  ),
  (
    '196',
    'University of Colorado Anschutz Medical Campus',
    '',
    'cu-anschutz',
    'https://via.placeholder.com/300.png',
    'https://www.cuanschutz.edu/',
    ''
  ),
  (
    '197',
    'University of Connecticut',
    '',
    'uconn',
    'https://via.placeholder.com/300.png',
    'https://uconn.edu/',
    ''
  ),
  (
    '198',
    'University of Houston',
    '',
    'uh',
    'https://via.placeholder.com/300.png',
    'https://www.uh.edu/',
    ''
  ),
  (
    '199',
    'University of Illinois Urbana-Champaign',
    '',
    'uiuc',
    'https://via.placeholder.com/300.png',
    'https://illinois.edu/',
    ''
  ),
  (
    '200',
    'University of Kent',
    '',
    'university-of-kent',
    'https://via.placeholder.com/300.png',
    'https://www.kent.ac.uk/',
    ''
  ),
  (
    '201',
    'University of Kentucky',
    '',
    'uky',
    'https://via.placeholder.com/300.png',
    'http://www.uky.edu/',
    ''
  ),
  (
    '202',
    'University of Lausanne',
    '',
    'unil',
    'https://via.placeholder.com/300.png',
    'https://www.unil.ch/central/en/home.html',
    ''
  ),
  (
    '203',
    'University of Lisbon',
    '',
    'u-lisbon',
    'https://via.placeholder.com/300.png',
    'https://www.ulisboa.pt/en',
    ''
  ),
  (
    '204',
    'University of London',
    '',
    'uol',
    'https://via.placeholder.com/300.png',
    'https://london.ac.uk/',
    ''
  ),
  (
    '205',
    'University of Luxembourg',
    '',
    'university-of-luxembourg',
    'https://via.placeholder.com/300.png',
    'https://wwwen.uni.lu/',
    ''
  ),
  (
    '206',
    'University of Maryland',
    '',
    'umd',
    'https://via.placeholder.com/300.png',
    'https://www.umd.edu/',
    ''
  ),
  (
    '207',
    'University of Michigan',
    '',
    'umich',
    'https://via.placeholder.com/300.png',
    'https://umich.edu/',
    ''
  ),
  (
    '208',
    'University of North Carolina at Chapel Hill',
    '',
    'unc',
    'https://via.placeholder.com/300.png',
    'https://www.unc.edu/',
    ''
  ),
  (
    '209',
    'University of Notre Dame',
    '',
    'notre-dame',
    'https://via.placeholder.com/300.png',
    'https://www.nd.edu/',
    ''
  ),
  (
    '210',
    'University of Padova',
    '',
    'university-of-padova',
    'https://via.placeholder.com/300.png',
    'https://www.unipd.it/en/',
    ''
  ),
  (
    '211',
    'University of Padua',
    '',
    'university-of-padua',
    'https://via.placeholder.com/300.png',
    'https://www.unipd.it/en/',
    ''
  ),
  (
    '212',
    'University of Pennsylvania',
    '',
    'upenn',
    'https://via.placeholder.com/300.png',
    'https://www.upenn.edu/',
    ''
  ),
  (
    '213',
    'University of Rochester',
    '',
    'university-of-rochester',
    'https://via.placeholder.com/300.png',
    'https://www.urmedicine.org/',
    ''
  ),
  (
    '214',
    'University of South Florida',
    '',
    'usf',
    'https://via.placeholder.com/300.png',
    'https://www.usf.edu/',
    ''
  ),
  (
    '215',
    'University of Southampton',
    '',
    'university-of-southampton',
    'https://via.placeholder.com/300.png',
    'https://www.southampton.ac.uk/',
    ''
  ),
  (
    '216',
    'University of Texas Southwestern',
    '',
    'utsw',
    'https://via.placeholder.com/300.png',
    'https://www.utsouthwestern.edu/',
    ''
  ),
  (
    '217',
    'University of Toronto',
    '',
    'uoft',
    'https://via.placeholder.com/300.png',
    'https://www.utoronto.ca/',
    ''
  ),
  (
    '218',
    'University of Vermont',
    '',
    'uvm',
    'https://via.placeholder.com/300.png',
    'https://www.uvm.edu/',
    ''
  ),
  (
    '219',
    'University of Verona',
    '',
    'university-of-verona',
    'https://via.placeholder.com/300.png',
    'https://www.univr.it/en/international',
    ''
  ),
  (
    '220',
    'University of Virginia',
    '',
    'uva',
    'https://via.placeholder.com/300.png',
    'https://www.virginia.edu/',
    ''
  ),
  (
    '221',
    'University of Washington',
    '',
    'uw',
    'https://via.placeholder.com/300.png',
    'https://www.washington.edu/',
    ''
  ),
  (
    '222',
    'University of Wisconsin-Madison',
    '',
    'uw-madison',
    'https://via.placeholder.com/300.png',
    'https://www.wisc.edu/',
    ''
  ),
  (
    '223',
    'University of Zurich',
    '',
    'uzh',
    'https://via.placeholder.com/300.png',
    'https://www.uzh.ch/en.html',
    ''
  ),
  (
    '224',
    'Urban Green Energy',
    '',
    'uge',
    'https://via.placeholder.com/300.png',
    'https://www.ugei.com/',
    ''
  ),
  (
    '225',
    'US Army Medical Research Institute of Infectious Diseases',
    '',
    'usamriid',
    'https://via.placeholder.com/300.png',
    'https://www.usamriid.army.mil/',
    ''
  ),
  (
    '226',
    'Verily',
    '',
    'verily',
    'https://via.placeholder.com/300.png',
    'https://verily.com/',
    ''
  ),
  (
    '227',
    'VHA Innovation Ecosystem',
    '',
    'vha-ie',
    'https://via.placeholder.com/300.png',
    'https://www.va.gov/innovationecosystem/',
    ''
  ),
  (
    '228',
    'Washington University in St. Louis',
    '',
    'wustl',
    'https://via.placeholder.com/300.png',
    'https://wustl.edu/',
    ''
  ),
  (
    '229',
    'Wayne State University',
    '',
    'wayne-state-university',
    'https://via.placeholder.com/300.png',
    'https://wayne.edu/',
    ''
  ),
  (
    '230',
    'Weizmann Institute of Science',
    '',
    'weizmann-institute-of-science',
    'https://via.placeholder.com/300.png',
    'https://www.weizmann.ac.il/pages/',
    ''
  ),
  (
    '231',
    'Wellcome Sanger Institute',
    '',
    'sanger',
    'https://via.placeholder.com/300.png',
    'https://www.sanger.ac.uk/',
    ''
  ),
  (
    '232',
    'White House Office of Science and Technology Policy',
    '',
    'ostp',
    'https://via.placeholder.com/300.png',
    'https://www.whitehouse.gov/ostp/',
    ''
  ),
  (
    '233',
    'Multiple Myeloma Research Foundation',
    '',
    'mmrf',
    'https://via.placeholder.com/300.png',
    'https://themmrf.org/',
    ''
  ),
  (
    '234',
    'Kaiser Permanente Washington Health Research Institute',
    '',
    'kaiser',
    'https://via.placeholder.com/300.png',
    'https://www.kpwashingtonresearch.org/',
    ''
  );
