#!/usr/bin/env bash
set -eo pipefail

url="http://127.0.0.1:9200/_cat/health?h=status"

if health="$(curl --silent --show-error ${url})"; then
	if [ "$health" = 'green' ] || [ "$health" = 'yellow' ]; then
		exit 0
	fi

	echo >&2 "unexpected health status: $health"
fi

exit 1